openapi: 3.0.0
info:
  title: Square
  description: Use Square APIs to manage and run business including payment, customer,
    product, inventory, and employee management.
  termsOfService: https://connect.squareup.com/tos
  contact:
    name: Square Developer Platform
    url: https://squareup.com/developers
    email: developers@squareup.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "2.0"
  x-server-configuration:
    default-environment: production
    default-server: default
    environments:
    - name: production
      servers:
      - name: default
        url: https://connect.squareup.com
    - name: sandbox
      servers:
      - name: default
        url: https://connect.squareupsandbox.com
    - name: custom
      servers:
      - name: default
        url: '{custom_url}'
  x-square-generic-error-codes:
  - ACCESS_TOKEN_EXPIRED
  - ACCESS_TOKEN_REVOKED
  - API_VERSION_INCOMPATIBLE
  - APPLICATION_DISABLED
  - ARRAY_EMPTY
  - ARRAY_LENGTH_TOO_LONG
  - ARRAY_LENGTH_TOO_SHORT
  - BAD_CERTIFICATE
  - BAD_GATEWAY
  - BAD_REQUEST
  - CONFLICT
  - CONFLICTING_PARAMETERS
  - CURRENCY_MISMATCH
  - EXPECTED_ARRAY
  - EXPECTED_BASE64_ENCODED_BYTE_ARRAY
  - EXPECTED_BOOLEAN
  - EXPECTED_FLOAT
  - EXPECTED_INTEGER
  - EXPECTED_JSON_BODY
  - EXPECTED_MAP
  - EXPECTED_OBJECT
  - EXPECTED_STRING
  - FORBIDDEN
  - GATEWAY_TIMEOUT
  - GONE
  - IDEMPOTENCY_KEY_REUSED
  - INCORRECT_TYPE
  - INSUFFICIENT_SCOPES
  - INTERNAL_SERVER_ERROR
  - INVALID_ARRAY_VALUE
  - INVALID_CONTENT_TYPE
  - INVALID_CURSOR
  - INVALID_ENUM_VALUE
  - INVALID_FORM_VALUE
  - INVALID_SORT_ORDER
  - INVALID_SQUARE_VERSION_FORMAT
  - INVALID_TIME
  - INVALID_TIME_RANGE
  - INVALID_VALUE
  - LOCATION_MISMATCH
  - MAP_KEY_LENGTH_TOO_LONG
  - MAP_KEY_LENGTH_TOO_SHORT
  - MERCHANT_SUBSCRIPTION_NOT_FOUND
  - METHOD_NOT_ALLOWED
  - MISSING_REQUIRED_PARAMETER
  - NOT_ACCEPTABLE
  - NOT_FOUND
  - NOT_IMPLEMENTED
  - NO_FIELDS_SET
  - RATE_LIMITED
  - REQUEST_ENTITY_TOO_LARGE
  - REQUEST_TIMEOUT
  - SANDBOX_NOT_SUPPORTED
  - SERVICE_UNAVAILABLE
  - TOO_MANY_MAP_ENTRIES
  - UNAUTHORIZED
  - UNEXPECTED_VALUE
  - UNKNOWN_QUERY_PARAMETER
  - UNPROCESSABLE_ENTITY
  - UNSUPPORTED_MEDIA_TYPE
  - V1_ACCESS_TOKEN
  - V1_APPLICATION
  - VALUE_EMPTY
  - VALUE_REGEX_MISMATCH
  - VALUE_TOO_HIGH
  - VALUE_TOO_LONG
  - VALUE_TOO_LOW
  - VALUE_TOO_SHORT
servers:
- url: https://connect.squareup.com
paths:
  /mobile/authorization-code:
    post:
      tags:
      - MobileAuthorization
      summary: CreateMobileAuthorizationCode
      description: |-
        Generates code to authorize a mobile application to connect to a Square card reader

        Authorization codes are one-time-use and expire __60 minutes__ after being issued.

        __Important:__ The `Authorization` header you provide to this endpoint must have the following format:

        ```
        Authorization: Bearer ACCESS_TOKEN
        ```

        Replace `ACCESS_TOKEN` with a
        [valid production authorization credential](https://developer.squareup.com/docs/build-basics/access-tokens).
      operationId: CreateMobileAuthorizationCode
      security:
      - oauth2:
        - PAYMENTS_WRITE_IN_PERSON
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /oauth/protos/squareup/oauth/v1/api.proto
      x-proto-sha: 933b3a2bcf0d97135250f1654c43670d49e7ef30
  /oauth2/authorize:
    get:
      tags:
      - OAuth
      summary: Authorize
      description: "As part of a URL sent to a seller to authorize permissions for\
        \ \nthe developer, `Authorize` displays an authorization page and a \nlist\
        \ of requested permissions. This is not a callable API endpoint.\n\nThe completed\
        \ URL looks similar to the following example:\nhttps://connect.squareup.com/oauth2/authorize?client_id={YOUR_APP_ID}&scope=CUSTOMERS_WRITE+CUSTOMERS_READ&session=False&state=82201dd8d83d23cc8a48caf52b\n\
        \nThe seller can approve or deny the permissions. If approved,` Authorize`\
        \ \nreturns an `AuthorizeResponse` that is sent to the redirect URL and includes\
        \ \na state string and an authorization code. The code is used in the `ObtainToken`\
        \ \ncall to obtain an access token and a refresh token that the developer\
        \ uses \nto manage resources on behalf of the seller.\n\n__Important:__ The\
        \ `AuthorizeResponse` is sent to the redirect URL that you set on \nthe OAuth\
        \ page of your application in the Developer Dashboard.\n\nIf an error occurs\
        \ or the seller denies the request, `Authorize` returns an \nerror response\
        \ that includes `error` and `error_description` values. If the \nerror is\
        \ due to the seller denying the request, the error value is `access_denied`\
        \ \nand the error_description is `user_denied`."
      operationId: Authorize
      security: []
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /oauth/protos/squareup/oauth/v1/api.proto
      x-proto-sha: 933b3a2bcf0d97135250f1654c43670d49e7ef30
      x-visibility: DOC_ONLY
  /oauth2/clients/{client_id}/access-token/renew:
    post:
      tags:
      - OAuth
      summary: RenewToken
      description: |-
        `RenewToken` is deprecated. For information about refreshing OAuth access tokens, see
        [Migrate from Renew to Refresh OAuth Tokens](https://developer.squareup.com/docs/oauth-api/migrate-to-refresh-tokens).


        Renews an OAuth access token before it expires.

        OAuth access tokens besides your application's personal access token expire after __30 days__.
        You can also renew expired tokens within __15 days__ of their expiration.
        You cannot renew an access token that has been expired for more than 15 days.
        Instead, the associated user must re-complete the OAuth flow from the beginning.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the Credentials
        page in the [developer dashboard](https://developer.squareup.com/apps).
      operationId: RenewToken
      deprecated: true
      security:
      - oauth2ClientSecret: []
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /oauth/protos/squareup/oauth/v1/api.proto
      x-proto-sha: 933b3a2bcf0d97135250f1654c43670d49e7ef30
      x-deprecation: {}
  /oauth2/revoke:
    post:
      tags:
      - OAuth
      summary: RevokeToken
      description: |-
        Revokes an access token generated with the OAuth flow.

        If an account has more than one OAuth access token for your application, this
        endpoint revokes all of them, regardless of which token you specify. When an
        OAuth access token is revoked, all of the active subscriptions associated
        with that OAuth token are canceled immediately.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the OAuth
        page for your application on the Developer Dashboard.
      operationId: RevokeToken
      security:
      - oauth2ClientSecret: []
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /oauth/protos/squareup/oauth/v1/api.proto
      x-proto-sha: 933b3a2bcf0d97135250f1654c43670d49e7ef30
  /oauth2/token:
    post:
      tags:
      - OAuth
      summary: ObtainToken
      description: "Returns an OAuth access token and a refresh token unless the \n\
        `short_lived` parameter is set to `true`, in which case the endpoint \nreturns\
        \ only an access token.\n\nThe `grant_type` parameter specifies the type of\
        \ OAuth request. If \n`grant_type` is `authorization_code`, you must include\
        \ the authorization \ncode you received when a seller granted you authorization.\
        \ If `grant_type` \nis `refresh_token`, you must provide a valid refresh token.\
        \ If you are using \nan old version of the Square APIs (prior to March 13,\
        \ 2019), `grant_type` \ncan be `migration_token` and you must provide a valid\
        \ migration token.\n\nYou can use the `scopes` parameter to limit the set\
        \ of permissions granted \nto the access token and refresh token. You can\
        \ use the `short_lived` parameter \nto create an access token that expires\
        \ in 24 hours.\n\n__Note:__ OAuth tokens should be encrypted and stored on\
        \ a secure server. \nApplication clients should never interact directly with\
        \ OAuth tokens."
      operationId: ObtainToken
      security: []
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /oauth/protos/squareup/oauth/v1/api.proto
      x-proto-sha: 933b3a2bcf0d97135250f1654c43670d49e7ef30
  /v1/batch:
    post:
      tags:
      - V1Batching
      summary: V1SubmitBatch
      description: |-
        Bundle multiple requests to Connect V1 API endpoints as a single
        request.


        The __V1SubmitBatch__ endpoint does not require an access token
        in the request header. Instead, provide an `access_token` parameter for
        each request included in the batch.

        __V1SubmitBatch__ responds with an array that contains response objects for
        each of the batched requests. There is no guarantee of the order in
        which batched requests are performed.


        __IMPORTANT__

        You cannot include more than 30 requests in a single batch and
        recursive requests to __V1SubmitBatch__ are not allowed. In
        other words, none of the requests included in a batch can itself be a
        request to the __V1SubmitBatch__ endpoint.
      operationId: V1SubmitBatch
      deprecated: true
      security: []
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1batch.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/general-guidance#v1batching
      x-visibility: DOC_ONLY
  /v1/{location_id}/payments:
    get:
      tags:
      - V1Transactions
      summary: ListPayments
      description: |-
        Provides summary information for all payments taken for a given
        Square account during a date range. Date ranges cannot exceed 1 year in
        length. See Date ranges for details of inclusive and exclusive dates.

        *Note**: Details for payments processed with Square Point of Sale while
        in offline mode may not be transmitted to Square for up to 72 hours.
        Offline payments have a `created_at` value that reflects the time the
        payment was originally processed, not the time it was subsequently
        transmitted to Square. Consequently, the ListPayments endpoint might
        list an offline payment chronologically between online payments that
        were seen in a previous request.
      operationId: ListPayments
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-payments.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
  /v1/{location_id}/payments/{payment_id}:
    get:
      tags:
      - V1Transactions
      summary: RetrievePayment
      description: Provides comprehensive information for a single payment.
      operationId: RetrievePayment
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-payments.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
  /v1/{location_id}/refunds:
    get:
      tags:
      - V1Transactions
      summary: ListRefunds
      description: Provides the details for all refunds initiated by a merchant or
        any of the merchant's mobile staff during a date range. Date ranges cannot
        exceed one year in length.
      operationId: ListRefunds
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-refunds.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
    post:
      tags:
      - V1Transactions
      summary: CreateRefund
      description: |-
        Issues a refund for a previously processed payment. You must issue
        a refund within 60 days of the associated payment.

        You cannot issue a partial refund for a split tender payment. You must
        instead issue a full or partial refund for a particular tender, by
        providing the applicable tender id to the V1CreateRefund endpoint.
        Issuing a full refund for a split tender payment refunds all tenders
        associated with the payment.

        Issuing a refund for a card payment is not reversible. For development
        purposes, you can create fake cash payments in Square Point of Sale and
        refund them.
      operationId: CreateRefund
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-refunds.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
  /v1/{location_id}/settlements:
    get:
      tags:
      - V1Transactions
      summary: ListSettlements
      description: |-
        Provides summary information for all deposits and withdrawals
        initiated by Square to a linked bank account during a date range. Date
        ranges cannot exceed one year in length.

        *Note**: the ListSettlements endpoint does not provide entry
        information.
      operationId: ListSettlements
      deprecated: true
      security:
      - oauth2:
        - SETTLEMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-settlements.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
  /v1/{location_id}/settlements/{settlement_id}:
    get:
      tags:
      - V1Transactions
      summary: RetrieveSettlement
      description: |-
        Provides comprehensive information for a single settlement.

        The returned `Settlement` objects include an `entries` field that lists
        the transactions that contribute to the settlement total. Most
        settlement entries correspond to a payment payout, but settlement
        entries are also generated for less common events, like refunds, manual
        adjustments, or chargeback holds.

        Square initiates its regular deposits as indicated in the
        [Deposit Options with Square](https://squareup.com/help/us/en/article/3807)
        help article. Details for a regular deposit are usually not available
        from Connect API endpoints before 10 p.m. PST the same day.

        Square does not know when an initiated settlement **completes**, only
        whether it has failed. A completed settlement is typically reflected in
        a bank account within 3 business days, but in exceptional cases it may
        take longer.
      operationId: RetrieveSettlement
      deprecated: true
      security:
      - oauth2:
        - SETTLEMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1transactions-settlements.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-deprecation:
        deprecationDate: 2021-05-13
  /v1/{location_id}/webhooks:
    get:
      tags:
      - V1Webhooks
      summary: ListWebhooks
      description: |-
        Lists which types of events trigger webhook notifications for a particular location.
        See the [V1 Webhooks API guide](https://developer.squareup.com/docs/webhooks-api/what-it-does-v1) for more information.
      operationId: ListWebhooks
      security:
      - oauth2:
        - TIMECARDS_READ
        - PAYMENTS_READ
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1webhooks.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-visibility: DOC_ONLY
    put:
      tags:
      - V1Webhooks
      summary: UpdateWebhooks
      description: |-
        Changes the webhook event subscriptions for a location.
        See the [V1 Webhooks API guide](https://developer.squareup.com/docs/webhooks-api/what-it-does-v1) for more information.
      operationId: UpdateWebhooks
      security:
      - oauth2:
        - TIMECARDS_READ
        - PAYMENTS_READ
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/XP/repos/square-public-apis/browse
      x-proto-location: /_public-v1/v1webhooks.proto
      x-proto-sha: 5b34397c182abc91c1beeefdfaf38cc403d3930e
      x-visibility: DOC_ONLY
  /v2/apple-pay/domains:
    post:
      tags:
      - ApplePay
      summary: RegisterDomain
      description: |-
        Activates a domain for use with Apple Pay on the Web and Square. A validation
        is performed on this domain by Apple to ensure that it is properly set up as
        an Apple Pay enabled domain.

        This endpoint provides an easy way for platform developers to bulk activate
        Apple Pay on the Web with Square for merchants using their platform.

        To learn more about Web Apple Pay, see
        [Add the Apple Pay on the Web Button](https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay).
      operationId: RegisterDomain
      security:
      - oauth2: []
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /payapi-wallets/protos/squareup/payapi_wallets/apple_pay_domain_service.proto
      x-proto-sha: 97806244325ab9fded53f6629e1303295c8d4db8
  /v2/bank-accounts:
    get:
      tags:
      - BankAccounts
      summary: ListBankAccounts
      description: Returns a list of [BankAccount](entity:BankAccount) objects linked
        to a Square account.
      operationId: ListBankAccounts
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/bank_account_service.proto
      x-proto-sha: 9131b2c7156382fe9f16839668e39bfecda7f5e9
      x-namespace: marketplaces
  /v2/bank-accounts/by-v1-id/{v1_bank_account_id}:
    get:
      tags:
      - BankAccounts
      summary: GetBankAccountByV1Id
      description: Returns details of a [BankAccount](entity:BankAccount) identified
        by V1 bank account ID.
      operationId: GetBankAccountByV1Id
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/bank_account_service.proto
      x-proto-sha: 9131b2c7156382fe9f16839668e39bfecda7f5e9
      x-namespace: marketplaces
  /v2/bank-accounts/{bank_account_id}:
    get:
      tags:
      - BankAccounts
      summary: GetBankAccount
      description: |-
        Returns details of a [BankAccount](entity:BankAccount)
        linked to a Square account.
      operationId: GetBankAccount
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/bank_account_service.proto
      x-proto-sha: 9131b2c7156382fe9f16839668e39bfecda7f5e9
      x-namespace: marketplaces
  /v2/bookings:
    post:
      tags:
      - Bookings
      summary: CreateBooking
      description: Creates a booking.
      operationId: CreateBooking
      security:
      - oauth2:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Create a booking
          bodyParams:
            booking:
              customer_id: EX2QSVGTZN4K1E5QE1CBFNVQ8M
              start_at: 2020-11-26T13:00:00Z
              location_id: LEQHH0YY8B42M
              appointment_segments:
              - duration_minutes: 60
                team_member_id: TMXUrsBWWcHTt79t
                service_variation_id: RU3PBTZTK7DXZDQFCJHOK2MC
                service_variation_version: 1599775456731
  /v2/bookings/availability/search:
    post:
      tags:
      - Bookings
      summary: SearchAvailability
      description: Searches for availabilities for booking.
      operationId: SearchAvailability
      security:
      - oauth2:
        - APPOINTMENTS_READ
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Search for availability
          bodyParams:
            query:
              filter:
                start_at_range:
                  start_at: 2020-11-26T13:00:00Z
                  end_at: 2020-11-27T13:00:00Z
                location_id: LEQHH0YY8B42M
                segment_filters:
                - service_variation_id: RU3PBTZTK7DXZDQFCJHOK2MC
                  team_member_id_filter:
                    any:
                    - TMXUrsBWWcHTt79t
                    - TMaJcbiRqPIGZuS9
  /v2/bookings/business-booking-profile:
    get:
      tags:
      - Bookings
      summary: RetrieveBusinessBookingProfile
      description: Retrieves a seller's booking profile.
      operationId: RetrieveBusinessBookingProfile
      security:
      - oauth2:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Retrieve the business's booking profile
  /v2/bookings/team-member-booking-profiles:
    get:
      tags:
      - Bookings
      summary: ListTeamMemberBookingProfiles
      description: Lists booking profiles for team members.
      operationId: ListTeamMemberBookingProfiles
      security:
      - oauth2:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: List team member booking profiles
  /v2/bookings/team-member-booking-profiles/{team_member_id}:
    get:
      tags:
      - Bookings
      summary: RetrieveTeamMemberBookingProfile
      description: Retrieves a team member's booking profile.
      operationId: RetrieveTeamMemberBookingProfile
      security:
      - oauth2:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Retrieve a booking
          pathParameters:
            team_member_id: TMaJcbiRqPIGZuS9
  /v2/bookings/{booking_id}:
    get:
      tags:
      - Bookings
      summary: RetrieveBooking
      description: Retrieves a booking.
      operationId: RetrieveBooking
      security:
      - oauth2:
        - APPOINTMENTS_READ
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Retrieve a booking
          pathParameters:
            booking_id: zkras0xv0xwswx
    put:
      tags:
      - Bookings
      summary: UpdateBooking
      description: Updates a booking.
      operationId: UpdateBooking
      security:
      - oauth2:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Update a booking
          pathParameters:
            booking_id: zkras0xv0xwswx
          bodyParams:
            booking:
              version: 1
              customer_note: I would like to sit near the window please
  /v2/bookings/{booking_id}/cancel:
    post:
      tags:
      - Bookings
      summary: CancelBooking
      description: Cancels an existing booking.
      operationId: CancelBooking
      security:
      - oauth2:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-proto-repo: appointments
      x-proto-location: /protos/squareup/appointments/api/public.proto
      x-proto-sha: cd7da1dee4277ae4e9a5fe401239a6ad2b2c61c2
      x-example-scenarios:
        scenarios:
        - name: Cancel a booking
          pathParameters:
            booking_id: zkras0xv0xwswx
          bodyParams:
            booking_version: 1
  /v2/cards:
    get:
      tags:
      - Cards
      summary: ListCards
      description: |-
        Retrieves a list of cards owned by the account making the request.
        A max of 25 cards will be returned.
      operationId: ListCards
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/cards_store_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
    post:
      tags:
      - Cards
      summary: CreateCard
      description: Adds a card on file to an existing merchant.
      operationId: CreateCard
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/cards_store_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
      x-endpoint-errors:
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CUSTOMER_NOT_FOUND
      - error-code: SOURCE_EXPIRED
      - error-code: SOURCE_USED
      - error-code: INVALID_CARD_DATA
  /v2/cards/{card_id}:
    get:
      tags:
      - Cards
      summary: RetrieveCard
      description: Retrieves details for a specific Card.
      operationId: RetrieveCard
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/cards_store_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
      x-endpoint-errors:
      - error-code: NOT_FOUND
  /v2/cards/{card_id}/disable:
    post:
      tags:
      - Cards
      summary: DisableCard
      description: |-
        Disables the card, preventing any further updates or charges.
        Disabling an already disabled card is allowed but has no effect.
      operationId: DisableCard
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/cards_store_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
      x-endpoint-errors:
      - error-code: NOT_FOUND
  /v2/cash-drawers/shifts:
    get:
      tags:
      - CashDrawers
      summary: ListCashDrawerShifts
      description: |-
        Provides the details for all of the cash drawer shifts for a location
        in a date range.
      operationId: ListCashDrawerShifts
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /cashdrawers/cashdrawers-proto/src/main/proto/squareup/cashdrawers/api/v2/connect/service.proto
      x-proto-sha: 06291dbd5e7115613debe29fc712a6c8b9bd195e
  /v2/cash-drawers/shifts/{shift_id}:
    get:
      tags:
      - CashDrawers
      summary: RetrieveCashDrawerShift
      description: |-
        Provides the summary details for a single cash drawer shift. See
        [ListCashDrawerShiftEvents](api-endpoint:CashDrawers-ListCashDrawerShiftEvents) for a list of cash drawer shift events.
      operationId: RetrieveCashDrawerShift
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /cashdrawers/cashdrawers-proto/src/main/proto/squareup/cashdrawers/api/v2/connect/service.proto
      x-proto-sha: 06291dbd5e7115613debe29fc712a6c8b9bd195e
  /v2/cash-drawers/shifts/{shift_id}/events:
    get:
      tags:
      - CashDrawers
      summary: ListCashDrawerShiftEvents
      description: Provides a paginated list of events for a single cash drawer shift.
      operationId: ListCashDrawerShiftEvents
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /cashdrawers/cashdrawers-proto/src/main/proto/squareup/cashdrawers/api/v2/connect/service.proto
      x-proto-sha: 06291dbd5e7115613debe29fc712a6c8b9bd195e
  /v2/catalog/batch-delete:
    post:
      tags:
      - Catalog
      summary: BatchDeleteCatalogObjects
      description: |-
        Deletes a set of [CatalogItem](entity:CatalogItem)s based on the
        provided list of target IDs and returns a set of successfully deleted IDs in
        the response. Deletion is a cascading event such that all children of the
        targeted object are also deleted. For example, deleting a CatalogItem will
        also delete all of its [CatalogItemVariation](entity:CatalogItemVariation)
        children.

        `BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted
        IDs can be deleted. The response will only include IDs that were
        actually deleted.
      operationId: BatchDeleteCatalogObjects
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Delete multiple catalog objects
          bodyParameters:
            object_ids:
            - W62UWFY35CWMYGVWK6TWJDNI
            - AA27W3M2GGTF3H6AVPNB77CK
  /v2/catalog/batch-retrieve:
    post:
      tags:
      - Catalog
      summary: BatchRetrieveCatalogObjects
      description: |-
        Returns a set of objects based on the provided ID.
        Each [CatalogItem](entity:CatalogItem) returned in the set includes all of its
        child information including: all of its
        [CatalogItemVariation](entity:CatalogItemVariation) objects, references to
        its [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of
        any [CatalogTax](entity:CatalogTax) objects that apply to it.
      operationId: BatchRetrieveCatalogObjects
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Retrieve multiple catalog objects
          request_body:
            object_ids:
            - W62UWFY35CWMYGVWK6TWJDNI
            - AA27W3M2GGTF3H6AVPNB77CK
            include_related_objects: true
  /v2/catalog/batch-upsert:
    post:
      tags:
      - Catalog
      summary: BatchUpsertCatalogObjects
      description: |-
        Creates or updates up to 10,000 target objects based on the provided
        list of objects. The target objects are grouped into batches and each batch is
        inserted/updated in an all-or-nothing manner. If an object within a batch is
        malformed in some way, or violates a database constraint, the entire batch
        containing that item will be disregarded. However, other batches in the same
        request may still succeed. Each batch may contain up to 1,000 objects, and
        batches will be processed in order as long as the total object count for the
        request (items, variations, modifier lists, discounts, and taxes) is no more
        than 10,000.
      operationId: BatchUpsertCatalogObjects
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Add a batch of objects to the catalog
          bodyParams:
            idempotency_key: 789ff020-f723-43a9-b4b5-43b5dc1fa3dc
            batches:
            - objects:
              - type: ITEM
                id: '#Tea'
                present_at_all_locations: true
                item_data:
                  name: Tea
                  description: Hot Leaf Juice
                  category_id: '#Beverages'
                  tax_ids:
                  - '#SalesTax'
                  variations:
                  - type: ITEM_VARIATION
                    id: '#Tea_Mug'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Tea'
                      name: Mug
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 150
                        currency: USD
              - type: ITEM
                id: '#Coffee'
                present_at_all_locations: true
                item_data:
                  name: Coffee
                  description: Hot Bean Juice
                  category_id: '#Beverages'
                  tax_ids:
                  - '#SalesTax'
                  variations:
                  - type: ITEM_VARIATION
                    id: '#Coffee_Regular'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Coffee'
                      name: Regular
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 250
                        currency: USD
                  - type: ITEM_VARIATION
                    id: '#Coffee_Large'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Coffee'
                      name: Large
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 350
                        currency: USD
              - type: CATEGORY
                id: '#Beverages'
                present_at_all_locations: true
                category_data:
                  name: Beverages
              - type: TAX
                id: '#SalesTax'
                present_at_all_locations: true
                tax_data:
                  name: Sales Tax
                  calculation_phase: TAX_SUBTOTAL_PHASE
                  inclusion_type: ADDITIVE
                  percentage: "5.0"
                  applies_to_custom_amounts: true
                  enabled: true
  /v2/catalog/images:
    post:
      tags:
      - Catalog
      summary: CreateCatalogImage
      description: |-
        Uploads an image file to be represented by a [CatalogImage](entity:CatalogImage) object linked to an existing
        [CatalogObject](entity:CatalogObject) instance. A call to this endpoint can upload an image, link an image to
        a catalog object, or do both.

        This `CreateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in
        JPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.
      operationId: CreateCatalogImage
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Upload an image for a catalog object
          bodyParams:
            idempotency_key: 528dea59-7bfb-43c1-bd48-4a6bba7dd61f86
            object_id: ND6EA5AAJEO5WL3JNNIAQA32
            image:
              id: '#TEMP_ID'
              type: IMAGE
              image_data:
                caption: A picture of a cup of coffee
  /v2/catalog/info:
    get:
      tags:
      - Catalog
      summary: CatalogInfo
      description: |-
        Retrieves information about the Square Catalog API, such as batch size
        limits that can be used by the `BatchUpsertCatalogObjects` endpoint.
      operationId: CatalogInfo
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Get catalog API information
  /v2/catalog/list:
    get:
      tags:
      - Catalog
      summary: ListCatalog
      description: |-
        Returns a list of [CatalogObject](entity:CatalogObject)s that includes
        all objects of a set of desired types (for example, all [CatalogItem](entity:CatalogItem)
        and [CatalogTax](entity:CatalogTax) objects) in the catalog. The `types` parameter
        is specified as a comma-separated list of valid [CatalogObject](entity:CatalogObject) types:
        `ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`.

        __Important:__ ListCatalog does not return deleted catalog items. To retrieve
        deleted catalog items, use [SearchCatalogObjects](api-endpoint:Catalog-SearchCatalogObjects)
        and set the `include_deleted_objects` attribute value to `true`.
      operationId: ListCatalog
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: List catalog objects of a certain type
          requestParams:
            types: category,tax
  /v2/catalog/object:
    post:
      tags:
      - Catalog
      summary: UpsertCatalogObject
      description: Creates or updates the target [CatalogObject](entity:CatalogObject).
      operationId: UpsertCatalogObject
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Add an item
          bodyParameters:
            idempotency_key: af3d1afc-7212-4300-b463-0bfc5314a5ae
            object:
              id: '#Cocoa'
              type: ITEM
              item_data:
                abbreviation: Ch
                description: Hot Chocolate
                name: Cocoa
                variations:
                - id: '#Small'
                  type: ITEM_VARIATION
                  item_variation_data:
                    item_id: '#Cocoa'
                    name: Small
                    pricing_type: VARIABLE_PRICING
                - id: '#Large'
                  type: ITEM_VARIATION
                  item_variation_data:
                    item_id: '#Cocoa'
                    name: Large
                    pricing_type: FIXED_PRICING
                    price_money:
                      amount: 400
                      currency: USD
        - name: Add a category
          bodyParameters:
            idempotency_key: 4ef9a31f-b405-4df8-9c67-e6f964778fe8
            object:
              id: '#Beverages'
              type: CATEGORY
              category_data:
                name: Beverages
  /v2/catalog/object/{object_id}:
    get:
      tags:
      - Catalog
      summary: RetrieveCatalogObject
      description: |-
        Returns a single [CatalogItem](entity:CatalogItem) as a
        [CatalogObject](entity:CatalogObject) based on the provided ID. The returned
        object includes all of the relevant [CatalogItem](entity:CatalogItem)
        information including: [CatalogItemVariation](entity:CatalogItemVariation)
        children, references to its
        [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of
        any [CatalogTax](entity:CatalogTax) objects that apply to it.
      operationId: RetrieveCatalogObject
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Retrieve catalog object
          pathParameters:
            object_id: W62UWFY35CWMYGVWK6TWJDNI
        - name: Retrieve catalog object and include related objects
          pathParameters:
            object_id: W62UWFY35CWMYGVWK6TWJDNI
          queryParameters:
            include_related_objects: true
    delete:
      tags:
      - Catalog
      summary: DeleteCatalogObject
      description: |-
        Deletes a single [CatalogObject](entity:CatalogObject) based on the
        provided ID and returns the set of successfully deleted IDs in the response.
        Deletion is a cascading event such that all children of the targeted object
        are also deleted. For example, deleting a [CatalogItem](entity:CatalogItem)
        will also delete all of its
        [CatalogItemVariation](entity:CatalogItemVariation) children.
      operationId: DeleteCatalogObject
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Delete a catalog object
          pathParameters:
            object_id: 7SB3ZQYJ5GDMVFL7JK46JCHT
  /v2/catalog/search:
    post:
      tags:
      - Catalog
      summary: SearchCatalogObjects
      description: |-
        Searches for [CatalogObject](entity:CatalogObject) of any type by matching supported search attribute values,
        excluding custom attribute values on items or item variations, against one or more of the specified query filters.

        This (`SearchCatalogObjects`) endpoint differs from the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems)
        endpoint in the following aspects:

        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.
        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.
        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.
        - The both endpoints have different call conventions, including the query filter formats.
      operationId: SearchCatalogObjects
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Search for catalog objects by name
          bodyParameters:
            object_types:
            - ITEM
            query:
              prefix_query:
                attribute_name: name
                attribute_prefix: tea
            limit: 100
  /v2/catalog/search-catalog-items:
    post:
      tags:
      - Catalog
      summary: SearchCatalogItems
      description: |-
        Searches for catalog items or item variations by matching supported search attribute values, including
        custom attribute values, against one or more of the specified query filters.

        This (`SearchCatalogItems`) endpoint differs from the [SearchCatalogObjects](api-endpoint:Catalog-SearchCatalogObjects)
        endpoint in the following aspects:

        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.
        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.
        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.
        - The both endpoints use different call conventions, including the query filter formats.
      operationId: SearchCatalogItems
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Search for a catalog item using filters
          bodyParams:
            sort_order: ASC
            product_types:
            - REGULAR
            category_ids:
            - WINE_CATEGORY_ID
            enabled_location_ids:
            - ATL_LOCATION_ID
            text_filter: red
            custom_attribute_filters:
            - custom_attribute_definition_id: VEGAN_DEFINITION_ID
              bool_filter: true
            - custom_attribute_definition_id: BRAND_DEFINITION_ID
              string_filter: Dark Horse
            - key: VINTAGE
              number_filter:
                min: 2017
                max: 2018
            - custom_attribute_definition_id: VARIETAL_DEFINITION_ID
              selection_ids_filter: MERLOT_SELECTION_ID
            stock_levels:
            - OUT
            - LOW
            limit: 100
  /v2/catalog/update-item-modifier-lists:
    post:
      tags:
      - Catalog
      summary: UpdateItemModifierLists
      description: |-
        Updates the [CatalogModifierList](entity:CatalogModifierList) objects
        that apply to the targeted [CatalogItem](entity:CatalogItem) without having
        to perform an upsert on the entire item.
      operationId: UpdateItemModifierLists
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Update modifier lists for a list of items
          bodyParameters:
            item_ids:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            modifier_lists_to_enable:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            modifier_lists_to_disable:
            - 7WRC16CJZDVLSNDQ35PP6YAD
  /v2/catalog/update-item-taxes:
    post:
      tags:
      - Catalog
      summary: UpdateItemTaxes
      description: |-
        Updates the [CatalogTax](entity:CatalogTax) objects that apply to the
        targeted [CatalogItem](entity:CatalogItem) without having to perform an
        upsert on the entire item.
      operationId: UpdateItemTaxes
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/catalog/service.proto
      x-proto-sha: 7564f2195a5bc06364dc54c0b78bf8919a1b9f8d
      x-example-scenarios:
        scenarios:
        - name: Update taxes for a list of items
          bodyParameters:
            item_ids:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            taxes_to_enable:
            - 4WRCNHCJZDVLSNDQ35PP6YAD
            taxes_to_disable:
            - AQCEGCEBBQONINDOHRGZISEX
  /v2/customers:
    get:
      tags:
      - Customers
      summary: ListCustomers
      description: |-
        Lists customer profiles associated with a Square account.

        Under normal operating conditions, newly created or updated customer profiles become available
        for the listing operation in well under 30 seconds. Occasionally, propagation of the new or updated
        profiles can take closer to one minute or longer, especially during network incidents and outages.
      operationId: ListCustomers
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    post:
      tags:
      - Customers
      summary: CreateCustomer
      description: |-
        Creates a new customer for a business.

        You must provide at least one of the following values in your request to this
        endpoint:

        - `given_name`
        - `family_name`
        - `company_name`
        - `email_address`
        - `phone_number`
      operationId: CreateCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/groups:
    get:
      tags:
      - CustomerGroups
      summary: ListCustomerGroups
      description: Retrieves the list of customer groups of a business.
      operationId: ListCustomerGroups
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    post:
      tags:
      - CustomerGroups
      summary: CreateCustomerGroup
      description: |-
        Creates a new customer group for a business.

        The request must include the `name` value of the group.
      operationId: CreateCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/groups/{group_id}:
    get:
      tags:
      - CustomerGroups
      summary: RetrieveCustomerGroup
      description: Retrieves a specific customer group as identified by the `group_id`
        value.
      operationId: RetrieveCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    put:
      tags:
      - CustomerGroups
      summary: UpdateCustomerGroup
      description: Updates a customer group as identified by the `group_id` value.
      operationId: UpdateCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    delete:
      tags:
      - CustomerGroups
      summary: DeleteCustomerGroup
      description: Deletes a customer group as identified by the `group_id` value.
      operationId: DeleteCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/search:
    post:
      tags:
      - Customers
      summary: SearchCustomers
      description: |-
        Searches the customer profiles associated with a Square account using a supported query filter.

        Calling `SearchCustomers` without any explicit query filter returns all
        customer profiles ordered alphabetically based on `given_name` and
        `family_name`.

        Under normal operating conditions, newly created or updated customer profiles become available
        for the search operation in well under 30 seconds. Occasionally, propagation of the new or updated
        profiles can take closer to one minute or longer, especially during network incidents and outages.
      operationId: SearchCustomers
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/segments:
    get:
      tags:
      - CustomerSegments
      summary: ListCustomerSegments
      description: Retrieves the list of customer segments of a business.
      operationId: ListCustomerSegments
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/segments/{segment_id}:
    get:
      tags:
      - CustomerSegments
      summary: RetrieveCustomerSegment
      description: Retrieves a specific customer segment as identified by the `segment_id`
        value.
      operationId: RetrieveCustomerSegment
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/{customer_id}:
    get:
      tags:
      - Customers
      summary: RetrieveCustomer
      description: Returns details for a single customer.
      operationId: RetrieveCustomer
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    put:
      tags:
      - Customers
      summary: UpdateCustomer
      description: |-
        Updates a customer profile. To change an attribute, specify the new value. To remove an attribute, specify the value as an empty string or empty object.

        As a best practice, you should include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/working-with-apis/optimistic-concurrency) control. The value must be set to the current version of the customer profile.

        To update a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.

        You cannot use this endpoint to change cards on file. To make changes, use the [Cards API](api:Cards) or [Gift Cards API](api:GiftCards).
      operationId: UpdateCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    delete:
      tags:
      - Customers
      summary: DeleteCustomer
      description: "Deletes a customer profile from a business. This operation also\
        \ unlinks any associated cards on file. \n\nAs a best practice, you should\
        \ include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/working-with-apis/optimistic-concurrency)\
        \ control. The value must be set to the current version of the customer profile.\
        \ \n\nTo delete a customer profile that was created by merging existing profiles,\
        \ you must use the ID of the newly created profile."
      operationId: DeleteCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/customers/{customer_id}/cards:
    post:
      tags:
      - Customers
      summary: CreateCustomerCard
      description: |-
        Adds a card on file to an existing customer.

        As with charges, calls to `CreateCustomerCard` are idempotent. Multiple
        calls with the same card nonce return the same card record that was created
        with the provided nonce during the _first_ call.
      operationId: CreateCustomerCard
      deprecated: true
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/customer_cards_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
      x-deprecation:
        deprecationDate: 2021-06-16
        retirementDate: 2022-06-16
        replacedBy: CreateCard
        guideUrl: https://developer.squareup.com/docs/customers-api/use-the-api/integrate-with-other-services#migrate-customer-cards
      x-endpoint-errors:
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: INVALID_CARD
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EXPIRATION
      - error-code: UNSUPPORTED_ENTRY_METHOD
      - error-code: VERIFY_AVS_FAILURE
      - error-code: VERIFY_CVV_FAILURE
  /v2/customers/{customer_id}/cards/{card_id}:
    delete:
      tags:
      - Customers
      summary: DeleteCustomerCard
      description: Removes a card on file from a customer.
      operationId: DeleteCustomerCard
      deprecated: true
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /cards-api/protos/squareup/cards/api/customer_cards_service.proto
      x-proto-sha: c0f44fae5809caaf71fe83a1271cf188cc4c0856
      x-deprecation:
        deprecationDate: 2021-06-16
        retirementDate: 2022-06-16
        replacedBy: DisableCard
        guideUrl: https://developer.squareup.com/docs/customers-api/use-the-api/integrate-with-other-services#migrate-customer-cards
  /v2/customers/{customer_id}/groups/{group_id}:
    put:
      tags:
      - Customers
      summary: AddGroupToCustomer
      description: |-
        Adds a group membership to a customer.

        The customer is identified by the `customer_id` value
        and the customer group is identified by the `group_id` value.
      operationId: AddGroupToCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
    delete:
      tags:
      - Customers
      summary: RemoveGroupFromCustomer
      description: |-
        Removes a group membership from a customer.

        The customer is identified by the `customer_id` value
        and the customer group is identified by the `group_id` value.
      operationId: RemoveGroupFromCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /connectcustomers/connectcustomers-proto/src/main/proto/squareup/connectcustomers/service.proto
      x-proto-sha: 132a16ddcd88459d8974cbf25697f168239f16e9
  /v2/devices/codes:
    get:
      tags:
      - Devices
      summary: ListDeviceCodes
      description: Lists all DeviceCodes associated with the merchant.
      operationId: ListDeviceCodes
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /device-settings/device-settings-proto/src/main/proto/squareup/devicesettings/external/device_code_service.proto
      x-proto-sha: c26abe92e5379e8660778fe30b38f9165df7fabc
      x-endpoint-errors:
      - error-code: INVALID_CURSOR
      - error-code: BAD_REQUEST
    post:
      tags:
      - Devices
      summary: CreateDeviceCode
      description: |-
        Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected
        terminal mode.
      operationId: CreateDeviceCode
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /device-settings/device-settings-proto/src/main/proto/squareup/devicesettings/external/device_code_service.proto
      x-proto-sha: c26abe92e5379e8660778fe30b38f9165df7fabc
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: IDEMPOTENCY_KEY_REUSED
      - error-code: INVALID_VALUE
      - error-code: UNAUTHORIZED
  /v2/devices/codes/{id}:
    get:
      tags:
      - Devices
      summary: GetDeviceCode
      description: Retrieves DeviceCode with the associated ID.
      operationId: GetDeviceCode
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /device-settings/device-settings-proto/src/main/proto/squareup/devicesettings/external/device_code_service.proto
      x-proto-sha: c26abe92e5379e8660778fe30b38f9165df7fabc
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
      - error-code: UNAUTHORIZED
  /v2/disputes:
    get:
      tags:
      - Disputes
      summary: ListDisputes
      description: Returns a list of disputes associated with a particular account.
      operationId: ListDisputes
      security:
      - oauth2:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}:
    get:
      tags:
      - Disputes
      summary: RetrieveDispute
      description: Returns details about a specific dispute.
      operationId: RetrieveDispute
      security:
      - oauth2:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/accept:
    post:
      tags:
      - Disputes
      summary: AcceptDispute
      description: |-
        Accepts the loss on a dispute. Square returns the disputed amount to the cardholder and
        updates the dispute state to ACCEPTED.

        Square debits the disputed amount from the seller’s Square account. If the Square account
        does not have sufficient funds, Square debits the associated bank account.
      operationId: AcceptDispute
      security:
      - oauth2:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/evidence:
    get:
      tags:
      - Disputes
      summary: ListDisputeEvidence
      description: Returns a list of evidence associated with a dispute.
      operationId: ListDisputeEvidence
      security:
      - oauth2:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/evidence-files:
    post:
      tags:
      - Disputes
      summary: CreateDisputeEvidenceFile
      description: |-
        Uploads a file to use as evidence in a dispute challenge. The endpoint accepts HTTP
        multipart/form-data file uploads in HEIC, HEIF, JPEG, PDF, PNG, and TIFF formats.
      operationId: CreateDisputeEvidenceFile
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/evidence-text:
    post:
      tags:
      - Disputes
      summary: CreateDisputeEvidenceText
      description: Uploads text to use as evidence for a dispute challenge.
      operationId: CreateDisputeEvidenceText
      security:
      - oauth2:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/evidence/{evidence_id}:
    get:
      tags:
      - Disputes
      summary: RetrieveDisputeEvidence
      description: |-
        Returns the evidence metadata specified by the evidence ID in the request URL path

        You must maintain a copy of the evidence you upload if you want to reference it later. You cannot
        download the evidence after you upload it.
      operationId: RetrieveDisputeEvidence
      security:
      - oauth2:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
    delete:
      tags:
      - Disputes
      summary: DeleteDisputeEvidence
      description: |-
        Removes specified evidence from a dispute.

        Square does not send the bank any evidence that is removed. Also, you cannot remove evidence after
        submitting it to the bank using [SubmitEvidence](api-endpoint:Disputes-SubmitEvidence).
      operationId: DeleteDisputeEvidence
      security:
      - oauth2:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/disputes/{dispute_id}/submit-evidence:
    post:
      tags:
      - Disputes
      summary: SubmitEvidence
      description: |-
        Submits evidence to the cardholder's bank.

        Before submitting evidence, Square compiles all available evidence. This includes evidence uploaded
        using the [CreateDisputeEvidenceFile](api-endpoint:Disputes-CreateDisputeEvidenceFile) and
        [CreateDisputeEvidenceText](api-endpoint:Disputes-CreateDisputeEvidenceText) endpoints and
        evidence automatically provided by Square, when available.
      operationId: SubmitEvidence
      security:
      - oauth2:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /payments/marketplaces-api/src/main/proto/squareup/payments/external/disputes_service.proto
      x-proto-sha: 4528de82f345513293484cb71cfd0cf3cd7f5d76
  /v2/employees:
    get:
      tags:
      - Employees
      summary: ListEmployees
      operationId: ListEmployees
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/employee.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: SearchTeamMembers
        guideUrl: https://developer.squareup.com/docs/team/migrate-from-v2-employees
  /v2/employees/{id}:
    get:
      tags:
      - Employees
      summary: RetrieveEmployee
      operationId: RetrieveEmployee
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/employee.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: RetrieveTeamMember
        guideUrl: https://developer.squareup.com/docs/team/migrate-from-v2-employees
  /v2/gift-cards:
    get:
      tags:
      - GiftCards
      summary: ListGiftCards
      description: "Lists all gift cards. You can specify optional filters to retrieve\
        \ \na subset of the gift cards."
      operationId: ListGiftCards
      security:
      - oauth2:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
    post:
      tags:
      - GiftCards
      summary: CreateGiftCard
      description: "Creates a digital gift card or registers a physical (plastic)\
        \ gift card. You must activate the gift card before \nit can be used for payment.\
        \ For more information, see \n[Selling gift cards](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#selling-square-gift-cards)."
      operationId: CreateGiftCard
      security:
      - oauth2:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/gift-cards/activities:
    get:
      tags:
      - GiftCardActivities
      summary: ListGiftCardActivities
      description: |-
        Lists gift card activities. By default, you get gift card activities for all
        gift cards in the seller's account. You can optionally specify query parameters to
        filter the list. For example, you can get a list of gift card activities for a gift card,
        for all gift cards in a specific region, or for activities within a time window.
      operationId: ListGiftCardActivities
      security:
      - oauth2:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
    post:
      tags:
      - GiftCardActivities
      summary: CreateGiftCardActivity
      description: "Creates a gift card activity. For more information, see \n[GiftCardActivity](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#giftcardactivity)\
        \ and \n[Using activated gift cards](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#using-activated-gift-cards)."
      operationId: CreateGiftCardActivity
      security:
      - oauth2:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
      x-endpoint-errors:
      - error-code: PAYMENT_LIMIT_EXCEEDED
      - error-code: INSUFFICIENT_FUNDS
  /v2/gift-cards/from-gan:
    post:
      tags:
      - GiftCards
      summary: RetrieveGiftCardFromGAN
      description: Retrieves a gift card using the gift card account number (GAN).
      operationId: RetrieveGiftCardFromGAN
      security:
      - oauth2:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/gift-cards/from-nonce:
    post:
      tags:
      - GiftCards
      summary: RetrieveGiftCardFromNonce
      description: Retrieves a gift card using a nonce (a secure token) that represents
        the gift card.
      operationId: RetrieveGiftCardFromNonce
      security:
      - oauth2:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/gift-cards/{gift_card_id}/link-customer:
    post:
      tags:
      - GiftCards
      summary: LinkCustomerToGiftCard
      description: Links a customer to a gift card
      operationId: LinkCustomerToGiftCard
      security:
      - oauth2:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/gift-cards/{gift_card_id}/unlink-customer:
    post:
      tags:
      - GiftCards
      summary: UnlinkCustomerFromGiftCard
      description: Unlinks a customer from a gift card
      operationId: UnlinkCustomerFromGiftCard
      security:
      - oauth2:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/gift-cards/{id}:
    get:
      tags:
      - GiftCards
      summary: RetrieveGiftCard
      description: Retrieves a gift card using its ID.
      operationId: RetrieveGiftCard
      security:
      - oauth2:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /giftcard/api/src/main/proto/squareup/giftcard/connect-api/proto/squareup/giftcard/giftcard_api/service.proto
      x-proto-sha: 953ab4382ca9779f22195534dfb3f3ce888929c9
  /v2/inventory/adjustment/{adjustment_id}:
    get:
      tags:
      - Inventory
      summary: DeprecatedRetrieveInventoryAdjustment
      description: "Deprecated version of [RetrieveInventoryAdjustment](api-endpoint:Inventory-RetrieveInventoryAdjustment)\
        \ after the endpoint URL \nis updated to conform to the standard convention."
      operationId: DeprecatedRetrieveInventoryAdjustment
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/inventory/adjustments/{adjustment_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryAdjustment
      description: |-
        Returns the [InventoryAdjustment](entity:InventoryAdjustment) object
        with the provided `adjustment_id`.
      operationId: RetrieveInventoryAdjustment
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/batch-change:
    post:
      tags:
      - Inventory
      summary: DeprecatedBatchChangeInventory
      description: "Deprecated version of [BatchChangeInventory](api-endpoint:Inventory-BatchChangeInventory)\
        \ after the endpoint URL \nis updated to conform to the standard convention."
      operationId: DeprecatedBatchChangeInventory
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/inventory/batch-retrieve-changes:
    post:
      tags:
      - Inventory
      summary: DeprecatedBatchRetrieveInventoryChanges
      description: "Deprecated version of [BatchRetrieveInventoryChanges](api-endpoint:Inventory-BatchRetrieveInventoryChanges)\
        \ after the endpoint URL \nis updated to conform to the standard convention."
      operationId: DeprecatedBatchRetrieveInventoryChanges
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/inventory/batch-retrieve-counts:
    post:
      tags:
      - Inventory
      summary: DeprecatedBatchRetrieveInventoryCounts
      description: "Deprecated version of [BatchRetrieveInventoryCounts](api-endpoint:Inventory-BatchRetrieveInventoryCounts)\
        \ after the endpoint URL \nis updated to conform to the standard convention."
      operationId: DeprecatedBatchRetrieveInventoryCounts
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/inventory/changes/batch-create:
    post:
      tags:
      - Inventory
      summary: BatchChangeInventory
      description: |-
        Applies adjustments and counts to the provided item quantities.

        On success: returns the current calculated counts for all objects
        referenced in the request.
        On failure: returns a list of related errors.
      operationId: BatchChangeInventory
      security:
      - oauth2:
        - INVENTORY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/changes/batch-retrieve:
    post:
      tags:
      - Inventory
      summary: BatchRetrieveInventoryChanges
      description: |-
        Returns historical physical counts and adjustments based on the
        provided filter criteria.

        Results are paginated and sorted in ascending order according their
        `occurred_at` timestamp (oldest first).

        BatchRetrieveInventoryChanges is a catch-all query endpoint for queries
        that cannot be handled by other, simpler endpoints.
      operationId: BatchRetrieveInventoryChanges
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/counts/batch-retrieve:
    post:
      tags:
      - Inventory
      summary: BatchRetrieveInventoryCounts
      description: |-
        Returns current counts for the provided
        [CatalogObject](entity:CatalogObject)s at the requested
        [Location](entity:Location)s.

        Results are paginated and sorted in descending order according to their
        `calculated_at` timestamp (newest first).

        When `updated_after` is specified, only counts that have changed since that
        time (based on the server timestamp for the most recent change) are
        returned. This allows clients to perform a "sync" operation, for example
        in response to receiving a Webhook notification.
      operationId: BatchRetrieveInventoryCounts
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/physical-count/{physical_count_id}:
    get:
      tags:
      - Inventory
      summary: DeprecatedRetrieveInventoryPhysicalCount
      description: "Deprecated version of [RetrieveInventoryPhysicalCount](api-endpoint:Inventory-RetrieveInventoryPhysicalCount)\
        \ after the endpoint URL \nis updated to conform to the standard convention."
      operationId: DeprecatedRetrieveInventoryPhysicalCount
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/inventory/physical-counts/{physical_count_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryPhysicalCount
      description: |-
        Returns the [InventoryPhysicalCount](entity:InventoryPhysicalCount)
        object with the provided `physical_count_id`.
      operationId: RetrieveInventoryPhysicalCount
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/transfers/{transfer_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryTransfer
      description: |-
        Returns the [InventoryTransfer](entity:InventoryTransfer) object
        with the provided `transfer_id`.
      operationId: RetrieveInventoryTransfer
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/{catalog_object_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryCount
      description: |-
        Retrieves the current calculated stock count for a given
        [CatalogObject](entity:CatalogObject) at a given set of
        [Location](entity:Location)s. Responses are paginated and unsorted.
        For more sophisticated queries, use a batch endpoint.
      operationId: RetrieveInventoryCount
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
  /v2/inventory/{catalog_object_id}/changes:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryChanges
      description: "Returns a set of physical counts and inventory adjustments for\
        \ the\nprovided [CatalogObject](entity:CatalogObject) at the requested\n[Location](entity:Location)s.\
        \ \n\nYou can achieve the same result by calling [BatchRetrieveInventoryChanges](api-endpoint:Inventory-BatchRetrieveInventoryChanges)\
        \ \nand having the `catalog_object_ids` list contain a single element of the\
        \ `CatalogObject` ID.\n\nResults are paginated and sorted in descending order\
        \ according to their\n`occurred_at` timestamp (newest first).\n\nThere are\
        \ no limits on how far back the caller can page. This endpoint can be \nused\
        \ to display recent changes for a specific item. For more\nsophisticated queries,\
        \ use a batch endpoint."
      operationId: RetrieveInventoryChanges
      deprecated: true
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/inventory/service/inventory_service.proto
      x-proto-sha: f56e272803cd7897f99b1920315310d2c7140a68
      x-deprecation: {}
  /v2/invoices:
    get:
      tags:
      - Invoices
      summary: ListInvoices
      description: "Returns a list of invoices for a given location. The response\
        \ \nis paginated. If truncated, the response includes a `cursor` that you\
        \    \nuse in a subsequent request to retrieve the next set of invoices."
      operationId: ListInvoices
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
    post:
      tags:
      - Invoices
      summary: CreateInvoice
      description: "Creates a draft [invoice](entity:Invoice) \nfor an order created\
        \ using the Orders API.\n\nA draft invoice remains in your account and no\
        \ action is taken. \nYou must publish the invoice before Square can process\
        \ it (send it to the customer's email address or charge the customer’s card\
        \ on file)."
      operationId: CreateInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
      x-endpoint-errors:
      - error-code: INVALID_CARD
      - error-code: MERCHANT_SUBSCRIPTION_NOT_FOUND
      x-example-scenarios:
        scenarios:
        - name: Payment in full
          bodyParameters:
            idempotency_key: ce3748f9-5fc1-4762-aa12-aae5e843f1f4
            invoice:
              location_id: ES0RJRZYEC39A
              order_id: CAISENgvlJ6jLWAzERDzjyHVybY
              scheduled_at: 2030-01-13T10:00:00Z
              primary_recipient:
                customer_id: JDKYHBWT1D4F8MFH63DBMEN8Y4
              delivery_method: EMAIL
              payment_requests:
              - request_type: BALANCE
                due_date: 2030-01-24
                tipping_enabled: true
                automatic_payment_source: NONE
                reminders:
                - message: Your invoice is due tomorrow
                  relative_scheduled_days: -1
              invoice_number: inv-100
              title: Event Planning Services
              description: We appreciate your business!
              accepted_payment_methods:
                card: true
                square_gift_card: false
                bank_account: false
              custom_fields:
              - label: Event Reference Number
                value: 'Ref. #1234'
                placement: ABOVE_LINE_ITEMS
              - label: Terms of Service
                value: The terms of service are...
                placement: BELOW_LINE_ITEMS
              sale_or_service_date: 2030-01-24
        - name: Deposit with balance due later
          bodyParameters:
            idempotency_key: 8c944132-7fb5-48a4-9811-23faf364dbbd
            invoice:
              location_id: ES0RJRZYEC39A
              order_id: MJgfQ4nbvqoUzoZH0xTvJC3QuaB
              primary_recipient:
                customer_id: JDKYHBWT1D4F8MFH63DBMEN8Y4
              delivery_method: EMAIL
              payment_requests:
              - request_type: DEPOSIT
                due_date: 2022-02-01
                percentage_requested: "50"
              - request_type: BALANCE
                due_date: 2022-03-01
                tipping_enabled: true
                automatic_payment_source: NONE
                reminders:
                - message: Your invoice is due tomorrow
                  relative_scheduled_days: -1
              invoice_number: inv-101
              title: Event Planning Services
              description: We appreciate your business!
              accepted_payment_methods:
                card: true
                square_gift_card: false
                bank_account: false
              custom_fields:
              - label: Event Reference Number
                value: 'Ref. #1234'
                placement: ABOVE_LINE_ITEMS
              - label: Terms of Service
                value: The terms of service are...
                placement: BELOW_LINE_ITEMS
              sale_or_service_date: 2030-01-24
        - name: Deposit with installments
          bodyParameters:
            idempotency_key: 22506e12-dd9c-400e-9292-8bd8f1b2099b
            invoice:
              location_id: ES0RJRZYEC39A
              order_id: E90bKTQOBmeO7W4TLvG5pMIVvaB
              primary_recipient:
                customer_id: JDKYHBWT1D4F8MFH63DBMEN8Y4
              delivery_method: EMAIL
              payment_requests:
              - request_type: DEPOSIT
                due_date: 2022-02-01
                percentage_requested: "20"
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                percentage_requested: "33"
                due_date: 2022-03-01
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                percentage_requested: "33"
                due_date: 2022-04-01
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                percentage_requested: "34"
                due_date: 2022-05-01
                automatic_payment_source: NONE
              invoice_number: inv-102
              title: Event Planning Services
              description: We appreciate your business!
              accepted_payment_methods:
                card: true
                square_gift_card: false
                bank_account: false
              custom_fields:
              - label: Event Reference Number
                value: 'Ref. #1234'
                placement: ABOVE_LINE_ITEMS
              - label: Terms of Service
                value: The terms of service are...
                placement: BELOW_LINE_ITEMS
              sale_or_service_date: 2030-01-24
        - name: Installments only (fixed amount)
          bodyParameters:
            idempotency_key: a0dc6108-b9ae-4e3c-aadf-55a88bebdd4f
            invoice:
              location_id: ES0RJRZYEC39A
              order_id: WaU0nObtSiP3r08mpcwPNHaivaB
              primary_recipient:
                customer_id: JDKYHBWT1D4F8MFH63DBMEN8Y4
              delivery_method: EMAIL
              payment_requests:
              - request_type: INSTALLMENT
                due_date: 2022-02-01
                fixed_amount_requested_money:
                  amount: 2500
                  currency: USD
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                due_date: 2022-03-01
                fixed_amount_requested_money:
                  amount: 2500
                  currency: USD
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                due_date: 2022-04-01
                fixed_amount_requested_money:
                  amount: 2500
                  currency: USD
                automatic_payment_source: NONE
              - request_type: INSTALLMENT
                due_date: 2022-05-01
                fixed_amount_requested_money:
                  amount: 2500
                  currency: USD
                automatic_payment_source: NONE
              invoice_number: inv-103
              title: Event Planning Services
              description: We appreciate your business!
              accepted_payment_methods:
                card: true
                square_gift_card: false
                bank_account: false
              custom_fields:
              - label: Event Reference Number
                value: 'Ref. #1234'
                placement: ABOVE_LINE_ITEMS
              - label: Terms of Service
                value: The terms of service are...
                placement: BELOW_LINE_ITEMS
              sale_or_service_date: 2030-01-24
        - name: Automatically charge card on file
          bodyParameters:
            idempotency_key: 1502dae6-c66f-48cd-a994-251b3eaebf57
            invoice:
              location_id: ES0RJRZYEC39A
              order_id: Wyo24rZbYWnQYQTqFYY92Q69uaB
              scheduled_at: 2030-01-13T10:00:00Z
              primary_recipient:
                customer_id: JDKYHBWT1D4F8MFH63DBMEN8Y4
              delivery_method: EMAIL
              payment_requests:
              - request_type: BALANCE
                due_date: 2030-01-24
                tipping_enabled: true
                card_id: ccof:oSvC0j8sqGECA5DM3GB
                automatic_payment_source: CARD_ON_FILE
                reminders:
                - message: Your card on file will be charged tomorrow.
                  relative_scheduled_days: -1
              invoice_number: inv-104
              title: Event Planning Services
              description: We appreciate your business!
              accepted_payment_methods:
                card: true
                square_gift_card: false
                bank_account: false
              custom_fields:
              - label: Event Reference Number
                value: 'Ref. #1234'
                placement: ABOVE_LINE_ITEMS
              - label: Terms of Service
                value: The terms of service are...
                placement: BELOW_LINE_ITEMS
              sale_or_service_date: 2030-01-24
  /v2/invoices/search:
    post:
      tags:
      - Invoices
      summary: SearchInvoices
      description: "Searches for invoices from a location specified in \nthe filter.\
        \ You can optionally specify customers in the filter for whom to \nretrieve\
        \ invoices. In the current implementation, you can only specify one location\
        \ and \noptionally one customer.\n\nThe response is paginated. If truncated,\
        \ the response includes a `cursor` \nthat you use in a subsequent request\
        \ to retrieve the next set of invoices."
      operationId: SearchInvoices
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
  /v2/invoices/{invoice_id}:
    get:
      tags:
      - Invoices
      summary: GetInvoice
      description: Retrieves an invoice by invoice ID.
      operationId: GetInvoice
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
    put:
      tags:
      - Invoices
      summary: UpdateInvoice
      description: "Updates an invoice by modifying fields, clearing fields, or both.\
        \ For most updates, you can use a sparse \n`Invoice` object to add fields\
        \ or change values and use the `fields_to_clear` field to specify fields to\
        \ clear. \nHowever, some restrictions apply. For example, you cannot change\
        \ the `order_id` or `location_id` field and you \nmust provide the complete\
        \ `custom_fields` list to update a custom field. Published invoices have additional\
        \ restrictions."
      operationId: UpdateInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
      x-endpoint-errors:
      - error-code: MERCHANT_SUBSCRIPTION_NOT_FOUND
    delete:
      tags:
      - Invoices
      summary: DeleteInvoice
      description: "Deletes the specified invoice. When an invoice is deleted, the\
        \ \nassociated order status changes to CANCELED. You can only delete a draft\
        \ \ninvoice (you cannot delete a published invoice, including one that is\
        \ scheduled for processing)."
      operationId: DeleteInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
  /v2/invoices/{invoice_id}/cancel:
    post:
      tags:
      - Invoices
      summary: CancelInvoice
      description: "Cancels an invoice. The seller cannot collect payments for \n\
        the canceled invoice.\n\nYou cannot cancel an invoice in the `DRAFT` state\
        \ or in a terminal state: `PAID`, `REFUNDED`, `CANCELED`, or `FAILED`."
      operationId: CancelInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
  /v2/invoices/{invoice_id}/publish:
    post:
      tags:
      - Invoices
      summary: PublishInvoice
      description: "Publishes the specified draft invoice. \n\nAfter an invoice is\
        \ published, Square \nfollows up based on the invoice configuration. For example,\
        \ Square \nsends the invoice to the customer's email address, charges the\
        \ customer's card on file, or does \nnothing. Square also makes the invoice\
        \ available on a Square-hosted invoice page. \n\nThe invoice `status` also\
        \ changes from `DRAFT` to a status \nbased on the invoice configuration. For\
        \ example, the status changes to `UNPAID` if \nSquare emails the invoice or\
        \ `PARTIALLY_PAID` if Square charge a card on file for a portion of the \n\
        invoice amount."
      operationId: PublishInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /invoice-api/invoice-api-proto/src/main/proto/squareup/invoiceapi/service/public_api.proto
      x-proto-sha: 9ebd276
      x-endpoint-errors:
      - error-code: CARD_DECLINED
      - error-code: INVALID_CARD
  /v2/labor/break-types:
    get:
      tags:
      - Labor
      summary: ListBreakTypes
      description: Returns a paginated list of `BreakType` instances for a business.
      operationId: ListBreakTypes
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
    post:
      tags:
      - Labor
      summary: CreateBreakType
      description: |-
        Creates a new `BreakType`.

        A `BreakType` is a template for creating `Break` objects.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `break_name`
        - `expected_duration`
        - `is_paid`

        You can only have three `BreakType` instances per location. If you attempt to add a fourth
        `BreakType` for a location, an `INVALID_REQUEST_ERROR` "Exceeded limit of 3 breaks per location."
        is returned.
      operationId: CreateBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/break-types/{id}:
    get:
      tags:
      - Labor
      summary: GetBreakType
      description: Returns a single `BreakType` specified by `id`.
      operationId: GetBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
    put:
      tags:
      - Labor
      summary: UpdateBreakType
      description: Updates an existing `BreakType`.
      operationId: UpdateBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
    delete:
      tags:
      - Labor
      summary: DeleteBreakType
      description: |-
        Deletes an existing `BreakType`.

        A `BreakType` can be deleted even if it is referenced from a `Shift`.
      operationId: DeleteBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/employee-wages:
    get:
      tags:
      - Labor
      summary: ListEmployeeWages
      description: Returns a paginated list of `EmployeeWage` instances for a business.
      operationId: ListEmployeeWages
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: ListTeamMemberWages
        guideUrl: https://developer.squareup.com/docs/labor-api/migrate-to-teams
  /v2/labor/employee-wages/{id}:
    get:
      tags:
      - Labor
      summary: GetEmployeeWage
      description: Returns a single `EmployeeWage` specified by `id`.
      operationId: GetEmployeeWage
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: GetTeamMemberWage
        guideUrl: https://developer.squareup.com/docs/labor-api/migrate-to-teams
  /v2/labor/shifts:
    post:
      tags:
      - Labor
      summary: CreateShift
      description: |-
        Creates a new `Shift`.

        A `Shift` represents a complete workday for a single employee.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `employee_id`
        - `start_at`

        An attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:
        - The `status` of the new `Shift` is `OPEN` and the employee has another
        shift with an `OPEN` status.
        - The `start_at` date is in the future.
        - The `start_at` or `end_at` date overlaps another shift for the same employee.
        - The `Break` instances are set in the request and a break `start_at`
        is before the `Shift.start_at`, a break `end_at` is after
        the `Shift.end_at`, or both.
      operationId: CreateShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/shifts/search:
    post:
      tags:
      - Labor
      summary: SearchShifts
      description: |-
        Returns a paginated list of `Shift` records for a business.
        The list to be returned can be filtered by:
        - Location IDs.
        - Employee IDs.
        - Shift status (`OPEN` and `CLOSED`).
        - Shift start.
        - Shift end.
        - Workday details.

        The list can be sorted by:
        - `start_at`.
        - `end_at`.
        - `created_at`.
        - `updated_at`.
      operationId: SearchShifts
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/shifts/{id}:
    get:
      tags:
      - Labor
      summary: GetShift
      description: Returns a single `Shift` specified by `id`.
      operationId: GetShift
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
    put:
      tags:
      - Labor
      summary: UpdateShift
      description: |-
        Updates an existing `Shift`.

        When adding a `Break` to a `Shift`, any earlier `Break` instances in the `Shift` have
        the `end_at` property set to a valid RFC-3339 datetime string.

        When closing a `Shift`, all `Break` instances in the `Shift` must be complete with `end_at`
        set on each `Break`.
      operationId: UpdateShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
    delete:
      tags:
      - Labor
      summary: DeleteShift
      description: Deletes a `Shift`.
      operationId: DeleteShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/team-member-wages:
    get:
      tags:
      - Labor
      summary: ListTeamMemberWages
      description: Returns a paginated list of `TeamMemberWage` instances for a business.
      operationId: ListTeamMemberWages
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/team-member-wages/{id}:
    get:
      tags:
      - Labor
      summary: GetTeamMemberWage
      description: Returns a single `TeamMemberWage` specified by `id `.
      operationId: GetTeamMemberWage
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/workweek-configs:
    get:
      tags:
      - Labor
      summary: ListWorkweekConfigs
      description: Returns a list of `WorkweekConfig` instances for a business.
      operationId: ListWorkweekConfigs
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/labor/workweek-configs/{id}:
    put:
      tags:
      - Labor
      summary: UpdateWorkweekConfig
      description: Updates a `WorkweekConfig`.
      operationId: UpdateWorkweekConfig
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /timecards/timecards-proto/src/main/proto/squareup/labor_api/service.proto
      x-proto-sha: 620d804cdff66f35c9a548a3743eb6fba87ded8a
  /v2/locations:
    get:
      tags:
      - Locations
      summary: ListLocations
      description: |-
        Provides information of all locations of a business.

        Many Square API endpoints require a `location_id` parameter.
        The `id` field of the [`Location`](entity:Location) objects returned by this
        endpoint correspond to that `location_id` parameter.
      operationId: ListLocations
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-unitTests:
      - request:
          method: GET
          uri: /v2/locations
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          statusCode: "200"
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: ListLocations
    post:
      tags:
      - Locations
      summary: CreateLocation
      description: Creates a location.
      operationId: CreateLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/location.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
      x-endpoint-errors:
      - error-code: BAD_REQUEST
  /v2/locations/{location_id}:
    get:
      tags:
      - Locations
      summary: RetrieveLocation
      description: "Retrieves details of a location. You can specify \"main\" \nas\
        \ the location ID to retrieve details of the \nmain location."
      operationId: RetrieveLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-endpoint-errors:
      - error-code: NOT_FOUND
    put:
      tags:
      - Locations
      summary: UpdateLocation
      description: Updates a location.
      operationId: UpdateLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/location.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
      x-endpoint-errors:
      - error-code: BAD_REQUEST
  /v2/locations/{location_id}/additional-recipient-receivable-refunds:
    get:
      tags:
      - Reporting
      summary: ListAdditionalRecipientReceivableRefunds
      description: |-
        Returns a list of refunded transactions (across all possible originating locations) relating to monies
        credited to the provided location ID by another Square account using the `additional_recipients` field in a transaction.

        Max results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50
      operationId: ListAdditionalRecipientReceivableRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: RETIRED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/additional_recipient_receivable/service/additional_recipient_receivable_service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
  /v2/locations/{location_id}/additional-recipient-receivables:
    get:
      tags:
      - Reporting
      summary: ListAdditionalRecipientReceivables
      description: |-
        Returns a list of receivables (across all possible sending locations) representing monies credited
        to the provided location ID by another Square account using the `additional_recipients` field in a transaction.

        Max results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50
      operationId: ListAdditionalRecipientReceivables
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: RETIRED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/additional_recipient_receivable/service/additional_recipient_receivable_service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
  /v2/locations/{location_id}/checkouts:
    post:
      tags:
      - Checkout
      summary: CreateCheckout
      description: |-
        Links a `checkoutId` to a `checkout_page_url` that customers are
        directed to in order to provide their payment information using a
        payment processing workflow hosted on connect.squareup.com.
      operationId: CreateCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /payapi-checkouts/protos/squareup/payapi/checkouts.proto
      x-proto-sha: 97806244325ab9fded53f6629e1303295c8d4db8
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: ORDER_EXPIRED
  /v2/locations/{location_id}/transactions:
    get:
      tags:
      - Transactions
      summary: ListTransactions
      description: |-
        Lists transactions for a particular location.

        Transactions include payment information from sales and exchanges and refund
        information from returns and exchanges.

        Max results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50
      operationId: ListTransactions
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: SearchOrders
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
  /v2/locations/{location_id}/transactions/{transaction_id}:
    get:
      tags:
      - Transactions
      summary: RetrieveTransaction
      description: Retrieves details for a single transaction.
      operationId: RetrieveTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: BatchRetrieveOrders
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
  /v2/locations/{location_id}/transactions/{transaction_id}/capture:
    post:
      tags:
      - Transactions
      summary: CaptureTransaction
      description: |-
        Captures a transaction that was created with the [Charge](api-endpoint:Transactions-Charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: CaptureTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: TBD
        replacedBy: CompletePayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: DELAYED_TRANSACTION_CANCELED
      - error-code: DELAYED_TRANSACTION_EXPIRED
  /v2/locations/{location_id}/transactions/{transaction_id}/void:
    post:
      tags:
      - Transactions
      summary: VoidTransaction
      description: |-
        Cancels a transaction that was created with the [Charge](api-endpoint:Transactions-Charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: VoidTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /xp/connect-public-protos/protos/squareup/connect/v2/service.proto
      x-proto-sha: 1112d951b165be2a6f4d4c47c8f09d258832b4da
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: CancelPayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: DELAYED_TRANSACTION_CAPTURED
      - error-code: DELAYED_TRANSACTION_EXPIRED
  /v2/loyalty/accounts:
    post:
      tags:
      - Loyalty
      summary: CreateLoyaltyAccount
      description: Creates a loyalty account. To create a loyalty account, you must
        provide the `program_id` and a `mapping` with the `phone_number` of the buyer.
      operationId: CreateLoyaltyAccount
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
      x-endpoint-errors:
      - error-code: INVALID_PHONE_NUMBER
  /v2/loyalty/accounts/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyAccounts
      description: "Searches for loyalty accounts in a loyalty program.  \n\nYou can\
        \ search for a loyalty account using the phone number or customer ID associated\
        \ with the account. To return all loyalty accounts, specify an empty `query`\
        \ object or omit it entirely.  \n\nSearch results are sorted by `created_at`\
        \ in ascending order."
      operationId: SearchLoyaltyAccounts
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
      x-example-scenarios:
        scenarios:
        - name: Retrieve all loyalty accounts
          bodyParameters:
            query: {}
            limit: 5
        - name: Search by phone number
          bodyParameters:
            query:
              mappings:
              - phone_number: +14155551234
            limit: 10
        - name: Search by customer ID
          bodyParameters:
            query:
              customer_ids:
              - RPJBC4YA0MTGX8DHTXE9AP2AS4
            limit: 10
  /v2/loyalty/accounts/{account_id}:
    get:
      tags:
      - Loyalty
      summary: RetrieveLoyaltyAccount
      description: Retrieves a loyalty account.
      operationId: RetrieveLoyaltyAccount
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/accounts/{account_id}/accumulate:
    post:
      tags:
      - Loyalty
      summary: AccumulateLoyaltyPoints
      description: "Adds points to a loyalty account.\n\n- If you are using the Orders\
        \ API to manage orders, you only provide the `order_id`. \nThe endpoint reads\
        \ the order to compute points to add to the buyer's account.\n- If you are\
        \ not using the Orders API to manage orders, \nyou first perform a client-side\
        \ computation to compute the points.  \nFor spend-based and visit-based programs,\
        \ you can first call \n[CalculateLoyaltyPoints](api-endpoint:Loyalty-CalculateLoyaltyPoints)\
        \ to compute the points  \nthat you provide to this endpoint. \n\n__Note:__\
        \ The country of the seller's Square account determines whether tax is included\
        \ in the purchase amount when accruing points for spend-based and visit-based\
        \ programs. \nFor more information, see [Availability of Square Loyalty](https://developer.squareup.com/docs/loyalty-api/overview#loyalty-market-availability)."
      operationId: AccumulateLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/accounts/{account_id}/adjust:
    post:
      tags:
      - Loyalty
      summary: AdjustLoyaltyPoints
      description: "Adds points to or subtracts points from a buyer's account. \n\n\
        Use this endpoint only when you need to manually adjust points. Otherwise,\
        \ in your application flow, you call \n[AccumulateLoyaltyPoints](api-endpoint:Loyalty-AccumulateLoyaltyPoints)\
        \ \nto add points when a buyer pays for the purchase."
      operationId: AdjustLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/events/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyEvents
      description: "Searches for loyalty events.\n\nA Square loyalty program maintains\
        \ a ledger of events that occur during the lifetime of a \nbuyer's loyalty\
        \ account. Each change in the point balance \n(for example, points earned,\
        \ points redeemed, and points expired) is \nrecorded in the ledger. Using\
        \ this endpoint, you can search the ledger for events.\n\nSearch results are\
        \ sorted by `created_at` in descending order."
      operationId: SearchLoyaltyEvents
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/programs:
    get:
      tags:
      - Loyalty
      summary: ListLoyaltyPrograms
      description: |-
        Returns a list of loyalty programs in the seller's account.
        Loyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).


        Replaced with [RetrieveLoyaltyProgram](api-endpoint:Loyalty-RetrieveLoyaltyProgram) when used with the keyword `main`.
      operationId: ListLoyaltyPrograms
      deprecated: true
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: DEPRECATED
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
      x-deprecation:
        deprecationDate: 2021-05-13
        retirementDate: 2022-05-13
        replacedBy: RetrieveLoyaltyProgram
        guideUrl: https://developer.squareup.com/docs/loyalty-api/overview#migration-notes
      x-endpoint-errors:
      - error-code: UNSUPPORTED_LOYALTY_REWARD_TIER
  /v2/loyalty/programs/{program_id}:
    get:
      tags:
      - Loyalty
      summary: RetrieveLoyaltyProgram
      description: "Retrieves the loyalty program in a seller's account, specified\
        \ by the program ID or the keyword `main`. \n\nLoyalty programs define how\
        \ buyers can earn points and redeem points for rewards. Square sellers can\
        \ have only one loyalty program, which is created and managed from the Seller\
        \ Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview)."
      operationId: RetrieveLoyaltyProgram
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
      x-endpoint-errors:
      - error-code: UNSUPPORTED_LOYALTY_REWARD_TIER
  /v2/loyalty/programs/{program_id}/calculate:
    post:
      tags:
      - Loyalty
      summary: CalculateLoyaltyPoints
      description: "Calculates the points a purchase earns.\n\n- If you are using\
        \ the Orders API to manage orders, you provide `order_id` in the request.\
        \ The \nendpoint calculates the points by reading the order.\n- If you are\
        \ not using the Orders API to manage orders, you provide the purchase amount\
        \ in \nthe request for the endpoint to calculate the points.\n\nAn application\
        \ might call this endpoint to show the points that a buyer can earn with the\
        \ \nspecific purchase.\n\n__Note:__ The country of the seller's Square account\
        \ determines whether tax is included in the purchase amount when accruing\
        \ points for spend-based and visit-based programs. \nFor more information,\
        \ see [Availability of Square Loyalty](https://developer.squareup.com/docs/loyalty-api/overview#loyalty-market-availability)."
      operationId: CalculateLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/rewards:
    post:
      tags:
      - Loyalty
      summary: CreateLoyaltyReward
      description: "Creates a loyalty reward. In the process, the endpoint does following:\n\
        \n- Uses the `reward_tier_id` in the request to determine the number of points\
        \ \nto lock for this reward. \n- If the request includes `order_id`, it adds\
        \ the reward and related discount to the order. \n\nAfter a reward is created,\
        \ the points are locked and \nnot available for the buyer to redeem another\
        \ reward."
      operationId: CreateLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/rewards/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyRewards
      description: "Searches for loyalty rewards in a loyalty account. \n\nIn the\
        \ current implementation, the endpoint supports search by the reward `status`.\n\
        \nIf you know a reward ID, use the \n[RetrieveLoyaltyReward](api-endpoint:Loyalty-RetrieveLoyaltyReward)\
        \ endpoint.\n\nSearch results are sorted by `updated_at` in descending order."
      operationId: SearchLoyaltyRewards
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/rewards/{reward_id}:
    get:
      tags:
      - Loyalty
      summary: RetrieveLoyaltyReward
      description: Retrieves a loyalty reward.
      operationId: RetrieveLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
    delete:
      tags:
      - Loyalty
      summary: DeleteLoyaltyReward
      description: "Deletes a loyalty reward by doing the following:\n\n- Returns\
        \ the loyalty points back to the loyalty account.\n- If an order ID was specified\
        \ when the reward was created \n(see [CreateLoyaltyReward](api-endpoint:Loyalty-CreateLoyaltyReward)),\
        \ \nit updates the order by removing the reward and related \ndiscounts.\n\
        \nYou cannot delete a reward that has reached the terminal state (REDEEMED)."
      operationId: DeleteLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/loyalty/rewards/{reward_id}/redeem:
    post:
      tags:
      - Loyalty
      summary: RedeemLoyaltyReward
      description: "Redeems a loyalty reward.\n\nThe endpoint sets the reward to the\
        \ `REDEEMED` terminal state. \n\nIf you are using your own order processing\
        \ system (not using the \nOrders API), you call this endpoint after the buyer\
        \ paid for the \npurchase.\n\nAfter the reward reaches the terminal state,\
        \ it cannot be deleted. \nIn other words, points used for the reward cannot\
        \ be returned \nto the account."
      operationId: RedeemLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /card/balance/connect-api/src/main/proto/squareup/card/balance/loyalty_api/service.proto
      x-proto-sha: 2f9af662b731efbbf896124dbf94b78a098cca9c
  /v2/merchants:
    get:
      tags:
      - Merchants
      summary: ListMerchants
      description: |-
        Returns `Merchant` information for a given access token.

        If you don't know a `Merchant` ID, you can use this endpoint to retrieve the merchant ID for an access token.
        You can specify your personal access token to get your own merchant information or specify an OAuth token
        to get the information for the  merchant that granted you access.

        If you know the merchant ID, you can also use the [RetrieveMerchant](api-endpoint:Merchants-RetrieveMerchant)
        endpoint to get the merchant information.
      operationId: ListMerchants
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/merchant.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
  /v2/merchants/{merchant_id}:
    get:
      tags:
      - Merchants
      summary: RetrieveMerchant
      description: Retrieve a `Merchant` object for the given `merchant_id`.
      operationId: RetrieveMerchant
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /roster/frontend/api/src/main/proto/squareup/roster/frontend/external/merchant.proto
      x-proto-sha: 6d6df970856ed806d6545553c0b0b58d074f5d8a
  /v2/orders:
    post:
      tags:
      - Orders
      summary: CreateOrder
      description: "Creates a new [order](entity:Order) that can include information\
        \ about products for\npurchase and settings to apply to the purchase.\n\n\
        To pay for a created order, see \n[Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders).\n\
        \nYou can modify open orders using the [UpdateOrder](api-endpoint:Orders-UpdateOrder)\
        \ endpoint."
      operationId: CreateOrder
      security:
      - oauth2:
        - ORDERS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/batch-retrieve:
    post:
      tags:
      - Orders
      summary: BatchRetrieveOrders
      description: |-
        Retrieves a set of [orders](entity:Order) by their IDs.

        If a given order ID does not exist, the ID is ignored instead of generating an error.
      operationId: BatchRetrieveOrders
      security:
      - oauth2:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/calculate:
    post:
      tags:
      - Orders
      summary: CalculateOrder
      description: Enables applications to preview order pricing without creating
        an order.
      operationId: CalculateOrder
      security:
      - oauth2: []
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/clone:
    post:
      tags:
      - Orders
      summary: CloneOrder
      description: "Creates a new order, in the `DRAFT` state, by duplicating an existing\
        \ order. The newly created order has \nonly the core fields (such as line\
        \ items, taxes, and discounts) copied from the original order."
      operationId: CloneOrder
      security:
      - oauth2:
        - ORDERS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/search:
    post:
      tags:
      - Orders
      summary: SearchOrders
      description: |-
        Search all orders for one or more locations. Orders include all sales,
        returns, and exchanges regardless of how or when they entered the Square
        ecosystem (such as Point of Sale, Invoices, and Connect APIs).

        `SearchOrders` requests need to specify which locations to search and define a
        [SearchOrdersQuery](entity:SearchOrdersQuery) object that controls
        how to sort or filter the results. Your `SearchOrdersQuery` can:

          Set filter criteria.
          Set the sort order.
          Determine whether to return results as complete `Order` objects or as
        [OrderEntry](entity:OrderEntry) objects.

        Note that details for orders processed with Square Point of Sale while in
        offline mode might not be transmitted to Square for up to 72 hours. Offline
        orders have a `created_at` value that reflects the time the order was created,
        not the time it was subsequently transmitted to Square.
      operationId: SearchOrders
      security:
      - oauth2:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/{order_id}:
    get:
      tags:
      - Orders
      summary: RetrieveOrder
      description: Retrieves an [Order](entity:Order) by ID.
      operationId: RetrieveOrder
      security:
      - oauth2:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
    put:
      tags:
      - Orders
      summary: UpdateOrder
      description: "Updates an open [order](entity:Order) by adding, replacing, or\
        \ deleting\nfields. Orders with a `COMPLETED` or `CANCELED` state cannot be\
        \ updated.\n\nAn `UpdateOrder` request requires the following:\n\n- The `order_id`\
        \ in the endpoint path, identifying the order to update.\n- The latest `version`\
        \ of the order to update.\n- The [sparse order](https://developer.squareup.com/docs/orders-api/manage-orders#sparse-order-objects)\n\
        containing only the fields to update and the version to which the update is\n\
        being applied.\n- If deleting fields, the [dot notation paths](https://developer.squareup.com/docs/orders-api/manage-orders#on-dot-notation)\n\
        identifying the fields to clear.\n\nTo pay for an order, see \n[Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders)."
      operationId: UpdateOrder
      security:
      - oauth2:
        - ORDERS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/orders/{order_id}/pay:
    post:
      tags:
      - Orders
      summary: PayOrder
      description: |-
        Pay for an [order](entity:Order) using one or more approved [payments](entity:Payment)
        or settle an order with a total of `0`.

        The total of the `payment_ids` listed in the request must be equal to the order
        total. Orders with a total amount of `0` can be marked as paid by specifying an empty
        array of `payment_ids` in the request.

        To be used with `PayOrder`, a payment must:

        - Reference the order by specifying the `order_id` when [creating the payment](api-endpoint:Payments-CreatePayment).
        Any approved payments that reference the same `order_id` not specified in the
        `payment_ids` is canceled.
        - Be approved with [delayed capture](https://developer.squareup.com/docs/payments-api/take-payments#delayed-capture).
        Using a delayed capture payment with `PayOrder` completes the approved payment.
      operationId: PayOrder
      security:
      - oauth2:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: BETA
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /orders/orders-service-proto/src/main/proto/squareup/omg/service.proto
      x-proto-sha: 83e541ea6c2e7f3c6ac461588091df6047c2b588
  /v2/payments:
    get:
      tags:
      - Payments
      summary: ListPayments
      description: |-
        Retrieves a list of payments taken by the account making the request.

        Results are eventually consistent, and new payments or changes to payments might take several
        seconds to appear.

        The maximum results per page is 100.
      operationId: ListPayments
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
    post:
      tags:
      - Payments
      summary: CreatePayment
      description: "Creates a payment using the provided source. You can use this\
        \ endpoint \nto charge a card (credit/debit card or    \nSquare gift card)\
        \ or record a payment that the seller received outside of Square \n(cash payment\
        \ from a buyer or a payment that an external entity \nprocessed on behalf\
        \ of the seller).\n\nThe endpoint creates a \n`Payment` object and returns\
        \ it in the response."
      operationId: CreatePayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
      x-endpoint-errors:
      - error-code: ADDRESS_VERIFICATION_FAILURE
      - error-code: ALLOWABLE_PIN_TRIES_EXCEEDED
      - error-code: BAD_EXPIRATION
      - error-code: CARDHOLDER_INSUFFICIENT_PERMISSIONS
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_NOT_SUPPORTED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: CHIP_INSERTION_REQUIRED
      - error-code: CVV_FAILURE
      - error-code: EXPIRATION_FAILURE
      - error-code: GENERIC_DECLINE
      - error-code: GIFT_CARD_AVAILABLE_AMOUNT
      - error-code: INSUFFICIENT_FUNDS
      - error-code: INSUFFICIENT_PERMISSIONS
      - error-code: INVALID_ACCOUNT
      - error-code: INVALID_CARD
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EMAIL_ADDRESS
      - error-code: INVALID_EXPIRATION
      - error-code: INVALID_FEES
      - error-code: INVALID_LOCATION
      - error-code: INVALID_PIN
      - error-code: INVALID_POSTAL_CODE
      - error-code: MANUALLY_ENTERED_PAYMENT_NOT_SUPPORTED
      - error-code: PAN_FAILURE
      - error-code: PAYMENT_LIMIT_EXCEEDED
      - error-code: TEMPORARY_ERROR
      - error-code: TRANSACTION_LIMIT
      - error-code: VOICE_FAILURE
  /v2/payments/cancel:
    post:
      tags:
      - Payments
      summary: CancelPaymentByIdempotencyKey
      description: |-
        Cancels (voids) a payment identified by the idempotency key that is specified in the
        request.

        Use this method when the status of a `CreatePayment` request is unknown (for example, after you send a
        `CreatePayment` request, a network error occurs and you do not get a response). In this case, you can
        direct Square to cancel the payment using this endpoint. In the request, you provide the same
        idempotency key that you provided in your `CreatePayment` request that you want to cancel. After
        canceling the payment, you can submit your `CreatePayment` request again.

        Note that if no payment with the specified idempotency key is found, no action is taken and the endpoint
        returns successfully.
      operationId: CancelPaymentByIdempotencyKey
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
  /v2/payments/{payment_id}:
    get:
      tags:
      - Payments
      summary: GetPayment
      description: Retrieves details for a specific payment.
      operationId: GetPayment
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
    put:
      tags:
      - Payments
      summary: UpdatePayment
      description: |-
        Updates a payment with the APPROVED status.
        You can update the `amount_money` and `tip_money` using this endpoint.
      operationId: UpdatePayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: GENERIC_DECLINE
      - error-code: INSUFFICIENT_FUNDS
      - error-code: INVALID_FEES
      - error-code: PAYMENT_LIMIT_EXCEEDED
      - error-code: TEMPORARY_ERROR
      - error-code: TRANSACTION_LIMIT
  /v2/payments/{payment_id}/cancel:
    post:
      tags:
      - Payments
      summary: CancelPayment
      description: "Cancels (voids) a payment. You can use this endpoint to cancel\
        \ a payment with \nthe APPROVED `status`."
      operationId: CancelPayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
  /v2/payments/{payment_id}/complete:
    post:
      tags:
      - Payments
      summary: CompletePayment
      description: |-
        Completes (captures) a payment.
        By default, payments are set to complete immediately after they are created.

        You can use this endpoint to complete a payment with the APPROVED `status`.
      operationId: CompletePayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
      x-endpoint-errors:
      - error-code: VERSION_MISMATCH
  /v2/refunds:
    get:
      tags:
      - Refunds
      summary: ListPaymentRefunds
      description: |-
        Retrieves a list of refunds for the account making the request.

        Results are eventually consistent, and new refunds or changes to refunds might take several
        seconds to appear.

        The maximum results per page is 100.
      operationId: ListPaymentRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
    post:
      tags:
      - Refunds
      summary: RefundPayment
      description: "Refunds a payment. You can refund the entire payment amount or\
        \ a\nportion of it. You can use this endpoint to refund a card payment or\
        \ record a \nrefund of a cash or external payment. For more information, see\n\
        [Refund Payment](https://developer.squareup.com/docs/payments-api/refund-payments)."
      operationId: RefundPayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: PAYMENT_NOT_REFUNDABLE
      - error-code: REFUND_AMOUNT_INVALID
      - error-code: REFUND_DECLINED
      - error-code: VERSION_MISMATCH
  /v2/refunds/{refund_id}:
    get:
      tags:
      - Refunds
      summary: GetPaymentRefund
      description: Retrieves a specific refund using the `refund_id`.
      operationId: GetPaymentRefund
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /pago/pago-proto/src/main/proto/squareup/pago/external/payments_service.proto
      x-proto-sha: 816934ee952386fa95f2829a713f36f455fbef04
  /v2/sites:
    get:
      tags:
      - Sites
      summary: ListSites
      description: |-
        Lists the Square Online sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: ListSites
      security:
      - oauth2:
        - ONLINE_STORE_SITE_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /ecom-connect/protos/squareup/ecom_connect/service/ecom_connect_service.proto
      x-proto-sha: fb3d3423678699286c092ccc816e6444b8bd130e
      x-not-supported-in-sandbox: true
  /v2/sites/{site_id}/snippet:
    get:
      tags:
      - Snippets
      summary: RetrieveSnippet
      description: |-
        Retrieves your snippet from a Square Online site. A site can contain snippets from multiple snippet applications, but you can retrieve only the snippet that was added by your application.

        You can call [ListSites](api-endpoint:Sites-ListSites) to get the IDs of the sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: RetrieveSnippet
      security:
      - oauth2:
        - ONLINE_STORE_SNIPPETS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /ecom-connect/protos/squareup/ecom_connect/service/ecom_connect_service.proto
      x-proto-sha: fb3d3423678699286c092ccc816e6444b8bd130e
      x-not-supported-in-sandbox: true
    post:
      tags:
      - Snippets
      summary: UpsertSnippet
      description: "Adds a snippet to a Square Online site or updates the existing\
        \ snippet on the site. \nThe snippet code is appended to the end of the `head`\
        \ element on every page of the site, except checkout pages. A snippet application\
        \ can add one snippet to a given site. \n\nYou can call [ListSites](api-endpoint:Sites-ListSites)\
        \ to get the IDs of the sites that belong to a seller.\n\n\n__Note:__ Square\
        \ Online APIs are publicly available as part of an early access program. For\
        \ more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis)."
      operationId: UpsertSnippet
      security:
      - oauth2:
        - ONLINE_STORE_SNIPPETS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /ecom-connect/protos/squareup/ecom_connect/service/ecom_connect_service.proto
      x-proto-sha: fb3d3423678699286c092ccc816e6444b8bd130e
      x-not-supported-in-sandbox: true
    delete:
      tags:
      - Snippets
      summary: DeleteSnippet
      description: |-
        Removes your snippet from a Square Online site.

        You can call [ListSites](api-endpoint:Sites-ListSites) to get the IDs of the sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: DeleteSnippet
      security:
      - oauth2:
        - ONLINE_STORE_SNIPPETS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/GO/repos/square/browse
      x-proto-location: /ecom-connect/protos/squareup/ecom_connect/service/ecom_connect_service.proto
      x-proto-sha: fb3d3423678699286c092ccc816e6444b8bd130e
      x-not-supported-in-sandbox: true
  /v2/subscriptions:
    post:
      tags:
      - Subscriptions
      summary: CreateSubscription
      description: |-
        Creates a subscription for a customer to a subscription plan.

        If you provide a card on file in the request, Square charges the card for
        the subscription. Otherwise, Square bills an invoice to the customer's email
        address. The subscription starts immediately, unless the request includes
        the optional `start_date`. Each individual subscription is associated with a particular location.
      operationId: CreateSubscription
      security:
      - oauth2:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
      x-endpoint-errors:
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CUSTOMER_NOT_FOUND
  /v2/subscriptions/search:
    post:
      tags:
      - Subscriptions
      summary: SearchSubscriptions
      description: |-
        Searches for subscriptions.
        Results are ordered chronologically by subscription creation date. If
        the request specifies more than one location ID,
        the endpoint orders the result
        by location ID, and then by creation date within each location. If no locations are given
        in the query, all locations are searched.

        You can also optionally specify `customer_ids` to search by customer.
        If left unset, all customers
        associated with the specified locations are returned.
        If the request specifies customer IDs, the endpoint orders results
        first by location, within location by customer ID, and within
        customer by subscription creation date.

        For more information, see
        [Retrieve subscriptions](https://developer.squareup.com/docs/subscriptions-api/overview#retrieve-subscriptions).
      operationId: SearchSubscriptions
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
      x-endpoint-errors:
      - error-code: CUSTOMER_NOT_FOUND
  /v2/subscriptions/{subscription_id}:
    get:
      tags:
      - Subscriptions
      summary: RetrieveSubscription
      description: Retrieves a subscription.
      operationId: RetrieveSubscription
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
    put:
      tags:
      - Subscriptions
      summary: UpdateSubscription
      description: |-
        Updates a subscription. You can set, modify, and clear the
        `subscription` field values.
      operationId: UpdateSubscription
      security:
      - oauth2:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
      x-endpoint-errors:
      - error-code: CUSTOMER_NOT_FOUND
  /v2/subscriptions/{subscription_id}/cancel:
    post:
      tags:
      - Subscriptions
      summary: CancelSubscription
      description: |-
        Sets the `canceled_date` field to the end of the active billing period.
        After this date, the status changes from ACTIVE to CANCELED.
      operationId: CancelSubscription
      security:
      - oauth2:
        - SUBSCRIPTIONS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
  /v2/subscriptions/{subscription_id}/events:
    get:
      tags:
      - Subscriptions
      summary: ListSubscriptionEvents
      description: |-
        Lists all events for a specific subscription.
        In the current implementation, only `START_SUBSCRIPTION` and `STOP_SUBSCRIPTION` (when the subscription was canceled) events are returned.
      operationId: ListSubscriptionEvents
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
  /v2/subscriptions/{subscription_id}/resume:
    post:
      tags:
      - Subscriptions
      summary: ResumeSubscription
      description: Resumes a deactivated subscription.
      operationId: ResumeSubscription
      security:
      - oauth2:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /buyer-subs/buyer-subs-proto/src/main/proto/squareup/buyersubs/external/subscriptions_service.proto
      x-proto-sha: 432ab81ce314934b4afd9ba131cdd40a94061e1f
      x-endpoint-errors:
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CUSTOMER_NOT_FOUND
  /v2/team-members:
    post:
      tags:
      - Team
      summary: CreateTeamMember
      description: |-
        Creates a single `TeamMember` object. The `TeamMember` object is returned on successful creates.
        You must provide the following values in your request to this endpoint:
        - `given_name`
        - `family_name`

        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#createteammember).
      operationId: CreateTeamMember
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/team-members/bulk-create:
    post:
      tags:
      - Team
      summary: BulkCreateTeamMembers
      description: |-
        Creates multiple `TeamMember` objects. The created `TeamMember` objects are returned on successful creates.
        This process is non-transactional and processes as much of the request as possible. If one of the creates in
        the request cannot be successfully processed, the request is not marked as failed, but the body of the response
        contains explicit error information for the failed create.

        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#bulk-create-team-members).
      operationId: BulkCreateTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/team-members/bulk-update:
    post:
      tags:
      - Team
      summary: BulkUpdateTeamMembers
      description: |-
        Updates multiple `TeamMember` objects. The updated `TeamMember` objects are returned on successful updates.
        This process is non-transactional and processes as much of the request as possible. If one of the updates in
        the request cannot be successfully processed, the request is not marked as failed, but the body of the response
        contains explicit error information for the failed update.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#bulk-update-team-members).
      operationId: BulkUpdateTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/team-members/search:
    post:
      tags:
      - Team
      summary: SearchTeamMembers
      description: |-
        Returns a paginated list of `TeamMember` objects for a business.
        The list can be filtered by the following:
        - location IDs
        - `status`
      operationId: SearchTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/team-members/{team_member_id}:
    get:
      tags:
      - Team
      summary: RetrieveTeamMember
      description: |-
        Retrieves a `TeamMember` object for the given `TeamMember.id`.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#retrieve-a-team-member).
      operationId: RetrieveTeamMember
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
    put:
      tags:
      - Team
      summary: UpdateTeamMember
      description: |-
        Updates a single `TeamMember` object. The `TeamMember` object is returned on successful updates.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#update-a-team-member).
      operationId: UpdateTeamMember
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/team-members/{team_member_id}/wage-setting:
    get:
      tags:
      - Team
      summary: RetrieveWageSetting
      description: |-
        Retrieves a `WageSetting` object for a team member specified
        by `TeamMember.id`.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#retrievewagesetting).
      operationId: RetrieveWageSetting
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
    put:
      tags:
      - Team
      summary: UpdateWageSetting
      description: |-
        Creates or updates a `WageSetting` object. The object is created if a
        `WageSetting` with the specified `team_member_id` does not exist. Otherwise,
        it fully replaces the `WageSetting` object for the team member.
        The `WageSetting` is returned on a successful update.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#create-or-update-a-wage-setting).
      operationId: UpdateWageSetting
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /team-members/team-members-proto/src/main/proto/squareup/team_api/service.proto
      x-proto-sha: 35e42321a09f40bdc25482a4978baef3c5bce048
  /v2/terminals/checkouts:
    post:
      tags:
      - Terminal
      summary: CreateTerminalCheckout
      description: |-
        Creates a Terminal checkout request and sends it to the specified device to take a payment
        for the requested amount.
      operationId: CreateTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_checkout_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: IDEMPOTENCY_KEY_REUSED
      - error-code: INVALID_VALUE
      - error-code: UNAUTHORIZED
  /v2/terminals/checkouts/search:
    post:
      tags:
      - Terminal
      summary: SearchTerminalCheckouts
      description: Retrieves a filtered list of Terminal checkout requests created
        by the account making the request.
      operationId: SearchTerminalCheckouts
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_checkout_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: INVALID_CURSOR
      - error-code: UNKNOWN_QUERY_PARAMETER
  /v2/terminals/checkouts/{checkout_id}:
    get:
      tags:
      - Terminal
      summary: GetTerminalCheckout
      description: Retrieves a Terminal checkout request by `checkout_id`.
      operationId: GetTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_checkout_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
  /v2/terminals/checkouts/{checkout_id}/cancel:
    post:
      tags:
      - Terminal
      summary: CancelTerminalCheckout
      description: Cancels a Terminal checkout request if the status of the request
        permits it.
      operationId: CancelTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_checkout_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
  /v2/terminals/refunds:
    post:
      tags:
      - Terminal
      summary: CreateTerminalRefund
      description: Creates a request to refund an Interac payment completed on a Square
        Terminal.
      operationId: CreateTerminalRefund
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_refund_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
  /v2/terminals/refunds/search:
    post:
      tags:
      - Terminal
      summary: SearchTerminalRefunds
      description: Retrieves a filtered list of Interac Terminal refund requests created
        by the seller making the request.
      operationId: SearchTerminalRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_refund_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
  /v2/terminals/refunds/{terminal_refund_id}:
    get:
      tags:
      - Terminal
      summary: GetTerminalRefund
      description: Retrieves an Interac Terminal refund object by ID.
      operationId: GetTerminalRefund
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_refund_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
  /v2/terminals/refunds/{terminal_refund_id}/cancel:
    post:
      tags:
      - Terminal
      summary: CancelTerminalRefund
      description: Cancels an Interac Terminal refund request by refund request ID
        if the status of the request permits it.
      operationId: CancelTerminalRefund
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-proto-repo: https://git.sqcorp.co/projects/SQ/repos/java/browse
      x-proto-location: /mango/mango-proto/src/main/proto/squareup/mango/external/terminal_refund_service.proto
      x-proto-sha: 5a3b622139b89256beca17c51dddedbe75c6aa42
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          tokenUrl: https://connect.squareup.com/oauth2/token
          scopes:
            BANK_ACCOUNTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to bank account information associated with the targeted
              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.
            CASH_DRAWER_READ: |-
              __HTTP Method__: `GET`

              Grants read access to cash drawer shift information. For example, to call the
              ListCashDrawerShifts endpoint.
            CUSTOMERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to customer information. For example, to call the
              ListCustomers endpoint.
            CUSTOMERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to customer information. For example, to create and update
              customer profiles.
            DEVICE_CREDENTIAL_MANAGEMENT: |-
              __HTTP Method__: `POST`, `GET`

              Grants read/write access to device credentials information. For example, to
              call the CreateDeviceCode endpoint.
            EMPLOYEES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee profile information. For example, to call the
              Connect v1 Employees API.
            EMPLOYEES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee profile information. For example, to create
              and modify employee profiles.
            INVENTORY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to inventory information. For example, to call the
              RetrieveInventoryCount endpoint.
            INVENTORY_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to inventory information. For example, to call the
              BatchChangeInventory endpoint.
            ITEMS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ITEMS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to product catalog information. For example, to modify or
              add to a product catalog.
            LOYALTY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to loyalty information. For example, to call the
              ListLoyaltyPrograms endpoint.
            LOYALTY_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to loyalty information. For example, to call the
              CreateLoyaltyAccount endpoint.
            MERCHANT_PROFILE_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ORDERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to order information. For example, to call the
              BatchRetrieveOrders endpoint.
            ORDERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to order information. For example, to call the
              CreateCheckout endpoint.
            PAYMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to transaction and refund information. For example, to call
              the RetrieveTransaction endpoint.
            PAYMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to transaction and refunds information. For example, to
              process payments with the Payments or Checkout API.
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allow third party applications to deduct a portion of each transaction amount.
              __Required__ to use multiparty transaction functionality with the Payments
              API.
            PAYMENTS_WRITE_IN_PERSON: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to payments and refunds information. For example, to
              process in-person payments.
            SETTLEMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to settlement (deposit) information. For example, to call
              the Connect v1 ListSettlements endpoint.
            TIMECARDS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard information. For example, to call the
              Connect v2 SearchShifts endpoint.
            TIMECARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee shift information. For example, to create
              and modify employee shifts.
            TIMECARDS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard settings information. For example, to
              call the GetBreakType endpoint.
            TIMECARDS_SETTINGS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee timecard settings information. For example, to
              call the UpdateBreakType endpoint.
            APPOINTMENTS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to booking information. For example, to call the
              RetrieveBooking endpoint.
            APPOINTMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to booking information. For example, to call the CreateBooking endpoint.
            APPOINTMENTS_BUSINESS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to booking business settings. For example, to call the
              ListTeamMemberBookingProfiles endpoint.
            INVOICES_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to invoice information. For example, to call the ListInvoices endpoint.
            INVOICES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to invoice information. For example, to call the CreateInvoice endpoint.
            SUBSCRIPTIONS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to subscription information. For example, to call the RetrieveSubscription
              endpoint.
            SUBSCRIPTIONS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to subscription information. For example, to call the CreateSubscription
              endpoint.
            DISPUTES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to dispute information. For example, to call the RetrieveDispute
              endpoint.
            DISPUTES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to dispute information. For example, to call the SubmitEvidence
              endpoint.
            GIFTCARDS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to gift card information. For example, to call the RetrieveGiftCard
              endpoint.
            GIFTCARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to gift card information. For example, to call the CreateGiftCard
              endpoint.
            ONLINE_STORE_SNIPPETS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Write access to ECOM online store snippets on published websites.
            ONLINE_STORE_SNIPPETS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store snippets on published websites.
            ONLINE_STORE_SITE_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store site details.
            PAYMENTS_WRITE_SHARED_ONFILE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allows the developer to process payments on behalf of a seller using a shared on file payment method.
      x-additional-headers:
      - name: Square-Version
        description: Square Connect API versions
        schema:
          default: 2021-10-20
    oauth2ClientSecret:
      type: apiKey
      name: Authorization
      in: header
  x-apis:
    Disputes:
      name: Disputes
      summary: Use the Disputes API to manage disputes (chargebacks).
      description: |2-

        A seller has the following options to process a dispute:

        - Accept the dispute using the [AcceptDispute](/reference/square/disputes-api/accept-dispute) endpoint. Square returns the disputed amount from the account balance of the Square account.
        - Challenge the dispute using the [SubmitEvidence](/reference/square/disputes-api/submit-evidence) endpoint. If the payment was valid, you can contest the disputed payment.
        You submit supporting evidence you have about the transaction, such as receipts, invoices, email correspondence, proof of delivery, or photos.
        You upload evidence using the [CreateDisputeEvidenceFile](/reference/square/disputes-api/create-dispute-evidence-file) endpoint.

        The Disputes API also supports other endpoints useful in dispute management.
      x-namespace: ""
      externalDocsList:
      - description: Disputes
        url: https://developer.squareup.com/docs/disputes-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    MobileAuthorization:
      name: Mobile Authorization
      summary: Authorize Reader SDK applications to take in-person payments.
      description: |2-

        The Mobile Authorization API accepts an account credential (an OAuth token or a personal access token) and a
        location ID and returns an authorization code that custom mobile applications can use to initialize Square mobile
        solutions, like Reader SDK, to accept payments using Square hardware.
      x-namespace: ""
      externalDocsList:
      - description: Mobile Authorization
        url: https://developer.squareup.com/docs/mobile-authz/what-it-does
    Sites:
      name: Sites
      summary: Get details about Square Online sites that belong to Square sellers.
      description: |2-

        Square sellers use Square Online to build eCommerce websites. The Sites API lets you get basic details about Square Online sites, such as the site ID, title, and domain. You can use the Sites API with the Snippets API to manage snippets that extend Square Online features.

         __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      x-namespace: ""
      externalDocsList:
      - description: Sites
        url: https://developer.squareup.com/docs/sites-api/overview
    Catalog:
      name: Catalog
      summary: Programmatically catalogs a Square seller’s products for sale and services
        for hire.
      description: |2-

        The Catalog API allows you to programmatically catalog products or services, including items, variations, categories, discounts, taxes, modifiers, and more.
      x-namespace: ""
      externalDocsList:
      - description: Catalog
        url: https://developer.squareup.com/docs/catalog-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Labor:
      name: Labor
      summary: Manage shifts, breaks, and wages for employees in Square Point of Sale.
      description: |2-

        The Labor API allows you to see when employees clocked in and out, how much they worked during different
        periods, and how many breaks they took. You can also call the API to register a past break, adjust a shift,
        or update a wage.

        This API is best used in conjunction with the Team API.
      x-namespace: ""
      externalDocsList:
      - description: Labor
        url: https://developer.squareup.com/docs/labor-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Team:
      name: Team
      summary: Pull employee data into accounting and payroll systems with the Team
        API.
      description: |2-

        The Team API allows applications to retrieve a roster of team members registered in the Square Point
        of Sale system, which can be useful in payroll and account contexts.

        The Team API is best used in conjunction with the Labor API, where you provide team member IDs to
        manage shifts, breaks, and wages.
      x-namespace: ""
      externalDocsList:
      - description: Team
        url: https://developer.squareup.com/docs/team/overview
    Orders:
      name: Orders
      summary: Get sales data for a Square seller, itemize payments, push orders to
        POS, and more.
      description: |2-

        The Orders API is your one-stop shop for adding rich functionality to payments. You can itemize
        payments using custom line items or catalog objects, send orders to physical Point of Sale devices
        to be fulfilled, attach a customer to a payment, and more.

        In addition, the Orders API lets you search through all of a seller's past sales and returns itemization
        data, customer references, and other details from sales made using POS or online.

        If you use the Square Orders API with a non-Square payments provider, Square charges a transaction fee. For more information, see [Orders API fee structure.](https://developer.squareup.com/docs/payments-pricing#orders-api-fee-structure)
      x-namespace: ""
      externalDocsList:
      - description: Orders
        url: https://developer.squareup.com/docs/orders-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Locations:
      name: Locations
      summary: Get a list of all a seller's locations.
      description: |2-

        Many sellers use multiple locations to track where they make sales. The Locations API allows you to
        get data about those locations, such as their addresses, names, and business hours.
      x-namespace: ""
      externalDocsList:
      - description: Locations
        url: https://developer.squareup.com/docs/locations-api
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Payments:
      name: Payments
      summary: The Payments API lets developers take and manage payments.
      description: "\nApplications need the following input to take a payment:\n\n\
        - The amount to charge.\n- The payment recipient. The payment goes to the\
        \ account identified by the Authorization header in the API request.\n- The\
        \ payment source. The source can be a payment token or card on file.\n\n \
        \ You can generate a payment token using the Web Payments SDK and the In-App\
        \ Payments SDK. For working code examples, see [Square Connect API Examples](https://github.com/square/connect-api-examples).\n\
        \n  A card on file is a credit card, debit card, or gift card that is associated\
        \ with a customer. \n  You can create a customer and add a card on file using\
        \ Square APIs, the Square Seller Dashboard, or the Square Point of Sale application.\n"
      x-namespace: ""
      externalDocsList:
      - description: Payments
        url: https://developer.squareup.com/docs/payments-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    CashDrawers:
      name: Cash Drawers
      summary: Get details about cash drawers.
      description: |2-

        Cash drawers track cash transactions so that the total money in the cash drawers can be reconciled for a
        specific period of time (a cash drawer shift), for a particular device, in a particular location. The Cash Drawers API
        enables you to list and retrieve cash drawers information.
      x-namespace: ""
      externalDocsList:
      - description: Cash Drawer Shifts
        url: https://developer.squareup.com/docs/cashdrawershift-api/reporting
    Transactions:
      name: Transactions
      summary: Deprecated - Use the Orders and Payments APIs instead.
      description: "\nPrior to 2019/08/15, the Transactions API was the way to take\
        \ online payments. Going forward, the Payments API \nand Refunds API (together\
        \ with the Orders API) replace the Transactions API."
      x-namespace: ""
    Cards:
      name: Cards
      summary: Use the Cards API to save a credit or debit card on file.
      description: |2-

        You can use the [CreateCard](/reference/square/cards-api/create-card) endpoint to save a credit or debit card to a Square account.
        Developers can integrate the Cards API in their application to let Square sellers:

        - **Save a card that can be charged by any Square seller who uses your application.** `Your application specifies the organization access token in the `CreateCard` request.
        - **Save a card that can be charged by a single Square seller.**  Your application specifies the access token of the specific seller account in the `CreateCard` request.

        The Cards API also supports other endpoints to manage the cards.
      x-namespace: ""
      externalDocsList:
      - description: Cards
        url: https://developer.squareup.com/docs/cards-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Settlements:
      name: Settlements
      summary: Get a list of deposits and withdrawals from a seller's bank accounts.
      description: |2-

        __The V1 Settlements API has been deprecated__. The Settlements API allows you to see a complete list of settlements made to a seller's bank account,
        with a list of settlement entries that describe the payments associated with each settlement. It can be paired with the
        Bank Accounts API to add detail about which bank account each settlement was made to.
      x-namespace: ""
    Merchants:
      name: Merchants
      summary: Use the Merchants API to retrieve information about a Square merchant
        account.
      description: |2-

        For example, suppose you develop an application (an eCommerce or a SaaS platform) integrated
        with Square to process payments. Other Square sellers sign up to use your application.

        In this scenario, the application developer can use the Merchants API to retrieve seller account information
        (such as language, business name, country, and account status) as shown in the following `RetrieveMerchant` request.
        In the request, the Authorization header provides an OAuth access token that identifies the seller whose account
        information is requested.
      x-namespace: ""
      externalDocsList:
[...]
