openapi: 3.0.0
info:
  title: Square
  description: Use Square APIs to manage and run business including payment, customer,
    product, inventory, and employee management.
  termsOfService: https://connect.squareup.com/tos
  contact:
    name: Square Developer Platform
    url: https://squareup.com/developers
    email: developers@squareup.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "2.0"
  x-server-configuration:
    default-environment: production
    default-server: default
    environments:
    - name: production
      servers:
      - name: default
        url: https://connect.squareup.com
    - name: sandbox
      servers:
      - name: default
        url: https://connect.squareupsandbox.com
  x-square-generic-error-codes:
  - ACCESS_TOKEN_EXPIRED
  - ACCESS_TOKEN_REVOKED
  - API_VERSION_INCOMPATIBLE
  - APPLICATION_DISABLED
  - ARRAY_EMPTY
  - ARRAY_LENGTH_TOO_LONG
  - ARRAY_LENGTH_TOO_SHORT
  - BAD_CERTIFICATE
  - BAD_GATEWAY
  - BAD_REQUEST
  - CONFLICT
  - CONFLICTING_PARAMETERS
  - CURRENCY_MISMATCH
  - EXPECTED_ARRAY
  - EXPECTED_BASE64_ENCODED_BYTE_ARRAY
  - EXPECTED_BOOLEAN
  - EXPECTED_FLOAT
  - EXPECTED_INTEGER
  - EXPECTED_JSON_BODY
  - EXPECTED_MAP
  - EXPECTED_OBJECT
  - EXPECTED_STRING
  - FORBIDDEN
  - GATEWAY_TIMEOUT
  - GONE
  - IDEMPOTENCY_KEY_REUSED
  - INCORRECT_TYPE
  - INSUFFICIENT_SCOPES
  - INTERNAL_SERVER_ERROR
  - INVALID_ARRAY_VALUE
  - INVALID_CONTENT_TYPE
  - INVALID_CURSOR
  - INVALID_ENUM_VALUE
  - INVALID_FORM_VALUE
  - INVALID_SORT_ORDER
  - INVALID_SQUARE_VERSION_FORMAT
  - INVALID_TIME
  - INVALID_TIME_RANGE
  - INVALID_VALUE
  - LOCATION_MISMATCH
  - MAP_KEY_LENGTH_TOO_LONG
  - MAP_KEY_LENGTH_TOO_SHORT
  - METHOD_NOT_ALLOWED
  - MISSING_REQUIRED_PARAMETER
  - NOT_ACCEPTABLE
  - NOT_FOUND
  - NOT_IMPLEMENTED
  - NO_FIELDS_SET
  - RATE_LIMITED
  - REQUEST_ENTITY_TOO_LARGE
  - REQUEST_TIMEOUT
  - SANDBOX_NOT_SUPPORTED
  - SERVICE_UNAVAILABLE
  - TOO_MANY_MAP_ENTRIES
  - UNAUTHORIZED
  - UNEXPECTED_VALUE
  - UNKNOWN_QUERY_PARAMETER
  - UNPROCESSABLE_ENTITY
  - UNSUPPORTED_MEDIA_TYPE
  - V1_ACCESS_TOKEN
  - V1_APPLICATION
  - VALUE_EMPTY
  - VALUE_REGEX_MISMATCH
  - VALUE_TOO_HIGH
  - VALUE_TOO_LONG
  - VALUE_TOO_LOW
  - VALUE_TOO_SHORT
servers:
- url: https://connect.squareup.com
paths:
  /mobile/authorization-code:
    post:
      tags:
      - MobileAuthorization
      summary: CreateMobileAuthorizationCode
      description: |-
        Generates code to authorize a mobile application to connect to a Square card reader

        Authorization codes are one-time-use and expire __60 minutes__ after being issued.

        __Important:__ The `Authorization` header you provide to this endpoint must have the following format:

        ```
        Authorization: Bearer ACCESS_TOKEN
        ```

        Replace `ACCESS_TOKEN` with a
        [valid production authorization credential](https://developer.squareup.com/docs/docs/build-basics/access-tokens).
      operationId: CreateMobileAuthorizationCode
      security:
      - oauth2:
        - PAYMENTS_WRITE_IN_PERSON
      x-release-status: PUBLIC
  /oauth2/authorize:
    get:
      tags:
      - OAuth
      summary: Authorize
      description: |-
        Presents a Permission Request form that returns an access
        code to be exchanged during the OAuth flow for a valid OAuth access token.
        To send users to the Permission Request form and start the OAuth flow,
        configure a link with the desired permissions that directs users to the
        OAuth Authorization endpoint. See the
        [OAuth Build Guide](https://developer.squareup.com/docs/oauth-api/build-with-oauth) for more information.

        In the event of an error, Authorize returns an error response
        (`error` and `error_description`). If the failure is a result of the user
        denying the request, the value is `access_denied` with a description of
        `user_denied`.
      operationId: Authorize
      security: []
      x-release-status: PUBLIC
      x-visibility: DOC_ONLY
  /oauth2/clients/{client_id}/access-token/renew:
    post:
      tags:
      - OAuth
      summary: RenewToken
      description: |-
        `RenewToken` is deprecated. For information about refreshing OAuth access tokens, see
        [Renew OAuth Token](https://developer.squareup.com/docs/oauth-api/cookbook/renew-oauth-tokens).


        Renews an OAuth access token before it expires.

        OAuth access tokens besides your application's personal access token expire after __30 days__.
        You can also renew expired tokens within __15 days__ of their expiration.
        You cannot renew an access token that has been expired for more than 15 days.
        Instead, the associated user must re-complete the OAuth flow from the beginning.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the Credentials
        page in the [application dashboard](https://connect.squareup.com/apps).
      operationId: RenewToken
      deprecated: true
      security:
      - oauth2ClientSecret: []
      x-release-status: DEPRECATED
      x-deprecation: {}
  /oauth2/revoke:
    post:
      tags:
      - OAuth
      summary: RevokeToken
      description: |-
        Revokes an access token generated with the OAuth flow.

        If an account has more than one OAuth access token for your application, this
        endpoint revokes all of them, regardless of which token you specify. When an
        OAuth access token is revoked, all of the active subscriptions associated
        with that OAuth token are canceled immediately.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the Credentials
        page in the [application dashboard](https://connect.squareup.com/apps).
      operationId: RevokeToken
      security:
      - oauth2ClientSecret: []
      x-release-status: PUBLIC
  /oauth2/token:
    post:
      tags:
      - OAuth
      summary: ObtainToken
      description: |-
        Returns an OAuth access token.

        The endpoint supports distinct methods of obtaining OAuth access tokens.
        Applications specify a method by adding the `grant_type` parameter
        in the request and also provide relevant information.
        For more information, see [OAuth access token management](https://developer.squareup.com/docs/authz/oauth/how-it-works#oauth-access-token-management).

        __Note:__ Regardless of the method application specified,
        the endpoint always returns two items; an OAuth access token and
        a refresh token in the response.

        __OAuth tokens should only live on secure servers. Application clients
        should never interact directly with OAuth tokens__.
      operationId: ObtainToken
      security: []
      x-release-status: PUBLIC
  /v1/batch:
    post:
      tags:
      - V1Batching
      summary: V1SubmitBatch
      description: |-
        Bundle multiple requests to Connect V1 API endpoints as a single
        request.


        The __V1SubmitBatch__ endpoint does not require an access token
        in the request header. Instead, provide an `access_token` parameter for
        each request included in the batch.

        __V1SubmitBatch__ responds with an array that contains response objects for
        each of the batched requests. There is no guarantee of the order in
        which batched requests are performed.


        __IMPORTANT__

        You cannot include more than 30 requests in a single batch and
        recursive requests to __V1SubmitBatch__ are not allowed. In
        other words, none of the requests included in a batch can itself be a
        request to the __V1SubmitBatch__ endpoint.
      operationId: V1SubmitBatch
      deprecated: true
      security: []
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/general-guidance#v1batching
      x-visibility: DOC_ONLY
  /v1/me:
    get:
      tags:
      - V1Locations
      summary: RetrieveBusiness
      description: Get the general information for a business.
      operationId: RetrieveBusiness
      deprecated: true
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: RetrieveLocation
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-locations
  /v1/me/employees:
    get:
      tags:
      - V1Employees
      summary: ListEmployees
      description: Provides summary information for all of a business's employees.
      operationId: ListEmployees
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    post:
      tags:
      - V1Employees
      summary: CreateEmployee
      description: |2-
         Use the CreateEmployee endpoint to add an employee to a Square
        account. Employees created with the Connect API have an initial status
        of `INACTIVE`. Inactive employees cannot sign in to Square Point of Sale
        until they are activated from the Square Dashboard. Employee status
        cannot be changed with the Connect API.

        <aside class="important">
        Employee entities cannot be deleted. To disable employee profiles,
        set the employee's status to <code>INACTIVE</code>
        </aside>
      operationId: CreateEmployee
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v1/me/employees/{employee_id}:
    get:
      tags:
      - V1Employees
      summary: RetrieveEmployee
      description: Provides the details for a single employee.
      operationId: RetrieveEmployee
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    put:
      tags:
      - V1Employees
      summary: UpdateEmployee
      operationId: UpdateEmployee
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v1/me/locations:
    get:
      tags:
      - V1Locations
      summary: ListLocations
      description: |-
        Provides details for all business locations associated with a Square
        account, including the Square-assigned object ID for the location.
      operationId: ListLocations
      deprecated: true
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListLocations
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-locations
  /v1/me/roles:
    get:
      tags:
      - V1Employees
      summary: ListEmployeeRoles
      description: Provides summary information for all of a business's employee roles.
      operationId: ListEmployeeRoles
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    post:
      tags:
      - V1Employees
      summary: CreateEmployeeRole
      description: |-
        Creates an employee role you can then assign to employees.

        Square accounts can include any number of roles that can be assigned to
        employees. These roles define the actions and permissions granted to an
        employee with that role. For example, an employee with a "Shift Manager"
        role might be able to issue refunds in Square Point of Sale, whereas an
        employee with a "Clerk" role might not.

        Roles are assigned with the [V1UpdateEmployee](#endpoint-v1updateemployee)
        endpoint. An employee can have only one role at a time.

        If an employee has no role, they have none of the permissions associated
        with roles. All employees can accept payments with Square Point of Sale.
      operationId: CreateEmployeeRole
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v1/me/roles/{role_id}:
    get:
      tags:
      - V1Employees
      summary: RetrieveEmployeeRole
      description: Provides the details for a single employee role.
      operationId: RetrieveEmployeeRole
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    put:
      tags:
      - V1Employees
      summary: UpdateEmployeeRole
      description: Modifies the details of an employee role.
      operationId: UpdateEmployeeRole
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v1/me/timecards:
    get:
      tags:
      - V1Employees
      summary: ListTimecards
      description: Provides summary information for all of a business's employee timecards.
      operationId: ListTimecards
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: SearchShifts
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
    post:
      tags:
      - V1Employees
      summary: CreateTimecard
      description: |-
        Creates a timecard for an employee and clocks them in with an
        `API_CREATE` event and a `clockin_time` set to the current time unless
        the request provides a different value.

        To import timecards from another
        system (rather than clocking someone in). Specify the `clockin_time`
        and* `clockout_time` in the request.

        Timecards correspond to exactly one shift for a given employee, bounded
        by the `clockin_time` and `clockout_time` fields. An employee is
        considered clocked in if they have a timecard that doesn't have a
        `clockout_time` set. An employee that is currently clocked in cannot
        be clocked in a second time.
      operationId: CreateTimecard
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: CreateShift
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
  /v1/me/timecards/{timecard_id}:
    get:
      tags:
      - V1Employees
      summary: RetrieveTimecard
      description: |-
        Provides the details for a single timecard.


        <aside>
        Only approved accounts can manage their employees with Square.
        Unapproved accounts cannot use employee management features with the
        API.
        </aside>
      operationId: RetrieveTimecard
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: GetShift
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
    put:
      tags:
      - V1Employees
      summary: UpdateTimecard
      description: |-
        Modifies the details of a timecard with an `API_EDIT` event for
        the timecard. Updating an active timecard with a `clockout_time`
        clocks the employee out.
      operationId: UpdateTimecard
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: UpdateShift
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
    delete:
      tags:
      - V1Employees
      summary: DeleteTimecard
      description: |-
        Deletes a timecard. Timecards can also be deleted through the
        Square Dashboard. Deleted timecards are still accessible through
        Connect API endpoints, but cannot be modified. The `deleted` field of
        the `Timecard` object indicates whether the timecard has been deleted.


        __Note__: By default, deleted timecards appear alongside valid timecards in
        results returned by the [ListTimecards](#endpoint-v1employees-listtimecards)
        endpoint. To filter deleted timecards, include the `deleted` query
        parameter in the list request.

        Only approved accounts can manage their employees with Square.
        Unapproved accounts cannot use employee management features with the
        API.
      operationId: DeleteTimecard
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: DeleteShift
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
  /v1/me/timecards/{timecard_id}/events:
    get:
      tags:
      - V1Employees
      summary: ListTimecardEvents
      description: |-
        Provides summary information for all events associated with a
        particular timecard.


        <aside>
        Only approved accounts can manage their employees with Square.
        Unapproved accounts cannot use employee management features with the
        API.
        </aside>
      operationId: ListTimecardEvents
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-timecards
  /v1/{location_id}/bank-accounts:
    get:
      tags:
      - V1Transactions
      summary: ListBankAccounts
      description: Provides non-confidential details for all of a location's associated
        bank accounts. This endpoint does not provide full bank account numbers, and
        there is no way to obtain a full bank account number with the Connect API.
      operationId: ListBankAccounts
      deprecated: true
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: ListBankAccounts
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-bankaccounts
  /v1/{location_id}/bank-accounts/{bank_account_id}:
    get:
      tags:
      - V1Transactions
      summary: RetrieveBankAccount
      description: Provides non-confidential details for a merchant's associated bank
        account. This endpoint does not provide full bank account numbers, and there
        is no way to obtain a full bank account number with the Connect API.
      operationId: RetrieveBankAccount
      deprecated: true
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: GetBankAccount
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-bankaccounts
  /v1/{location_id}/cash-drawer-shifts:
    get:
      tags:
      - V1Employees
      summary: ListCashDrawerShifts
      description: Provides the details for all of a location's cash drawer shifts
        during a date range. The date range you specify cannot exceed 90 days.
      operationId: ListCashDrawerShifts
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: ListCashDrawerShifts
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-cashdrawershifts
  /v1/{location_id}/cash-drawer-shifts/{shift_id}:
    get:
      tags:
      - V1Employees
      summary: RetrieveCashDrawerShift
      description: Provides the details for a single cash drawer shift, including
        all events that occurred during the shift.
      operationId: RetrieveCashDrawerShift
      deprecated: true
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-02-26
        retirementDate: 2021-02-26
        replacedBy: RetrieveCashDrawerShift
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-cashdrawershifts
  /v1/{location_id}/categories:
    get:
      tags:
      - V1Items
      summary: ListCategories
      description: Lists all the item categories for a given location.
      operationId: ListCategories
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListCatalog
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreateCategory
      description: Creates an item category.
      operationId: CreateCategory
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/categories/{category_id}:
    put:
      tags:
      - V1Items
      summary: UpdateCategory
      description: Modifies the details of an existing item category.
      operationId: UpdateCategory
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteCategory
      description: |-
        Deletes an existing item category.


        __DeleteCategory__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteCategoryRequest` object
        as documented below.
      operationId: DeleteCategory
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/discounts:
    get:
      tags:
      - V1Items
      summary: ListDiscounts
      description: Lists all the discounts for a given location.
      operationId: ListDiscounts
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListCatalog
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreateDiscount
      description: Creates a discount.
      operationId: CreateDiscount
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/discounts/{discount_id}:
    put:
      tags:
      - V1Items
      summary: UpdateDiscount
      description: Modifies the details of an existing discount.
      operationId: UpdateDiscount
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteDiscount
      description: |-
        Deletes an existing discount.


        __DeleteDiscount__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteDiscountRequest` object
        as documented below.
      operationId: DeleteDiscount
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/fees:
    get:
      tags:
      - V1Items
      summary: ListFees
      description: Lists all the fees (taxes) for a given location.
      operationId: ListFees
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListCatalog
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreateFee
      description: Creates a fee (tax).
      operationId: CreateFee
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/fees/{fee_id}:
    put:
      tags:
      - V1Items
      summary: UpdateFee
      description: Modifies the details of an existing fee (tax).
      operationId: UpdateFee
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteFee
      description: |-
        Deletes an existing fee (tax).


        __DeleteFee__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteFeeRequest` object
        as documented below.
      operationId: DeleteFee
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/inventory:
    get:
      tags:
      - V1Items
      summary: ListInventory
      description: |-
        Provides inventory information for all inventory-enabled item
        variations.
      operationId: ListInventory
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: BatchRetrieveInventoryCounts
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/inventory/{variation_id}:
    post:
      tags:
      - V1Items
      summary: AdjustInventory
      description: Adjusts the current available inventory of an item variation.
      operationId: AdjustInventory
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: BatchChangeInventory
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items:
    get:
      tags:
      - V1Items
      summary: ListItems
      description: Provides summary information of all items for a given location.
      operationId: ListItems
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListCatalog
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreateItem
      description: |-
        Creates an item and at least one variation for it.



        Item-related entities include fields you can use to associate them with
        entities in a non-Square system.

        When you create an item-related entity, you can optionally specify `id`.
        This value must be unique among all IDs ever specified for the account,
        including those specified by other applications. You can never reuse an
        entity ID. If you do not specify an ID, Square generates one for the entity.

        Item variations have a `user_data` string that lets you associate arbitrary
        metadata with the variation. The string cannot exceed 255 characters.
      operationId: CreateItem
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items/{item_id}:
    get:
      tags:
      - V1Items
      summary: RetrieveItem
      description: |-
        Provides the details for a single item, including associated modifier
        lists and fees.
      operationId: RetrieveItem
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: RetrieveCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    put:
      tags:
      - V1Items
      summary: UpdateItem
      description: Modifies the core details of an existing item.
      operationId: UpdateItem
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteItem
      description: |-
        Deletes an existing item and all item variations associated with it.


        __DeleteItem__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteItemRequest` object
        as documented below.
      operationId: DeleteItem
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items/{item_id}/fees/{fee_id}:
    put:
      tags:
      - V1Items
      summary: ApplyFee
      description: |-
        Associates a fee with an item so the fee is automatically applied to
        the item in Square Point of Sale.
      operationId: ApplyFee
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpdateItemTaxes
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: RemoveFee
      description: |-
        Removes a fee assocation from an item so the fee is no longer
        automatically applied to the item in Square Point of Sale.
      operationId: RemoveFee
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpdateItemTaxes
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items/{item_id}/image:
    post:
      tags:
      - V1Items
      summary: UploadItemImage
      description: |-
        Uploads a JPEG or PNG image and sets it as the master image for
        an item.


        If you upload an image for an item that already has a master image, the new
        image replaces the existing one.

        <aside class="important">
        Requests to this endpoint use the
        <code>Content-Type: multipart/form-data</code> header instead of
        <code>Content-Type: application/json</code>. Square recommends using an
        HTTP library (such as Requests for Python) that simplifies the process for
        sending <code>multipart/form-data</code> requests.
        </aside>

        The request body assumes the multipart boundary for the request is set to
        `BOUNDARY` in the `Content-Type header`, for example:
        ```
        Content-Type: multipart/form-data; boundary=BOUNDARY
        ```
        __Note__: some HTTP libraries will set the multipart boundary for you.
      operationId: UploadItemImage
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: CreateCatalogImage
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
      x-visibility: DOC_ONLY
  /v1/{location_id}/items/{item_id}/modifier-lists/{modifier_list_id}:
    put:
      tags:
      - V1Items
      summary: ApplyModifierList
      description: |-
        Associates a modifier list with an item so the associated modifier
        options can be applied to the item.
      operationId: ApplyModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpdateItemModifierLists
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: RemoveModifierList
      description: |-
        Removes a modifier list association from an item so the modifier
        options from the list can no longer be applied to the item.
      operationId: RemoveModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpdateItemModifierLists
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items/{item_id}/variations:
    post:
      tags:
      - V1Items
      summary: CreateVariation
      description: Creates an item variation for an existing item.
      operationId: CreateVariation
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/items/{item_id}/variations/{variation_id}:
    put:
      tags:
      - V1Items
      summary: UpdateVariation
      description: Modifies the details of an existing item variation.
      operationId: UpdateVariation
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteVariation
      description: |-
        Deletes an existing item variation from an item.


        __DeleteVariation__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteVariationRequest` object
        as documented below.
      operationId: DeleteVariation
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/modifier-lists:
    get:
      tags:
      - V1Items
      summary: ListModifierLists
      description: Lists all the modifier lists for a given location.
      operationId: ListModifierLists
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: ListCatalog
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreateModifierList
      description: Creates an item modifier list and at least 1 modifier option for
        it.
      operationId: CreateModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/modifier-lists/{modifier_list_id}:
    get:
      tags:
      - V1Items
      summary: RetrieveModifierList
      description: Provides the details for a single modifier list.
      operationId: RetrieveModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: RetrieveCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    put:
      tags:
      - V1Items
      summary: UpdateModifierList
      description: Modifies the details of an existing item modifier list.
      operationId: UpdateModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteModifierList
      description: |-
        Deletes an existing item modifier list and all modifier options
        associated with it.


        __DeleteModifierList__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeleteModifierListRequest` object
        as documented below.
      operationId: DeleteModifierList
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options:
    post:
      tags:
      - V1Items
      summary: CreateModifierOption
      description: Creates an item modifier option and adds it to a modifier list.
      operationId: CreateModifierOption
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options/{modifier_option_id}:
    put:
      tags:
      - V1Items
      summary: UpdateModifierOption
      description: Modifies the details of an existing item modifier option.
      operationId: UpdateModifierOption
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: UpsertCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeleteModifierOption
      description: |-
        Deletes an existing item modifier option from a modifier list.


        __DeleteModifierOption__ returns nothing on success but Connect
        SDKs map the empty response to an empty `V1DeleteModifierOptionRequest`
        object.
      operationId: DeleteModifierOption
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        replacedBy: DeleteCatalogObject
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/pages:
    get:
      tags:
      - V1Items
      summary: ListPages
      description: |-
        Lists all Favorites pages (in Square Point of Sale) for a given
        location.
      operationId: ListPages
      deprecated: true
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    post:
      tags:
      - V1Items
      summary: CreatePage
      description: Creates a Favorites page in Square Point of Sale.
      operationId: CreatePage
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/pages/{page_id}:
    put:
      tags:
      - V1Items
      summary: UpdatePage
      description: Modifies the details of a Favorites page in Square Point of Sale.
      operationId: UpdatePage
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeletePage
      description: |-
        Deletes an existing Favorites page and all of its cells.


        __DeletePage__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeletePageRequest` object.
      operationId: DeletePage
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/pages/{page_id}/cells:
    put:
      tags:
      - V1Items
      summary: UpdatePageCell
      description: Modifies a cell of a Favorites page in Square Point of Sale.
      operationId: UpdatePageCell
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
    delete:
      tags:
      - V1Items
      summary: DeletePageCell
      description: |-
        Deletes a cell from a Favorites page in Square Point of Sale.


        __DeletePageCell__ returns nothing on success but Connect SDKs
        map the empty response to an empty `V1DeletePageCellRequest` object
        as documented below.
      operationId: DeletePageCell
      deprecated: true
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-11-20
        retirementDate: 2020-11-18
        guideUrl: https://developer.squareup.com/docs/migrate-from-v1/guides/v1-items
  /v1/{location_id}/payments:
    get:
      tags:
      - V1Transactions
      summary: ListPayments
      description: |-
        Provides summary information for all payments taken for a given
        Square account during a date range. Date ranges cannot exceed 1 year in
        length. See Date ranges for details of inclusive and exclusive dates.

        *Note**: Details for payments processed with Square Point of Sale while
        in offline mode may not be transmitted to Square for up to 72 hours.
        Offline payments have a `created_at` value that reflects the time the
        payment was originally processed, not the time it was subsequently
        transmitted to Square. Consequently, the ListPayments endpoint might
        list an offline payment chronologically between online payments that
        were seen in a previous request.
      operationId: ListPayments
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
  /v1/{location_id}/payments/{payment_id}:
    get:
      tags:
      - V1Transactions
      summary: RetrievePayment
      description: Provides comprehensive information for a single payment.
      operationId: RetrievePayment
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
  /v1/{location_id}/refunds:
    get:
      tags:
      - V1Transactions
      summary: ListRefunds
      description: Provides the details for all refunds initiated by a merchant or
        any of the merchant's mobile staff during a date range. Date ranges cannot
        exceed one year in length.
      operationId: ListRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
    post:
      tags:
      - V1Transactions
      summary: CreateRefund
      description: |-
        Issues a refund for a previously processed payment. You must issue
        a refund within 60 days of the associated payment.

        You cannot issue a partial refund for a split tender payment. You must
        instead issue a full or partial refund for a particular tender, by
        providing the applicable tender id to the V1CreateRefund endpoint.
        Issuing a full refund for a split tender payment refunds all tenders
        associated with the payment.

        Issuing a refund for a card payment is not reversible. For development
        purposes, you can create fake cash payments in Square Point of Sale and
        refund them.
      operationId: CreateRefund
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
  /v1/{location_id}/settlements:
    get:
      tags:
      - V1Transactions
      summary: ListSettlements
      description: |-
        Provides summary information for all deposits and withdrawals
        initiated by Square to a linked bank account during a date range. Date
        ranges cannot exceed one year in length.

        *Note**: the ListSettlements endpoint does not provide entry
        information.
      operationId: ListSettlements
      security:
      - oauth2:
        - SETTLEMENTS_READ
      x-release-status: PUBLIC
  /v1/{location_id}/settlements/{settlement_id}:
    get:
      tags:
      - V1Transactions
      summary: RetrieveSettlement
      description: |-
        Provides comprehensive information for a single settlement.

        The returned `Settlement` objects include an `entries` field that lists
        the transactions that contribute to the settlement total. Most
        settlement entries correspond to a payment payout, but settlement
        entries are also generated for less common events, like refunds, manual
        adjustments, or chargeback holds.

        Square initiates its regular deposits as indicated in the
        [Deposit Options with Square](https://squareup.com/help/us/en/article/3807)
        help article. Details for a regular deposit are usually not available
        from Connect API endpoints before 10 p.m. PST the same day.

        Square does not know when an initiated settlement **completes**, only
        whether it has failed. A completed settlement is typically reflected in
        a bank account within 3 business days, but in exceptional cases it may
        take longer.
      operationId: RetrieveSettlement
      security:
      - oauth2:
        - SETTLEMENTS_READ
      x-release-status: PUBLIC
  /v1/{location_id}/webhooks:
    get:
      tags:
      - V1Webhooks
      summary: ListWebhooks
      description: |-
        Lists which types of events trigger webhook notifications for a particular location.
        See the [V1 Webhooks API guide](https://developer.squareup.com/docs/webhooks-api/what-it-does-v1) for more information.
      operationId: ListWebhooks
      security:
      - oauth2:
        - TIMECARDS_READ
        - PAYMENTS_READ
        - ITEMS_READ
      x-release-status: PUBLIC
      x-visibility: DOC_ONLY
    put:
      tags:
      - V1Webhooks
      summary: UpdateWebhooks
      description: |-
        Changes the webhook event subscriptions for a location.
        See the [V1 Webhooks API guide](https://developer.squareup.com/docs/webhooks-api/what-it-does-v1) for more information.
      operationId: UpdateWebhooks
      security:
      - oauth2:
        - TIMECARDS_READ
        - PAYMENTS_READ
        - ITEMS_READ
      x-release-status: PUBLIC
      x-visibility: DOC_ONLY
  /v2/apple-pay/domains:
    post:
      tags:
      - ApplePay
      summary: RegisterDomain
      description: |-
        Activates a domain for use with Web Apple Pay and Square. A validation
        will be performed on this domain by Apple to ensure is it properly set up as
        an Apple Pay enabled domain.

        This endpoint provides an easy way for platform developers to bulk activate
        Web Apple Pay with Square for merchants using their platform.

        To learn more about Apple Pay on Web see the Apple Pay section in the
        [Square Payment Form Walkthrough](https://developer.squareup.com/docs/docs/payment-form/payment-form-walkthrough).
      operationId: RegisterDomain
      security:
      - oauth2: []
      x-release-status: PUBLIC
  /v2/bank-accounts:
    get:
      tags:
      - BankAccounts
      summary: ListBankAccounts
      description: "Returns a list of [BankAccount](#type-bankaccount) objects linked\
        \ to a Square account. \nFor more information, see \n[Bank Accounts API](https://developer.squareup.com/docs/docs/bank-accounts-api)."
      operationId: ListBankAccounts
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
  /v2/bank-accounts/by-v1-id/{v1_bank_account_id}:
    get:
      tags:
      - BankAccounts
      summary: GetBankAccountByV1Id
      description: "Returns details of a [BankAccount](#type-bankaccount) identified\
        \ by V1 bank account ID. \nFor more information, see \n[Retrieve a bank account\
        \ by using an ID issued by V1 Bank Accounts API](https://developer.squareup.com/docs/docs/bank-accounts-api#retrieve-a-bank-account-by-using-an-id-issued-by-the-v1-bank-accounts-api)."
      operationId: GetBankAccountByV1Id
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
  /v2/bank-accounts/{bank_account_id}:
    get:
      tags:
      - BankAccounts
      summary: GetBankAccount
      description: "Returns details of a [BankAccount](#type-bankaccount) \nlinked\
        \ to a Square account. For more information, see \n[Bank Accounts API](https://developer.squareup.com/docs/docs/bank-accounts-api)."
      operationId: GetBankAccount
      security:
      - oauth2:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
  /v2/cash-drawers/shifts:
    get:
      tags:
      - CashDrawers
      summary: ListCashDrawerShifts
      description: |-
        Provides the details for all of the cash drawer shifts for a location
        in a date range.
      operationId: ListCashDrawerShifts
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
  /v2/cash-drawers/shifts/{shift_id}:
    get:
      tags:
      - CashDrawers
      summary: RetrieveCashDrawerShift
      description: |-
        Provides the summary details for a single cash drawer shift. See
        RetrieveCashDrawerShiftEvents for a list of cash drawer shift events.
      operationId: RetrieveCashDrawerShift
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
  /v2/cash-drawers/shifts/{shift_id}/events:
    get:
      tags:
      - CashDrawers
      summary: ListCashDrawerShiftEvents
      description: Provides a paginated list of events for a single cash drawer shift.
      operationId: ListCashDrawerShiftEvents
      security:
      - oauth2:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
  /v2/catalog/batch-delete:
    post:
      tags:
      - Catalog
      summary: BatchDeleteCatalogObjects
      description: |-
        Deletes a set of [CatalogItem](#type-catalogitem)s based on the
        provided list of target IDs and returns a set of successfully deleted IDs in
        the response. Deletion is a cascading event such that all children of the
        targeted object are also deleted. For example, deleting a CatalogItem will
        also delete all of its [CatalogItemVariation](#type-catalogitemvariation)
        children.

        `BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted
        IDs can be deleted. The response will only include IDs that were
        actually deleted.
      operationId: BatchDeleteCatalogObjects
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Delete multiple catalog objects
          bodyParameters:
            object_ids:
            - W62UWFY35CWMYGVWK6TWJDNI
            - AA27W3M2GGTF3H6AVPNB77CK
  /v2/catalog/batch-retrieve:
    post:
      tags:
      - Catalog
      summary: BatchRetrieveCatalogObjects
      description: |-
        Returns a set of objects based on the provided ID.
        Each [CatalogItem](#type-catalogitem) returned in the set includes all of its
        child information including: all of its
        [CatalogItemVariation](#type-catalogitemvariation) objects, references to
        its [CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of
        any [CatalogTax](#type-catalogtax) objects that apply to it.
      operationId: BatchRetrieveCatalogObjects
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Retrieve multiple catalog objects
          request_body:
            object_ids:
            - W62UWFY35CWMYGVWK6TWJDNI
            - AA27W3M2GGTF3H6AVPNB77CK
            include_related_objects: true
  /v2/catalog/batch-upsert:
    post:
      tags:
      - Catalog
      summary: BatchUpsertCatalogObjects
      description: |-
        Creates or updates up to 10,000 target objects based on the provided
        list of objects. The target objects are grouped into batches and each batch is
        inserted/updated in an all-or-nothing manner. If an object within a batch is
        malformed in some way, or violates a database constraint, the entire batch
        containing that item will be disregarded. However, other batches in the same
        request may still succeed. Each batch may contain up to 1,000 objects, and
        batches will be processed in order as long as the total object count for the
        request (items, variations, modifier lists, discounts, and taxes) is no more
        than 10,000.
      operationId: BatchUpsertCatalogObjects
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Add a batch of objects to the catalog
          bodyParams:
            idempotency_key: 789ff020-f723-43a9-b4b5-43b5dc1fa3dc
            batches:
            - objects:
              - type: ITEM
                id: '#Tea'
                present_at_all_locations: true
                item_data:
                  name: Tea
                  description: Hot Leaf Juice
                  category_id: '#Beverages'
                  tax_ids:
                  - '#SalesTax'
                  variations:
                  - type: ITEM_VARIATION
                    id: '#Tea_Mug'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Tea'
                      name: Mug
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 150
                        currency: USD
              - type: ITEM
                id: '#Coffee'
                present_at_all_locations: true
                item_data:
                  name: Coffee
                  description: Hot Bean Juice
                  category_id: '#Beverages'
                  tax_ids:
                  - '#SalesTax'
                  variations:
                  - type: ITEM_VARIATION
                    id: '#Coffee_Regular'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Coffee'
                      name: Regular
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 250
                        currency: USD
                  - type: ITEM_VARIATION
                    id: '#Coffee_Large'
                    present_at_all_locations: true
                    item_variation_data:
                      item_id: '#Coffee'
                      name: Large
                      pricing_type: FIXED_PRICING
                      price_money:
                        amount: 350
                        currency: USD
              - type: CATEGORY
                id: '#Beverages'
                present_at_all_locations: true
                category_data:
                  name: Beverages
              - type: TAX
                id: '#SalesTax'
                present_at_all_locations: true
                tax_data:
                  name: Sales Tax
                  calculation_phase: TAX_SUBTOTAL_PHASE
                  inclusion_type: ADDITIVE
                  percentage: "5.0"
                  applies_to_custom_amounts: true
                  enabled: true
  /v2/catalog/images:
    post:
      tags:
      - Catalog
      summary: CreateCatalogImage
      description: |-
        Uploads an image file to be represented by an [CatalogImage](#type-catalogimage) object linked to an existing
        [CatalogObject](#type-catalogobject) instance. A call to this endpoint can upload an image, link an image to
        a catalog object, or do both.

        This `CreateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in
        JPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.

        Additional information and an example cURL request can be found in the [Create a Catalog Image recipe](https://developer.squareup.com/docs/more-apis/catalog/cookbook/create-catalog-images).
      operationId: CreateCatalogImage
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Upload an image for a catalog object
          bodyParams:
            idempotency_key: 528dea59-7bfb-43c1-bd48-4a6bba7dd61f86
            object_id: ND6EA5AAJEO5WL3JNNIAQA32
            image:
              id: '#TEMP_ID'
              type: IMAGE
              image_data:
                caption: A picture of a cup of coffee
  /v2/catalog/info:
    get:
      tags:
      - Catalog
      summary: CatalogInfo
      description: |-
        Retrieves information about the Square Catalog API, such as batch size
        limits that can be used by the `BatchUpsertCatalogObjects` endpoint.
      operationId: CatalogInfo
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Get catalog API information
  /v2/catalog/list:
    get:
      tags:
      - Catalog
      summary: ListCatalog
      description: |-
        Returns a list of [CatalogObject](#type-catalogobject)s that includes
        all objects of a set of desired types (for example, all [CatalogItem](#type-catalogitem)
        and [CatalogTax](#type-catalogtax) objects) in the catalog. The `types` parameter
        is specified as a comma-separated list of valid [CatalogObject](#type-catalogobject) types:
        `ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`.

        __Important:__ ListCatalog does not return deleted catalog items. To retrieve
        deleted catalog items, use SearchCatalogObjects and set `include_deleted_objects`
        to `true`.
      operationId: ListCatalog
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: List catalog objects of a certain type
          requestParams:
            types: category,tax
  /v2/catalog/object:
    post:
      tags:
      - Catalog
      summary: UpsertCatalogObject
      description: Creates or updates the target [CatalogObject](#type-catalogobject).
      operationId: UpsertCatalogObject
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Add an item
          bodyParameters:
            idempotency_key: af3d1afc-7212-4300-b463-0bfc5314a5ae
            object:
              type: ITEM
              id: '#Cocoa'
              item_data:
                name: Cocoa
                description: Hot chocolate
                abbreviation: Ch
        - name: Add a category
          bodyParameters:
            idempotency_key: 4ef9a31f-b405-4df8-9c67-e6f964778fe8
            object:
              id: '#Beverages'
              type: CATEGORY
              category_data:
                name: Beverages
  /v2/catalog/object/{object_id}:
    get:
      tags:
      - Catalog
      summary: RetrieveCatalogObject
      description: |-
        Returns a single [CatalogItem](#type-catalogitem) as a
        [CatalogObject](#type-catalogobject) based on the provided ID. The returned
        object includes all of the relevant [CatalogItem](#type-catalogitem)
        information including: [CatalogItemVariation](#type-catalogitemvariation)
        children, references to its
        [CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of
        any [CatalogTax](#type-catalogtax) objects that apply to it.
      operationId: RetrieveCatalogObject
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Retrieve catalog object
          pathParameters:
            object_id: W62UWFY35CWMYGVWK6TWJDNI
        - name: Retrieve catalog object and include related objects
          pathParameters:
            object_id: W62UWFY35CWMYGVWK6TWJDNI
          queryParameters:
            include_related_objects: true
    delete:
      tags:
      - Catalog
      summary: DeleteCatalogObject
      description: |-
        Deletes a single [CatalogObject](#type-catalogobject) based on the
        provided ID and returns the set of successfully deleted IDs in the response.
        Deletion is a cascading event such that all children of the targeted object
        are also deleted. For example, deleting a [CatalogItem](#type-catalogitem)
        will also delete all of its
        [CatalogItemVariation](#type-catalogitemvariation) children.
      operationId: DeleteCatalogObject
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Delete a catalog object
          pathParameters:
            object_id: 7SB3ZQYJ5GDMVFL7JK46JCHT
  /v2/catalog/search:
    post:
      tags:
      - Catalog
      summary: SearchCatalogObjects
      description: "Searches for [CatalogObject](#type-CatalogObject) of any types\
        \ against supported search attribute values, \nexcluding custom attribute\
        \ values on items or item variations, against one or more of the specified\
        \ query expressions, \n\nThis (`SearchCatalogObjects`) endpoint differs from\
        \ the [SearchCatalogItems](#endpoint-Catalog-SearchCatalogItems)\nendpoint\
        \ in the following aspects:\n\n- `SearchCatalogItems` can only search for\
        \ items or item variations, whereas `SearchCatalogObjects` can search for\
        \ any type of catalog objects.\n- `SearchCatalogItems` supports the custom\
        \ attribute query filters to return items or item variations that contain\
        \ custom attribute values, where `SearchCatalogObjects` does not.\n- `SearchCatalogItems`\
        \ does not support the `include_deleted_objects` filter to search for deleted\
        \ items or item variations, whereas `SearchCatalogObjects` does.\n- The both\
        \ endpoints have different call conventions, including the query filter formats."
      operationId: SearchCatalogObjects
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Search for catalog objects by name
          bodyParameters:
            object_types:
            - ITEM
            query:
              prefix_query:
                attribute_name: name
                attribute_prefix: tea
            limit: 100
  /v2/catalog/search-catalog-items:
    post:
      tags:
      - Catalog
      summary: SearchCatalogItems
      description: "Searches for catalog items or item variations by matching supported\
        \ search attribute values, including\ncustom attribute values, against one\
        \ or more of the specified query expressions, \n\nThis (`SearchCatalogItems`)\
        \ endpoint differs from the [SearchCatalogObjects](#endpoint-Catalog-SearchCatalogObjects)\n\
        endpoint in the following aspects:\n\n- `SearchCatalogItems` can only search\
        \ for items or item variations, whereas `SearchCatalogObjects` can search\
        \ for any type of catalog objects.\n- `SearchCatalogItems` supports the custom\
        \ attribute query filters to return items or item variations that contain\
        \ custom attribute values, where `SearchCatalogObjects` does not.\n- `SearchCatalogItems`\
        \ does not support the `include_deleted_objects` filter to search for deleted\
        \ items or item variations, whereas `SearchCatalogObjects` does.\n- The both\
        \ endpoints use different call conventions, including the query filter formats."
      operationId: SearchCatalogItems
      security:
      - oauth2:
        - ITEMS_READ
      x-release-status: BETA
      x-example-scenarios:
        scenarios:
        - name: Search for a catalog item using filters
          bodyParams:
            sort_order: ASC
            product_types:
            - REGULAR
            category_ids:
            - WINE_CATEGORY_ID
            enabled_location_ids:
            - ATL_LOCATION_ID
            text_filter: red
            custom_attribute_filters:
            - custom_attribute_definition_id: VEGAN_DEFINITION_ID
              bool_filter: true
            - custom_attribute_definition_id: BRAND_DEFINITION_ID
              string_filter: Dark Horse
            - key: VINTAGE
              number_filter:
                min: 2017
                max: 2018
            - custom_attribute_definition_id: VARIETAL_DEFINITION_ID
              selection_ids_filter: MERLOT_SELECTION_ID
            stock_levels:
            - OUT
            - LOW
            limit: 100
  /v2/catalog/update-item-modifier-lists:
    post:
      tags:
      - Catalog
      summary: UpdateItemModifierLists
      description: |-
        Updates the [CatalogModifierList](#type-catalogmodifierlist) objects
        that apply to the targeted [CatalogItem](#type-catalogitem) without having
        to perform an upsert on the entire item.
      operationId: UpdateItemModifierLists
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Update modifier lists for a list of items
          bodyParameters:
            item_ids:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            modifier_lists_to_enable:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            modifier_lists_to_disable:
            - 7WRC16CJZDVLSNDQ35PP6YAD
  /v2/catalog/update-item-taxes:
    post:
      tags:
      - Catalog
      summary: UpdateItemTaxes
      description: |-
        Updates the [CatalogTax](#type-catalogtax) objects that apply to the
        targeted [CatalogItem](#type-catalogitem) without having to perform an
        upsert on the entire item.
      operationId: UpdateItemTaxes
      security:
      - oauth2:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-example-scenarios:
        scenarios:
        - name: Update taxes for a list of items
          bodyParameters:
            item_ids:
            - H42BRLUJ5KTZTTMPVSLFAACQ
            - 2JXOBJIHCWBQ4NZ3RIXQGJA6
            taxes_to_enable:
            - 4WRCNHCJZDVLSNDQ35PP6YAD
            taxes_to_disable:
            - AQCEGCEBBQONINDOHRGZISEX
  /v2/customers:
    get:
      tags:
      - Customers
      summary: ListCustomers
      description: "Lists customer profiles associated with a Square account.\n\n\
        Under normal operating conditions, newly created or updated customer profiles\
        \ become available \nfor the listing operation in well under 30 seconds. Occasionally,\
        \ propagation of the new or updated \nprofiles can take closer to one minute\
        \ or longer, espeically during network incidents and outages."
      operationId: ListCustomers
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
    post:
      tags:
      - Customers
      summary: CreateCustomer
      description: |-
        Creates a new customer for a business, which can have associated cards on file.

        You must provide __at least one__ of the following values in your request to this
        endpoint:

        - `given_name`
        - `family_name`
        - `company_name`
        - `email_address`
        - `phone_number`
      operationId: CreateCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
  /v2/customers/groups:
    get:
      tags:
      - CustomerGroups
      summary: ListCustomerGroups
      description: Retrieves the list of customer groups of a business.
      operationId: ListCustomerGroups
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: BETA
    post:
      tags:
      - CustomerGroups
      summary: CreateCustomerGroup
      description: "Creates a new customer group for a business. \n\nThe request must\
        \ include the `name` value of the group."
      operationId: CreateCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: BETA
  /v2/customers/groups/{group_id}:
    get:
      tags:
      - CustomerGroups
      summary: RetrieveCustomerGroup
      description: Retrieves a specific customer group as identified by the `group_id`
        value.
      operationId: RetrieveCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: BETA
    put:
      tags:
      - CustomerGroups
      summary: UpdateCustomerGroup
      description: Updates a customer group as identified by the `group_id` value.
      operationId: UpdateCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
        - CUSTOMERS_READ
      x-release-status: BETA
    delete:
      tags:
      - CustomerGroups
      summary: DeleteCustomerGroup
      description: Deletes a customer group as identified by the `group_id` value.
      operationId: DeleteCustomerGroup
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: BETA
  /v2/customers/search:
    post:
      tags:
      - Customers
      summary: SearchCustomers
      description: "Searches the customer profiles associated with a Square account\
        \ using \none or more supported query filters. \n\nCalling `SearchCustomers`\
        \ without any explicit query filter returns all\ncustomer profiles ordered\
        \ alphabetically based on `given_name` and\n`family_name`.\n\nUnder normal\
        \ operating conditions, newly created or updated customer profiles become\
        \ available \nfor the search operation in well under 30 seconds. Occasionally,\
        \ propagation of the new or updated \nprofiles can take closer to one minute\
        \ or longer, espeically during network incidents and outages."
      operationId: SearchCustomers
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
  /v2/customers/segments:
    get:
      tags:
      - CustomerSegments
      summary: ListCustomerSegments
      description: Retrieves the list of customer segments of a business.
      operationId: ListCustomerSegments
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: BETA
  /v2/customers/segments/{segment_id}:
    get:
      tags:
      - CustomerSegments
      summary: RetrieveCustomerSegment
      description: Retrieves a specific customer segment as identified by the `segment_id`
        value.
      operationId: RetrieveCustomerSegment
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: BETA
  /v2/customers/{customer_id}:
    get:
      tags:
      - Customers
      summary: RetrieveCustomer
      description: Returns details for a single customer.
      operationId: RetrieveCustomer
      security:
      - oauth2:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
    put:
      tags:
      - Customers
      summary: UpdateCustomer
      description: |-
        Updates the details of an existing customer. When two profiles are merged
        into a single profile, that profile is assigned a new `customer_id`. You must use
        the new `customer_id` to update merged profiles.

        You cannot edit a customer's cards on file with this endpoint. To make changes
        to a card on file, you must delete the existing card on file with the
        [DeleteCustomerCard](#endpoint-deletecustomercard) endpoint, then create a new one with the
        [CreateCustomerCard](#endpoint-createcustomercard) endpoint.
      operationId: UpdateCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
    delete:
      tags:
      - Customers
      summary: DeleteCustomer
      description: |-
        Deletes a customer from a business, along with any linked cards on file. When two profiles
        are merged into a single profile, that profile is assigned a new `customer_id`. You must use the
        new `customer_id` to delete merged profiles.
      operationId: DeleteCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
  /v2/customers/{customer_id}/cards:
    post:
      tags:
      - Customers
      summary: CreateCustomerCard
      description: |-
        Adds a card on file to an existing customer.

        As with charges, calls to `CreateCustomerCard` are idempotent. Multiple
        calls with the same card nonce return the same card record that was created
        with the provided nonce during the _first_ call.
      operationId: CreateCustomerCard
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-endpoint-errors:
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: INVALID_CARD
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EXPIRATION
      - error-code: UNSUPPORTED_ENTRY_METHOD
      - error-code: VERIFY_AVS_FAILURE
      - error-code: VERIFY_CVV_FAILURE
  /v2/customers/{customer_id}/cards/{card_id}:
    delete:
      tags:
      - Customers
      summary: DeleteCustomerCard
      description: Removes a card on file from a customer.
      operationId: DeleteCustomerCard
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
  /v2/customers/{customer_id}/groups/{group_id}:
    put:
      tags:
      - Customers
      summary: AddGroupToCustomer
      description: "Adds a group membership to a customer. \n\nThe customer is identified\
        \ by the `customer_id` value \nand the customer group is identified by the\
        \ `group_id` value."
      operationId: AddGroupToCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: BETA
    delete:
      tags:
      - Customers
      summary: RemoveGroupFromCustomer
      description: "Removes a group membership from a customer. \n\nThe customer is\
        \ identified by the `customer_id` value \nand the customer group is identified\
        \ by the `group_id` value."
      operationId: RemoveGroupFromCustomer
      security:
      - oauth2:
        - CUSTOMERS_WRITE
      x-release-status: BETA
  /v2/devices/codes:
    get:
      tags:
      - Devices
      summary: ListDeviceCodes
      description: Lists all DeviceCodes associated with the merchant.
      operationId: ListDeviceCodes
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: INVALID_CURSOR
      - error-code: BAD_REQUEST
    post:
      tags:
      - Devices
      summary: CreateDeviceCode
      description: |-
        Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected
        terminal mode.
      operationId: CreateDeviceCode
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: IDEMPOTENCY_KEY_REUSED
      - error-code: INVALID_VALUE
      - error-code: UNAUTHORIZED
  /v2/devices/codes/{id}:
    get:
      tags:
      - Devices
      summary: GetDeviceCode
      description: Retrieves DeviceCode with the associated ID.
      operationId: GetDeviceCode
      security:
      - oauth2:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
      - error-code: UNAUTHORIZED
  /v2/disputes:
    get:
      tags:
      - Disputes
      summary: ListDisputes
      description: |-
        Returns a list of disputes associated
        with a particular account.
      operationId: ListDisputes
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
  /v2/disputes/{dispute_id}:
    get:
      tags:
      - Disputes
      summary: RetrieveDispute
      description: Returns details of a specific dispute.
      operationId: RetrieveDispute
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
  /v2/disputes/{dispute_id}/accept:
    post:
      tags:
      - Disputes
      summary: AcceptDispute
      description: |-
        Accepts loss on a dispute. Square returns
        the disputed amount to the cardholder and updates the
        dispute state to ACCEPTED.

        Square debits the disputed amount from the seller’s Square
        account. If the Square account balance does not have
        sufficient funds, Square debits the associated bank account.
      operationId: AcceptDispute
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
  /v2/disputes/{dispute_id}/evidence:
    get:
      tags:
      - Disputes
      summary: ListDisputeEvidence
      description: Returns a list of evidence associated with a dispute.
      operationId: ListDisputeEvidence
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
  /v2/disputes/{dispute_id}/evidence/{evidence_id}:
    get:
      tags:
      - Disputes
      summary: RetrieveDisputeEvidence
      description: |-
        Returns the specific evidence metadata associated with a specific dispute.

        You must maintain a copy of the evidence you upload if you want to
        reference it later. You cannot download the evidence
        after you upload it.
      operationId: RetrieveDisputeEvidence
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
    delete:
      tags:
      - Disputes
      summary: RemoveDisputeEvidence
      description: |-
        Removes specified evidence from a dispute.

        Square does not send the bank any evidence that
        is removed. Also, you cannot remove evidence after
        submitting it to the bank using [SubmitEvidence](https://developer.squareup.com/docs/reference/square/disputes-api/submit-evidence).
      operationId: RemoveDisputeEvidence
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
  /v2/disputes/{dispute_id}/evidence_file:
    post:
      tags:
      - Disputes
      summary: CreateDisputeEvidenceFile
      description: |-
        Uploads a file to use as evidence in a dispute challenge. The endpoint accepts
        HTTP multipart/form-data file uploads in HEIC, HEIF, JPEG, PDF, PNG,
        and TIFF formats.
      operationId: CreateDisputeEvidenceFile
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
  /v2/disputes/{dispute_id}/evidence_text:
    post:
      tags:
      - Disputes
      summary: CreateDisputeEvidenceText
      description: Uploads text to use as evidence for a dispute challenge.
      operationId: CreateDisputeEvidenceText
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
  /v2/disputes/{dispute_id}/submit-evidence:
    post:
      tags:
      - Disputes
      summary: SubmitEvidence
      description: |-
        Submits evidence to the cardholder's bank.

        Before submitting evidence, Square compiles all available evidence. This includes
        evidence uploaded using the
        [CreateDisputeEvidenceFile](https://developer.squareup.com/docs/reference/square/disputes-api/create-dispute-evidence-file) and
        [CreateDisputeEvidenceText](https://developer.squareup.com/docs/reference/square/disputes-api/create-dispute-evidence-text) endpoints,
        and evidence automatically provided by Square, when
        available.
      operationId: SubmitEvidence
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
  /v2/employees:
    get:
      tags:
      - Employees
      summary: ListEmployees
      operationId: ListEmployees
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: SearchTeamMembers
        guideUrl: https://developer.squareup.com/docs/team/migrate-from-v2-employees
  /v2/employees/{id}:
    get:
      tags:
      - Employees
      summary: RetrieveEmployee
      operationId: RetrieveEmployee
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: RetrieveTeamMember
        guideUrl: https://developer.squareup.com/docs/team/migrate-from-v2-employees
  /v2/inventory/adjustment/{adjustment_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryAdjustment
      description: |-
        Returns the [InventoryAdjustment](#type-inventoryadjustment) object
        with the provided `adjustment_id`.
      operationId: RetrieveInventoryAdjustment
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/inventory/batch-change:
    post:
      tags:
      - Inventory
      summary: BatchChangeInventory
      description: |-
        Applies adjustments and counts to the provided item quantities.

        On success: returns the current calculated counts for all objects
        referenced in the request.
        On failure: returns a list of related errors.
      operationId: BatchChangeInventory
      security:
      - oauth2:
        - INVENTORY_WRITE
      x-release-status: PUBLIC
  /v2/inventory/batch-retrieve-changes:
    post:
      tags:
      - Inventory
      summary: BatchRetrieveInventoryChanges
      description: |-
        Returns historical physical counts and adjustments based on the
        provided filter criteria.

        Results are paginated and sorted in ascending order according their
        `occurred_at` timestamp (oldest first).

        BatchRetrieveInventoryChanges is a catch-all query endpoint for queries
        that cannot be handled by other, simpler endpoints.
      operationId: BatchRetrieveInventoryChanges
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/inventory/batch-retrieve-counts:
    post:
      tags:
      - Inventory
      summary: BatchRetrieveInventoryCounts
      description: |-
        Returns current counts for the provided
        [CatalogObject](#type-catalogobject)s at the requested
        [Location](#type-location)s.

        Results are paginated and sorted in descending order according to their
        `calculated_at` timestamp (newest first).

        When `updated_after` is specified, only counts that have changed since that
        time (based on the server timestamp for the most recent change) are
        returned. This allows clients to perform a "sync" operation, for example
        in response to receiving a Webhook notification.
      operationId: BatchRetrieveInventoryCounts
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/inventory/physical-count/{physical_count_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryPhysicalCount
      description: |-
        Returns the [InventoryPhysicalCount](#type-inventoryphysicalcount)
        object with the provided `physical_count_id`.
      operationId: RetrieveInventoryPhysicalCount
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/inventory/{catalog_object_id}:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryCount
      description: |-
        Retrieves the current calculated stock count for a given
        [CatalogObject](#type-catalogobject) at a given set of
        [Location](#type-location)s. Responses are paginated and unsorted.
        For more sophisticated queries, use a batch endpoint.
      operationId: RetrieveInventoryCount
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/inventory/{catalog_object_id}/changes:
    get:
      tags:
      - Inventory
      summary: RetrieveInventoryChanges
      description: "Returns a set of physical counts and inventory adjustments for\
        \ the\nprovided [CatalogObject](#type-catalogobject) at the requested\n[Location](#type-location)s.\n\
        \nResults are paginated and sorted in descending order according to their\n\
        `occurred_at` timestamp (newest first).\n\nThere are no limits on how far\
        \ back the caller can page. This endpoint can be \nused to display recent\
        \ changes for a specific item. For more\nsophisticated queries, use a batch\
        \ endpoint."
      operationId: RetrieveInventoryChanges
      security:
      - oauth2:
        - INVENTORY_READ
      x-release-status: PUBLIC
  /v2/invoices:
    get:
      tags:
      - Invoices
      summary: ListInvoices
      description: "Returns a list of invoices for a given location. The response\
        \ \nis paginated. If truncated, the response includes a `cursor` that you\
        \    \nuse in a subsequent request to fetch the next set of invoices."
      operationId: ListInvoices
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: BETA
    post:
      tags:
      - Invoices
      summary: CreateInvoice
      description: "Creates a draft [invoice](#type-invoice) \nfor an order created\
        \ using the Orders API.\n\nA draft invoice remains in your account and no\
        \ action is taken. \nYou must publish the invoice before Square can process\
        \ it (send it to the customer's email address or charge the customer’s card\
        \ on file)."
      operationId: CreateInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
  /v2/invoices/search:
    post:
      tags:
      - Invoices
      summary: SearchInvoices
      description: "Searches for invoices from a location specified in \nthe filter.\
        \ You can optionally specify customers in the filter for whom to \nretrieve\
        \ invoices. In the current implementation, you can only specify one location\
        \ and \noptionally one customer.\n\nThe response is paginated. If truncated,\
        \ the response includes a `cursor` \nthat you use in a subsequent request\
        \ to fetch the next set of invoices."
      operationId: SearchInvoices
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: BETA
  /v2/invoices/{invoice_id}:
    get:
      tags:
      - Invoices
      summary: GetInvoice
      description: Retrieves an invoice by invoice ID.
      operationId: GetInvoice
      security:
      - oauth2:
        - INVOICES_READ
      x-release-status: BETA
    put:
      tags:
      - Invoices
      summary: UpdateInvoice
      description: "Updates an invoice by modifying field values, clearing field values,\
        \ or both \nas specified in the request. \nThere are no restrictions to updating\
        \ an invoice in a draft state. \nHowever, there are guidelines for updating\
        \ a published invoice."
      operationId: UpdateInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
    delete:
      tags:
      - Invoices
      summary: DeleteInvoice
      description: "Deletes the specified invoice. When an invoice is deleted, the\
        \ \nassociated Order status changes to CANCELED. You can only delete a draft\
        \ \ninvoice (you cannot delete an invoice scheduled for publication, or a\
        \ \npublished invoice)."
      operationId: DeleteInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
  /v2/invoices/{invoice_id}/cancel:
    post:
      tags:
      - Invoices
      summary: CancelInvoice
      description: "Cancels an invoice. The seller cannot collect payments for \n\
        the canceled invoice.\n\nYou cannot cancel an invoice in a terminal state:\
        \ `PAID`, `REFUNDED`, `CANCELED`, or `FAILED`."
      operationId: CancelInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
  /v2/invoices/{invoice_id}/publish:
    post:
      tags:
      - Invoices
      summary: PublishInvoice
      description: "Publishes the specified draft invoice. \n\nAfter an invoice is\
        \ published, Square \nfollows up based on the invoice configuration. For example,\
        \ Square \nsends the invoice to the customer's email address, charges the\
        \ customer's card on file, or does \nnothing. Square also makes the invoice\
        \ available on a Square-hosted invoice page. \n\nThe invoice `status` also\
        \ changes from `DRAFT` to a status \nbased on the invoice configuration. For\
        \ example, the status changes to `UNPAID` if \nSquare emails the invoice or\
        \ `PARTIALLY_PAID` if Square charge a card on file for a portion of the \n\
        invoice amount)."
      operationId: PublishInvoice
      security:
      - oauth2:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: CARD_DECLINED
      - error-code: INVALID_CARD
  /v2/labor/break-types:
    get:
      tags:
      - Labor
      summary: ListBreakTypes
      description: Returns a paginated list of `BreakType` instances for a business.
      operationId: ListBreakTypes
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
    post:
      tags:
      - Labor
      summary: CreateBreakType
      description: |-
        Creates a new `BreakType`.

        A `BreakType` is a template for creating `Break` objects.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `break_name`
        - `expected_duration`
        - `is_paid`

        You can only have 3 `BreakType` instances per location. If you attempt to add a 4th
        `BreakType` for a location, an `INVALID_REQUEST_ERROR` "Exceeded limit of 3 breaks per location."
        is returned.
      operationId: CreateBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
  /v2/labor/break-types/{id}:
    get:
      tags:
      - Labor
      summary: GetBreakType
      description: Returns a single `BreakType` specified by id.
      operationId: GetBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
    put:
      tags:
      - Labor
      summary: UpdateBreakType
      description: Updates an existing `BreakType`.
      operationId: UpdateBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
    delete:
      tags:
      - Labor
      summary: DeleteBreakType
      description: |-
        Deletes an existing `BreakType`.

        A `BreakType` can be deleted even if it is referenced from a `Shift`.
      operationId: DeleteBreakType
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
  /v2/labor/employee-wages:
    get:
      tags:
      - Labor
      summary: ListEmployeeWages
      description: Returns a paginated list of `EmployeeWage` instances for a business.
      operationId: ListEmployeeWages
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: ListTeamMemberWages
        guideUrl: https://developer.squareup.com/docs/labor-api/migrate-to-teams
  /v2/labor/employee-wages/{id}:
    get:
      tags:
      - Labor
      summary: GetEmployeeWage
      description: Returns a single `EmployeeWage` specified by id.
      operationId: GetEmployeeWage
      deprecated: true
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2020-08-26
        retirementDate: 2021-08-26
        replacedBy: GetTeamMemberWage
        guideUrl: https://developer.squareup.com/docs/labor-api/migrate-to-teams
  /v2/labor/shifts:
    post:
      tags:
      - Labor
      summary: CreateShift
      description: |-
        Creates a new `Shift`.

        A `Shift` represents a complete work day for a single employee.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `employee_id`
        - `start_at`

        An attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:
        - The `status` of the new `Shift` is `OPEN` and the employee has another
        shift with an `OPEN` status.
        - The `start_at` date is in the future
        - the `start_at` or `end_at` overlaps another shift for the same employee
        - If `Break`s are set in the request, a break `start_at`
        must not be before the `Shift.start_at`. A break `end_at` must not be after
        the `Shift.end_at`
      operationId: CreateShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
  /v2/labor/shifts/search:
    post:
      tags:
      - Labor
      summary: SearchShifts
      description: |-
        Returns a paginated list of `Shift` records for a business.
        The list to be returned can be filtered by:
        - Location IDs **and**
        - employee IDs **and**
        - shift status (`OPEN`, `CLOSED`) **and**
        - shift start **and**
        - shift end **and**
        - work day details

        The list can be sorted by:
        - `start_at`
        - `end_at`
        - `created_at`
        - `updated_at`
      operationId: SearchShifts
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: PUBLIC
  /v2/labor/shifts/{id}:
    get:
      tags:
      - Labor
      summary: GetShift
      description: Returns a single `Shift` specified by id.
      operationId: GetShift
      security:
      - oauth2:
        - TIMECARDS_READ
      x-release-status: PUBLIC
    put:
      tags:
      - Labor
      summary: UpdateShift
      description: |-
        Updates an existing `Shift`.

        When adding a `Break` to a `Shift`, any earlier `Breaks` in the `Shift` have
        the `end_at` property set to a valid RFC-3339 datetime string.

        When closing a `Shift`, all `Break` instances in the shift must be complete with `end_at`
        set on each `Break`.
      operationId: UpdateShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
        - TIMECARDS_READ
      x-release-status: PUBLIC
    delete:
      tags:
      - Labor
      summary: DeleteShift
      description: Deletes a `Shift`.
      operationId: DeleteShift
      security:
      - oauth2:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
  /v2/labor/team-member-wages:
    get:
      tags:
      - Labor
      summary: ListTeamMemberWages
      description: Returns a paginated list of `TeamMemberWage` instances for a business.
      operationId: ListTeamMemberWages
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
  /v2/labor/team-member-wages/{id}:
    get:
      tags:
      - Labor
      summary: GetTeamMemberWage
      description: Returns a single `TeamMemberWage` specified by id.
      operationId: GetTeamMemberWage
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
  /v2/labor/workweek-configs:
    get:
      tags:
      - Labor
      summary: ListWorkweekConfigs
      description: Returns a list of `WorkweekConfig` instances for a business.
      operationId: ListWorkweekConfigs
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
  /v2/labor/workweek-configs/{id}:
    put:
      tags:
      - Labor
      summary: UpdateWorkweekConfig
      description: Updates a `WorkweekConfig`.
      operationId: UpdateWorkweekConfig
      security:
      - oauth2:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
  /v2/locations:
    get:
      tags:
      - Locations
      summary: ListLocations
      description: |-
        Provides information of all locations of a business.

        Most other Connect API endpoints have a required `location_id` path parameter.
        The `id` field of the [`Location`](#type-location) objects returned by this
        endpoint correspond to that `location_id` parameter.
      operationId: ListLocations
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-unitTests:
      - request:
          method: GET
          uri: /v2/locations
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          statusCode: "200"
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: ListLocations
    post:
      tags:
      - Locations
      summary: CreateLocation
      description: |-
        Creates a location.
        For more information about locations, see [Locations API Overview](https://developer.squareup.com/docs/locations-api).
      operationId: CreateLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
  /v2/locations/{location_id}:
    get:
      tags:
      - Locations
      summary: RetrieveLocation
      description: "Retrieves details of a location. You can specify \"main\" \nas\
        \ the location ID to retrieve details of the \nmain location. For more information,\
        \ \nsee [Locations API Overview](https://developer.squareup.com/docs/docs/locations-api)."
      operationId: RetrieveLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-endpoint-errors:
      - error-code: NOT_FOUND
    put:
      tags:
      - Locations
      summary: UpdateLocation
      description: Updates a location.
      operationId: UpdateLocation
      security:
      - oauth2:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
  /v2/locations/{location_id}/additional-recipient-receivable-refunds:
    get:
      tags:
      - Reporting
      summary: ListAdditionalRecipientReceivableRefunds
      description: |-
        Returns a list of refunded transactions (across all possible originating locations) relating to monies
        credited to the provided location ID by another Square account using the `additional_recipients` field in a transaction.

        Max results per [page](#paginatingresults): 50
      operationId: ListAdditionalRecipientReceivableRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: RETIRED
  /v2/locations/{location_id}/additional-recipient-receivables:
    get:
      tags:
      - Reporting
      summary: ListAdditionalRecipientReceivables
      description: |-
        Returns a list of receivables (across all possible sending locations) representing monies credited
        to the provided location ID by another Square account using the `additional_recipients` field in a transaction.

        Max results per [page](#paginatingresults): 50
      operationId: ListAdditionalRecipientReceivables
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: RETIRED
  /v2/locations/{location_id}/checkouts:
    post:
      tags:
      - Checkout
      summary: CreateCheckout
      description: |-
        Links a `checkoutId` to a `checkout_page_url` that customers will
        be directed to in order to provide their payment information using a
        payment processing workflow hosted on connect.squareup.com.
      operationId: CreateCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: PUBLIC
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: ORDER_EXPIRED
  /v2/locations/{location_id}/refunds:
    get:
      tags:
      - Transactions
      summary: ListRefunds
      description: |-
        Lists refunds for one of a business's locations.

        In addition to full or partial tender refunds processed through Square APIs,
        refunds may result from itemized returns or exchanges through Square's
        Point of Sale applications.

        Refunds with a `status` of `PENDING` are not currently included in this
        endpoint's response.

        Max results per [page](#paginatingresults): 50
      operationId: ListRefunds
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: SearchOrders
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
  /v2/locations/{location_id}/transactions:
    get:
      tags:
      - Transactions
      summary: ListTransactions
      description: |-
        Lists transactions for a particular location.

        Transactions include payment information from sales and exchanges and refund
        information from returns and exchanges.

        Max results per [page](#paginatingresults): 50
      operationId: ListTransactions
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: SearchOrders
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
    post:
      tags:
      - Transactions
      summary: Charge
      description: |-
        Charges a card represented by a card nonce or a customer's card on file.

        Your request to this endpoint must include _either_:

        - A value for the `card_nonce` parameter (to charge a card nonce generated
        with the `SqPaymentForm`)
        - Values for the `customer_card_id` and `customer_id` parameters (to charge
        a customer's card on file)

        In order for an eCommerce payment to potentially qualify for
        [Square chargeback protection](https://squareup.com/help/article/5394), you
        _must_ provide values for the following parameters in your request:

        - `buyer_email_address`
        - At least one of `billing_address` or `shipping_address`

        When this response is returned, the amount of Square's processing fee might not yet be
        calculated. To obtain the processing fee, wait about ten seconds and call
        [RetrieveTransaction](#endpoint-retrievetransaction). See the `processing_fee_money`
        field of each [Tender included](#type-tender) in the transaction.
      operationId: Charge
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: CreatePayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: CARD_DECLINED
      - error-code: CARD_DECLINED_CALL_ISSUER
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: INVALID_CARD
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EXPIRATION
      - error-code: ONE_INSTRUMENT_EXPECTED
      - error-code: ORDER_ALREADY_USED
      - error-code: ORDER_EXPIRED
      - error-code: VERIFY_AVS_FAILURE
      - error-code: VERIFY_CVV_FAILURE
  /v2/locations/{location_id}/transactions/{transaction_id}:
    get:
      tags:
      - Transactions
      summary: RetrieveTransaction
      description: Retrieves details for a single transaction.
      operationId: RetrieveTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: BatchRetrieveOrders
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
  /v2/locations/{location_id}/transactions/{transaction_id}/capture:
    post:
      tags:
      - Transactions
      summary: CaptureTransaction
      description: |-
        Captures a transaction that was created with the [Charge](#endpoint-charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: CaptureTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: CompletePayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: DELAYED_TRANSACTION_CANCELED
      - error-code: DELAYED_TRANSACTION_EXPIRED
  /v2/locations/{location_id}/transactions/{transaction_id}/refund:
    post:
      tags:
      - Transactions
      summary: CreateRefund
      description: |-
        Initiates a refund for a previously charged tender.

        You must issue a refund within 120 days of the associated payment. See
        [this article](https://squareup.com/help/us/en/article/5060) for more information
        on refund behavior.

        NOTE: Card-present transactions with Interac credit cards **cannot be
        refunded using the Connect API**. Interac transactions must refunded
        in-person (e.g., dipping the card using POS app).
      operationId: CreateRefund
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: RefundPayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: PAYMENT_NOT_REFUNDABLE
      - error-code: REFUND_AMOUNT_INVALID
  /v2/locations/{location_id}/transactions/{transaction_id}/void:
    post:
      tags:
      - Transactions
      summary: VoidTransaction
      description: |-
        Cancels a transaction that was created with the [Charge](#endpoint-charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: VoidTransaction
      deprecated: true
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-deprecation:
        deprecationDate: 2019-08-15
        retirementDate: 2021-09-01
        replacedBy: CancelPayment
        guideUrl: https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api
      x-endpoint-errors:
      - error-code: DELAYED_TRANSACTION_CAPTURED
      - error-code: DELAYED_TRANSACTION_EXPIRED
  /v2/loyalty/accounts:
    post:
      tags:
      - Loyalty
      summary: CreateLoyaltyAccount
      description: "Creates a loyalty account. For more information, see \n[Create\
        \ a loyalty account](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-overview-create-account)."
      operationId: CreateLoyaltyAccount
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: INVALID_PHONE_NUMBER
  /v2/loyalty/accounts/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyAccounts
      description: "Searches for loyalty accounts. \nIn the current implementation,\
        \ you can search for a loyalty account using the phone number associated with\
        \ the account. \nIf no phone number is provided, all loyalty accounts are\
        \ returned."
      operationId: SearchLoyaltyAccounts
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/accounts/{account_id}:
    get:
      tags:
      - Loyalty
      summary: RetrieveLoyaltyAccount
      description: Retrieves a loyalty account.
      operationId: RetrieveLoyaltyAccount
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/accounts/{account_id}/accumulate:
    post:
      tags:
      - Loyalty
      summary: AccumulateLoyaltyPoints
      description: "Adds points to a loyalty account.\n\n- If you are using the Orders\
        \ API to manage orders, you only provide the `order_id`. \nThe endpoint reads\
        \ the order to compute points to add to the buyer's account.\n- If you are\
        \ not using the Orders API to manage orders, \nyou first perform a client-side\
        \ computation to compute the points.  \nFor spend-based and visit-based programs,\
        \ you can call \n`CalculateLoyaltyPoints` to compute the points. For more\
        \ information, \nsee [Loyalty Program Overview](https://developer.squareup.com/docs/docs/loyalty/overview).\
        \ \nYou then provide the points in a request to this endpoint. \n\nFor more\
        \ information, see [Accumulate points](https://developer.squareup.com/docs/docs/loyalty-api/overview/#accumulate-points)."
      operationId: AccumulateLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
  /v2/loyalty/accounts/{account_id}/adjust:
    post:
      tags:
      - Loyalty
      summary: AdjustLoyaltyPoints
      description: "Adds points to or subtracts points from a buyer's account. \n\n\
        Use this endpoint only when you need to manually adjust points. Otherwise,\
        \ in your application flow, you call \n[AccumulateLoyaltyPoints](https://developer.squareup.com/docs/reference/square/loyalty-api/accumulate-loyalty-points)\
        \ \nto add points when a buyer pays for the purchase."
      operationId: AdjustLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
  /v2/loyalty/events/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyEvents
      description: "Searches for loyalty events.\n\nA Square loyalty program maintains\
        \ a ledger of events that occur during the lifetime of a \nbuyer's loyalty\
        \ account. Each change in the point balance \n(for example, points earned,\
        \ points redeemed, and points expired) is \nrecorded in the ledger. Using\
        \ this endpoint, you can search the ledger for events. \nFor more information,\
        \ see \n[Loyalty events](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-events)."
      operationId: SearchLoyaltyEvents
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/programs:
    get:
      tags:
      - Loyalty
      summary: ListLoyaltyPrograms
      description: "Returns a list of loyalty programs in the seller's account.\n\
        Currently, a seller can only have one loyalty program. For more information,\
        \ see \n[Loyalty Overview](https://developer.squareup.com/docs/docs/loyalty/overview).\n\
        ."
      operationId: ListLoyaltyPrograms
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/programs/{program_id}/calculate:
    post:
      tags:
      - Loyalty
      summary: CalculateLoyaltyPoints
      description: "Calculates the points a purchase earns.\n\n- If you are using\
        \ the Orders API to manage orders, you provide `order_id` in the request.\
        \ The \nendpoint calculates the points by reading the order.\n- If you are\
        \ not using the Orders API to manage orders, you provide the purchase amount\
        \ in \nthe request for the endpoint to calculate the points.\n\nAn application\
        \ might call this endpoint to show the points that a buyer can earn with the\
        \ \nspecific purchase."
      operationId: CalculateLoyaltyPoints
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/rewards:
    post:
      tags:
      - Loyalty
      summary: CreateLoyaltyReward
      description: "Creates a loyalty reward. In the process, the endpoint does following:\n\
        \n- Uses the `reward_tier_id` in the request to determine the number of points\
        \ \nto lock for this reward. \n- If the request includes `order_id`, it adds\
        \ the reward and related discount to the order. \n\nAfter a reward is created,\
        \ the points are locked and \nnot available for the buyer to redeem another\
        \ reward. \nFor more information, see \n[Loyalty rewards](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-overview-loyalty-rewards)."
      operationId: CreateLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
  /v2/loyalty/rewards/search:
    post:
      tags:
      - Loyalty
      summary: SearchLoyaltyRewards
      description: "Searches for loyalty rewards in a loyalty account. \n\nIn the\
        \ current implementation, the endpoint supports search by the reward `status`.\n\
        \nIf you know a reward ID, use the \n[RetrieveLoyaltyReward](https://developer.squareup.com/docs/reference/square/loyalty-api/retrieve-loyalty-reward)\
        \ endpoint.\n\nFor more information about loyalty rewards, see \n[Loyalty\
        \ Rewards](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-rewards)."
      operationId: SearchLoyaltyRewards
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
  /v2/loyalty/rewards/{reward_id}:
    get:
      tags:
      - Loyalty
      summary: RetrieveLoyaltyReward
      description: Retrieves a loyalty reward.
      operationId: RetrieveLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_READ
      x-release-status: BETA
    delete:
      tags:
      - Loyalty
      summary: DeleteLoyaltyReward
      description: "Deletes a loyalty reward by doing the following:\n\n- Returns\
        \ the loyalty points back to the loyalty account.\n- If an order ID was specified\
        \ when the reward was created \n(see [CreateLoyaltyReward](https://developer.squareup.com/docs/reference/square/loyalty-api/create-loyalty-reward)),\
        \ \nit updates the order by removing the reward and related \ndiscounts.\n\
        \nYou cannot delete a reward that has reached the terminal state (REDEEMED).\
        \ \nFor more information, see \n[Loyalty rewards](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-overview-loyalty-rewards)."
      operationId: DeleteLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
  /v2/loyalty/rewards/{reward_id}/redeem:
    post:
      tags:
      - Loyalty
      summary: RedeemLoyaltyReward
      description: "Redeems a loyalty reward.\n\nThe endpoint sets the reward to the\
        \ terminal state (`REDEEMED`). \n\nIf you are using your own order processing\
        \ system (not using the \nOrders API), you call this endpoint after the buyer\
        \ paid for the \npurchase.\n\nAfter the reward reaches the terminal state,\
        \ it cannot be deleted. \nIn other words, points used for the reward cannot\
        \ be returned \nto the account.\n\nFor more information, see \n[Loyalty rewards](https://developer.squareup.com/docs/docs/loyalty-api/overview/#loyalty-overview-loyalty-rewards)."
      operationId: RedeemLoyaltyReward
      security:
      - oauth2:
        - LOYALTY_WRITE
      x-release-status: BETA
  /v2/merchants:
    get:
      tags:
      - Merchants
      summary: ListMerchants
      description: |-
        Returns `Merchant` information for a given access token.

        If you don't know a `Merchant` ID, you can use this endpoint to retrieve the merchant ID for an access token.
        You can specify your personal access token to get your own merchant information or specify an OAuth token
        to get the information for the  merchant that granted you access.

        If you know the merchant ID, you can also use the [RetrieveMerchant](#endpoint-merchants-retrievemerchant)
        endpoint to get the merchant information.
      operationId: ListMerchants
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
  /v2/merchants/{merchant_id}:
    get:
      tags:
      - Merchants
      summary: RetrieveMerchant
      description: Retrieve a `Merchant` object for the given `merchant_id`.
      operationId: RetrieveMerchant
      security:
      - oauth2:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
  /v2/orders:
    post:
      tags:
      - Orders
      summary: CreateOrder
      description: |-
        Creates a new [Order](#type-order) which can include information on products for
        purchase and settings to apply to the purchase.

        To pay for a created order, please refer to the [Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders)
        guide.

        You can modify open orders using the [UpdateOrder](#endpoint-orders-updateorder) endpoint.
      operationId: CreateOrder
      security:
      - oauth2:
        - ORDERS_WRITE
      x-release-status: PUBLIC
  /v2/orders/batch-retrieve:
    post:
      tags:
      - Orders
      summary: BatchRetrieveOrders
      description: |-
        Retrieves a set of [Order](#type-order)s by their IDs.

        If a given Order ID does not exist, the ID is ignored instead of generating an error.
      operationId: BatchRetrieveOrders
      security:
      - oauth2:
        - ORDERS_READ
      x-release-status: PUBLIC
  /v2/orders/calculate:
    post:
      tags:
      - Orders
      summary: CalculateOrder
      description: Calculates an [Order](#type-order).
      operationId: CalculateOrder
      security:
      - oauth2: []
      x-release-status: BETA
  /v2/orders/search:
    post:
      tags:
      - Orders
      summary: SearchOrders
      description: |-
        Search all orders for one or more locations. Orders include all sales,
        returns, and exchanges regardless of how or when they entered the Square
        Ecosystem (e.g. Point of Sale, Invoices, Connect APIs, etc).

        SearchOrders requests need to specify which locations to search and define a
        [`SearchOrdersQuery`](#type-searchordersquery) object which controls
        how to sort or filter the results. Your SearchOrdersQuery can:

          Set filter criteria.
          Set sort order.
          Determine whether to return results as complete Order objects, or as
        [OrderEntry](#type-orderentry) objects.

        Note that details for orders processed with Square Point of Sale while in
        offline mode may not be transmitted to Square for up to 72 hours. Offline
        orders have a `created_at` value that reflects the time the order was created,
        not the time it was subsequently transmitted to Square.
      operationId: SearchOrders
      security:
      - oauth2:
        - ORDERS_READ
      x-release-status: PUBLIC
  /v2/orders/{order_id}:
    put:
      tags:
      - Orders
      summary: UpdateOrder
      description: |-
        Updates an open [Order](#type-order) by adding, replacing, or deleting
        fields. Orders with a `COMPLETED` or `CANCELED` state cannot be updated.

        An UpdateOrder request requires the following:

        - The `order_id` in the endpoint path, identifying the order to update.
        - The latest `version` of the order to update.
        - The [sparse order](https://developer.squareup.com/docs/orders-api/manage-orders#sparse-order-objects)
        containing only the fields to update and the version the update is
        being applied to.
        - If deleting fields, the [dot notation paths](https://developer.squareup.com/docs/orders-api/manage-orders#on-dot-notation)
        identifying fields to clear.

        To pay for an order, please refer to the [Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders) guide.
      operationId: UpdateOrder
      security:
      - oauth2:
        - ORDERS_WRITE
      x-release-status: BETA
  /v2/orders/{order_id}/pay:
    post:
      tags:
      - Orders
      summary: PayOrder
      description: |-
        Pay for an [order](#type-order) using one or more approved [payments](#type-payment),
        or settle an order with a total of `0`.

        The total of the `payment_ids` listed in the request must be equal to the order
        total. Orders with a total amount of `0` can be marked as paid by specifying an empty
        array of `payment_ids` in the request.

        To be used with PayOrder, a payment must:

        - Reference the order by specifying the `order_id` when [creating the payment](#endpoint-payments-createpayment).
        Any approved payments that reference the same `order_id` not specified in the
        `payment_ids` will be canceled.
        - Be approved with [delayed capture](https://developer.squareup.com/docs/payments-api/take-payments#delayed-capture).
        Using a delayed capture payment with PayOrder will complete the approved payment.
      operationId: PayOrder
      security:
      - oauth2:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: BETA
  /v2/payments:
    get:
      tags:
      - Payments
      summary: ListPayments
      description: |-
        Retrieves a list of payments taken by the account making the request.

        Max results per page: 100
      operationId: ListPayments
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
    post:
      tags:
      - Payments
      summary: CreatePayment
      description: "Charges a payment source, for example, a card \nrepresented by\
        \ customer's card on file or a card nonce. In addition \nto the payment source,\
        \ the request must also include the \namount to accept for the payment.\n\n\
        There are several optional parameters that you can include in the request.\
        \ \nFor example, tip money, whether to autocomplete the payment, or a reference\
        \ ID\nto correlate this payment with another system. \n\nThe `PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS`\
        \ OAuth permission is required\nto enable application fees."
      operationId: CreatePayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-endpoint-errors:
      - error-code: ADDRESS_VERIFICATION_FAILURE
      - error-code: ALLOWABLE_PIN_TRIES_EXCEEDED
      - error-code: BAD_EXPIRATION
      - error-code: CARDHOLDER_INSUFFICIENT_PERMISSIONS
      - error-code: CARD_EXPIRED
      - error-code: CARD_PROCESSING_NOT_ENABLED
      - error-code: CARD_NOT_SUPPORTED
      - error-code: CARD_TOKEN_EXPIRED
      - error-code: CARD_TOKEN_USED
      - error-code: CHIP_INSERTION_REQUIRED
      - error-code: CVV_FAILURE
      - error-code: EXPIRATION_FAILURE
      - error-code: GENERIC_DECLINE
      - error-code: GIFT_CARD_AVAILABLE_AMOUNT
      - error-code: INSUFFICIENT_FUNDS
      - error-code: INSUFFICIENT_PERMISSIONS
      - error-code: INVALID_ACCOUNT
      - error-code: INVALID_CARD_DATA
      - error-code: INVALID_EMAIL_ADDRESS
      - error-code: INVALID_EXPIRATION
      - error-code: INVALID_FEES
      - error-code: INVALID_LOCATION
      - error-code: INVALID_PIN
      - error-code: INVALID_POSTAL_CODE
      - error-code: MANUALLY_ENTERED_PAYMENT_NOT_SUPPORTED
      - error-code: PAN_FAILURE
      - error-code: PAYMENT_LIMIT_EXCEEDED
      - error-code: TEMPORARY_ERROR
      - error-code: TRANSACTION_LIMIT
      - error-code: VOICE_FAILURE
  /v2/payments/cancel:
    post:
      tags:
      - Payments
      summary: CancelPaymentByIdempotencyKey
      description: |-
        Cancels (voids) a payment identified by the idempotency key that is specified in the
        request.

        Use this method when status of a CreatePayment request is unknown. For example, after you send a
        CreatePayment request a network error occurs and you don't get a response. In this case, you can
        direct Square to cancel the payment using this endpoint. In the request, you provide the same
        idempotency key that you provided in your CreatePayment request you want  to cancel. After
        cancelling the payment, you can submit your CreatePayment request again.

        Note that if no payment with the specified idempotency key is found, no action is taken, the end
        point returns successfully.
      operationId: CancelPaymentByIdempotencyKey
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
  /v2/payments/{payment_id}:
    get:
      tags:
      - Payments
      summary: GetPayment
      description: Retrieves details for a specific Payment.
      operationId: GetPayment
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
  /v2/payments/{payment_id}/cancel:
    post:
      tags:
      - Payments
      summary: CancelPayment
      description: "Cancels (voids) a payment. If you set `autocomplete` to false\
        \ when creating a payment, \nyou can cancel the payment using this endpoint."
      operationId: CancelPayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
  /v2/payments/{payment_id}/complete:
    post:
      tags:
      - Payments
      summary: CompletePayment
      description: "Completes (captures) a payment.\n\nBy default, payments are set\
        \ to complete immediately after they are created. \nIf you set autocomplete\
        \ to false when creating a payment, you can complete (capture) \nthe payment\
        \ using this endpoint."
      operationId: CompletePayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
  /v2/refunds:
    get:
      tags:
      - Refunds
      summary: ListPaymentRefunds
      description: |-
        Retrieves a list of refunds for the account making the request.

        Max results per page: 100
      operationId: ListPaymentRefunds
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
    post:
      tags:
      - Refunds
      summary: RefundPayment
      description: "Refunds a payment. You can refund the entire payment amount or\
        \ a \nportion of it."
      operationId: RefundPayment
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-endpoint-errors:
      - error-code: AMOUNT_TOO_HIGH
      - error-code: REFUND_DECLINED
  /v2/refunds/{refund_id}:
    get:
      tags:
      - Refunds
      summary: GetPaymentRefund
      description: Retrieves a specific `Refund` using the `refund_id`.
      operationId: GetPaymentRefund
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: PUBLIC
  /v2/subscriptions:
    post:
      tags:
      - Subscriptions
      summary: CreateSubscription
      description: "Creates a subscription for a customer to a subscription plan.\n\
        \nIf you provide a card on file in the request, Square charges the card for\
        \ \nthe subscription. Otherwise, Square bills an invoice to the customer's\
        \ email \naddress. The subscription starts immediately, unless the request\
        \ includes \nthe optional `start_date`. Each individual subscription is associated\
        \ with a particular location."
      operationId: CreateSubscription
      security:
      - oauth2:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
  /v2/subscriptions/search:
    post:
      tags:
      - Subscriptions
      summary: SearchSubscriptions
      description: "Searches for subscriptions. \nResults are ordered chronologically\
        \ by subscription creation date. If\nthe request specifies more than one location\
        \ ID, \nthe endpoint orders the result \nby location ID, and then by creation\
        \ date within each location. If no locations are given\nin the query, all\
        \ locations are searched.\n\nYou can also optionally specify `customer_ids`\
        \ to search by customer. \nIf left unset, all customers \nassociated with\
        \ the specified locations are returned. \nIf the request specifies customer\
        \ IDs, the endpoint orders results \nfirst by location, within location by\
        \ customer ID, and within \ncustomer by subscription creation date.\n\nFor\
        \ more information, see \n[Retrieve subscriptions](https://developer.squareup.com/docs/docs/subscriptions-api/overview#retrieve-subscriptions)."
      operationId: SearchSubscriptions
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: BETA
  /v2/subscriptions/{subscription_id}:
    get:
      tags:
      - Subscriptions
      summary: RetrieveSubscription
      description: Retrieves a subscription.
      operationId: RetrieveSubscription
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: BETA
    put:
      tags:
      - Subscriptions
      summary: UpdateSubscription
      description: "Updates a subscription. You can set, modify, and clear the \n\
        `subscription` field values."
      operationId: UpdateSubscription
      security:
      - oauth2:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: BETA
  /v2/subscriptions/{subscription_id}/cancel:
    post:
      tags:
      - Subscriptions
      summary: CancelSubscription
      description: |-
        Sets the `canceled_date` field to the end of the active billing period.
        After this date, the status changes from ACTIVE to CANCELED.
      operationId: CancelSubscription
      security:
      - oauth2:
        - SUBSCRIPTIONS_WRITE
      x-release-status: BETA
  /v2/subscriptions/{subscription_id}/events:
    get:
      tags:
      - Subscriptions
      summary: ListSubscriptionEvents
      description: |-
        Lists all events for a specific subscription.
        In the current implementation, only `START_SUBSCRIPTION` and `STOP_SUBSCRIPTION` (when the subscription was canceled) events are returned.
      operationId: ListSubscriptionEvents
      security:
      - oauth2:
        - SUBSCRIPTIONS_READ
      x-release-status: BETA
  /v2/team-members:
    post:
      tags:
      - Team
      summary: CreateTeamMember
      description: |-
        Creates a single `TeamMember` object. The `TeamMember` will be returned on successful creates.
        You must provide the following values in your request to this endpoint:
        - `first_name`
        - `last_name`
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#createteammember).
      operationId: CreateTeamMember
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v2/team-members/bulk-create:
    post:
      tags:
      - Team
      summary: BulkCreateTeamMembers
      description: |-
        Creates multiple `TeamMember` objects. The created `TeamMember` objects will be returned on successful creates.
        This process is non-transactional and will process as much of the request as is possible. If one of the creates in
        the request cannot be successfully processed, the request will NOT be marked as failed, but the body of the response
        will contain explicit error information for this particular create.

        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#bulkcreateteammembers).
      operationId: BulkCreateTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v2/team-members/bulk-update:
    post:
      tags:
      - Team
      summary: BulkUpdateTeamMembers
      description: |-
        Updates multiple `TeamMember` objects. The updated `TeamMember` objects will be returned on successful updates.
        This process is non-transactional and will process as much of the request as is possible. If one of the updates in
        the request cannot be successfully processed, the request will NOT be marked as failed, but the body of the response
        will contain explicit error information for this particular update.
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#bulkupdateteammembers).
      operationId: BulkUpdateTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v2/team-members/search:
    post:
      tags:
      - Team
      summary: SearchTeamMembers
      description: |-
        Returns a paginated list of `TeamMember` objects for a business.
        The list to be returned can be filtered by:
        - location IDs **and**
        - `is_active`
      operationId: SearchTeamMembers
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
  /v2/team-members/{team_member_id}:
    get:
      tags:
      - Team
      summary: RetrieveTeamMember
      description: |-
        Retrieve a `TeamMember` object for the given `TeamMember.id`
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#retrieveteammember).
      operationId: RetrieveTeamMember
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    put:
      tags:
      - Team
      summary: UpdateTeamMember
      description: |-
        Updates a single `TeamMember` object. The `TeamMember` will be returned on successful updates.
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#updateteammember).
      operationId: UpdateTeamMember
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v2/team-members/{team_member_id}/wage-setting:
    get:
      tags:
      - Team
      summary: RetrieveWageSetting
      description: |-
        Retrieve a `WageSetting` object for a team member specified
        by `TeamMember.id`.
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#retrievewagesetting).
      operationId: RetrieveWageSetting
      security:
      - oauth2:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
    put:
      tags:
      - Team
      summary: UpdateWageSetting
      description: |-
        Creates or updates a `WageSetting` object. The object is created if a
        `WageSetting` with the specified `team_member_id` does not exist. Otherwise,
        it fully replaces the `WageSetting` object for the team member.
        The `WageSetting` will be returned upon successful update.
        Learn about [Troubleshooting the Teams API](https://developer.squareup.com/docs/docs/team/troubleshooting#updatewagesetting).
      operationId: UpdateWageSetting
      security:
      - oauth2:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
  /v2/terminals/checkouts:
    post:
      tags:
      - Terminal
      summary: CreateTerminalCheckout
      description: Creates a new Terminal checkout request and sends it to the specified
        device to take a payment for the requested amount.
      operationId: CreateTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: IDEMPOTENCY_KEY_REUSED
      - error-code: INVALID_VALUE
      - error-code: UNAUTHORIZED
  /v2/terminals/checkouts/search:
    post:
      tags:
      - Terminal
      summary: SearchTerminalCheckouts
      description: Retrieves a filtered list of Terminal checkout requests created
        by the account making the request.
      operationId: SearchTerminalCheckouts
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: INVALID_CURSOR
      - error-code: UNKNOWN_QUERY_PARAMETER
  /v2/terminals/checkouts/{checkout_id}:
    get:
      tags:
      - Terminal
      summary: GetTerminalCheckout
      description: Retrieves a Terminal checkout request by checkout_id.
      operationId: GetTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_READ
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
  /v2/terminals/checkouts/{checkout_id}/cancel:
    post:
      tags:
      - Terminal
      summary: CancelTerminalCheckout
      description: Cancels a Terminal checkout request, if the status of the request
        permits it.
      operationId: CancelTerminalCheckout
      security:
      - oauth2:
        - PAYMENTS_WRITE
      x-release-status: BETA
      x-endpoint-errors:
      - error-code: BAD_REQUEST
      - error-code: NOT_FOUND
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          tokenUrl: https://connect.squareup.com/oauth2/token
          scopes:
            BANK_ACCOUNTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to bank account information associated with the targeted
              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.
            CASH_DRAWER_READ: |-
              __HTTP Method__: `GET`

              Grants read access to cash drawer shift information. For example, to call the
              ListCashDrawerShifts endpoint.
            CUSTOMERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to customer information. For example, to call the
              ListCustomers endpoint.
            CUSTOMERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to customer information. For example, to create and update
              customer profiles.
            DEVICE_CREDENTIAL_MANAGEMENT: |-
              __HTTP Method__: `POST`, `GET`

              Grants read/write access to device credentials information. For example, to
              call the CreateDeviceCode endpoint.
            EMPLOYEES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee profile information. For example, to call the
              Connect v1 Employees API.
            EMPLOYEES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee profile information. For example, to create
              and modify employee profiles.
            INVENTORY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to inventory information. For example, to call the
              RetrieveInventoryCount endpoint.
            INVENTORY_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to inventory information. For example, to call the
              BatchChangeInventory endpoint.
            ITEMS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ITEMS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to product catalog information. For example, to modify or
              add to a product catalog.
            LOYALTY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to loyalty information. For example, to call the
              ListLoyaltyPrograms endpoint.
            LOYALTY_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to loyalty information. For example, to call the
              CreateLoyaltyAccount endpoint.
            MERCHANT_PROFILE_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ORDERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to order information. For example, to call the
              BatchRetrieveOrders endpoint.
            ORDERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to order information. For example, to call the
              CreateCheckout endpoint.
            PAYMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to transaction and refund information. For example, to call
              the RetrieveTransaction endpoint.
            PAYMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to transaction and refunds information. For example, to
              process payments with the Payments or Checkout API.
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allow third party applications to deduct a portion of each transaction amount.
              __Required__ to use multiparty transaction functionality with the Payments
              API.
            PAYMENTS_WRITE_IN_PERSON: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to payments and refunds information. For example, to
              process in-person payments.
            SETTLEMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to settlement (deposit) information. For example, to call
              the Connect v1 ListSettlements endpoint.
            TIMECARDS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard information. For example, to call the
              Connect v2 SearchShifts endpoint.
            TIMECARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee shift information. For example, to create
              and modify employee shifts.
            TIMECARDS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard settings information. For example, to
              call the GetBreakType endpoint.
            TIMECARDS_SETTINGS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee timecard settings information. For example, to
              call the UpdateBreakType endpoint.
      x-additional-headers:
      - name: Square-Version
        description: Square Connect API versions
        schema:
          default: 2020-09-23
    oauth2ClientSecret:
      type: apiKey
      name: Authorization
      in: header
  x-apis:
    Checkout:
      name: Checkout
      summary: Accept itemized payments on a Square-hosted webpage, no frontend experience
        required
      description: |2-

        The Checkout API lets you create Square-hosted checkout webpages where your customers can pay for
        goods and services. Like the Orders API, it allows you to add custom line items or catalog objects
        so customers can see what they're purchasing.

        You can also configure a URL for customers to be redirected to once they complete their purchase, to
        verify that the payment went through successfully.
      externalDocsList:
      - description: Checkout
        url: https://developer.squareup.com/docs/checkout-api-overview
    Labor:
      name: Labor
      summary: Manage shifts, breaks, and wages for employees in Square POS
      description: |2-

        The Labor API allows you to see when employees clocked in and out, how much they worked during different
        periods, and how many breaks they took. You can also call the API to register a past break, adjust a shift,
        or update a wage.

        This API is best used in conjunction with the Team API.
      externalDocsList:
      - description: Labor
        url: https://developer.squareup.com/docs/labor-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    BankAccounts:
      name: Bank Accounts
      summary: Get a list of a merchant's bank accounts
      description: |2-

        The Bank Account API allows you to get basic details about a merchant's bank account, such as the
        last few digits of the account number and the routing number. It can be paired with the Settlements API to understand the
        pattern of deposits and withdrawals from a merchant's bank account.
      externalDocsList:
      - description: Bank Accounts
        url: https://developer.squareup.com/docs/bank-accounts-api
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Loyalty:
      name: Loyalty
      summary: Create and manage loyalty accounts for buyers.
      description: |2

        The Loyalty API enables you to create and manage loyalty accounts for buyers in a loyalty program, allow them to earn points, and to redeem rewards.
      externalDocsList:
      - description: Loyalty
        url: https://developer.squareup.com/docs/loyalty/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Locations:
      name: Locations
      summary: Get a list of all a merchant's locations
      description: |2-

        Many merchants use multiple locations to track where they make sales. The locations API allows you to
        get data about those locations, such as their addresses, names, and business hours.
      externalDocsList:
      - description: Locations
        url: https://developer.squareup.com/docs/locations-api
    Devices:
      name: Devices
      summary: Manages pairing between a 3rd party Point of Sale app and a Square
        Terminal in a merchant location.
      description: ""
      externalDocsList:
      - description: Devices
        url: https://developer.squareup.com/docs/terminal-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Inventory:
      name: Inventory
      summary: Keep inventory of catalog items in sync across all commerce channels
      description: |2-

        The Inventory API provides the ability to do a 2-way sync between your inventory system and Square
        using catalog items. You can poll Square's inventory counts to update your system, and update counts
        in Square using the batch change inventory request.
      externalDocsList:
      - description: Inventory
        url: https://developer.squareup.com/docs/inventory-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Reporting:
      name: Reporting
      summary: Deprecated - Use the Orders & Payments APIs instead
      description: |2-

        Prior to 2019/08/15, the Reporting API was the way to review multi-party payments taken with the Transactions
        API. The Payments API now includes a "application fee" parameter you can use to replace this functionality.
    OAuth:
      name: OAuth
      summary: Allow your application to gain programmatic access to other merchant
        accounts
      description: |2-

        The Square OAuth API lets applications request and obtain permission from a Square account to make API
        calls on behalf of that account. Applications can request individual permissions so that users do not need
        to grant full access to their Square accounts.
      externalDocsList:
      - description: OAuth
        url: https://developer.squareup.com/docs/oauth-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Webhooks:
      name: Webhooks
      summary: Subscribe to V1 Webhook events for a merchant
      description: |2-

        **If you're working with V1 Webhooks,** you'll use the Webhooks API to subscribe to events for each merchant you're interested in receiving events for. Learn how to subscribe to V1 Webhooks [here](/docs/webhooks-api/subscribe-to-events-v1).

        **If you're working with V2 Webhooks,** you don't need to use this API; instead, you'll subscribe to events using the [Developer Dashboard](/apps). Learn how to subscribe to V2 Webhooks [here](/docs/webhooks-api/subscribe-to-events).
    Merchants:
      name: Merchants
      summary: Use the Merchants API to retrieve information about a Square merchant
        account
      description: |2-

        For example, suppose you develop an application (an eCommerce or a SaaS platform) integrated
        with Square to process payments. Other Square sellers sign up to use your application.

        In this scenario, the application developer can use the Merchants API to retrieve seller account information,
        such as language, business name, country, and account status as shown in the following RetrieveMerchant request.
        In the request, the Authorization header provides an OAuth access token that identifies the seller whose account
        information is requested.
      externalDocsList:
      - description: Merchants
        url: https://developer.squareup.com/docs/merchants-api
    Invoices:
      name: Invoices
      summary: Create and manage invoices.
      description: |2

        Square Invoices enable you to request or automatically collect payments from customers for orders created using the Orders API.

        The Invoices API makes it easy for you to manage invoices. After you create and publish an invoice using the API, Square follows up with the customer by sending the invoice to the customer's email address or automatically charging the customer's card on file. Square makes it easy for your customers to pay by hosting each invoice on a web page where customers can pay for it.
      externalDocsList:
      - description: Invoices
        url: https://developer.squareup.com/docs/invoices-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Employees:
      name: Employees
      summary: Pull employee data into accounting and payroll systems with the Employees
        API
      description: |2-

        The Employees API allows applications to retrieve a roster of employees registered in the Square Point
        of Sale system, which can be useful in payroll and account contexts.

        The Employees API is best used in conjunction with the Labor API, where you provide employee IDs to
        manage shifts, breaks, and wages.
    Customers:
      name: Customers
      summary: Create and manage customer profiles, save cards on file for customers,
        and sync CRM systems with Square.
      description: |2

        The Customers API enables you to create and manage customer profiles, as well as search for customers based on various criteria (including customer group membership). You can also use the API to save cards on file for customers to streamline future transactions, for example, to enable speedier checkout without requiring the card-on-file customer to provide the credit card info again. In addition, the API allows you to sync contacts between your CRM system and Square.
      externalDocsList:
      - description: Customers
        url: https://developer.squareup.com/docs/customers-api/what-it-does
    CashDrawers:
      name: Cash Drawers
      summary: Get details about cash drawers
      description: |2-

        Cash drawers track cash transactions so that total money in the cash drawers can be reconciled for a
        specific period of time (a cash drawer shift) for a particular device in a particular location. The Cash Drawers API
        enables you to list and retrieve cash drawers information.
      externalDocsList:
      - description: Cash Drawer Shifts
        url: https://developer.squareup.com/docs/cashdrawershift-api/reporting
    CustomerSegments:
      name: Customer Segments
      summary: List and retrieve customer segments (aka smart groups) in the business
        account.
      description: "\nThe Customer Segments API lets you retrieve information about\
        \ segments available in the business account. You can only create a segment\
        \ in the Square Dashboard or Point of Sale by defining and saving the desired\
        \ filters for the segment. For example, you could define a customer segment\
        \ to include customers who have visited more than 10 times. Customers will\
        \ be automatically added to and removed from the segment over time based on\
        \ this criterion. \n\nYou can determine if a given customer is a part of segment\
        \ by inspecting the customer's `segment_ids` property. With the segments'\
        \ IDs, you can then use the Customer Segments API to retrieve basic details\
        \ about each segment, such as the segment name and the time when it was created."
      externalDocsList:
      - description: Customer Segments
        url: https://developer.squareup.com/docs/customer-segments-api/what-it-does
    ApplePay:
      name: Apple Pay
      summary: Apple Pay support APIs
      description: |2-

        The Apple Pay APIs provides an easy way for platform developers
        to bulk activate Web Apple Pay with Square for merchants using their platform.
      externalDocsList:
      - description: Payment Form
        url: https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay
      - description: In-App Payments SDK
        url: https://developer.squareup.com/docs/in-app-payments-sdk/add-digital-wallets/apple-pay
    Payments:
      name: Payments
      summary: The Payments API lets developers take and manage payments
      description: |2

        Applications need the following input to take a payment:

        - Amount to charge.
        - Payment recipient. The payment goes to the account identified by the Authorization header in the API request.
        - Payment source. It can be a secure token (nonce) or a card on file.

        You can generate a nonce using the Square Payment Form and the In-App Payments SDK.
        For working code examples, see Connect API examples.

        A card on file refers to a credit/debit or a gift card associated with a customer.
        You can create a customer and add a card to them using either the Customers API, the dashboard, or the Square mobile app.
      externalDocsList:
      - description: Payments
        url: https://developer.squareup.com/docs/payments-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    MobileAuthorization:
      name: Mobile Authorization
      summary: Authorize Reader SDK apps to take in-person payments
      description: |2-

        The Mobile Authorization API accepts an account credential (OAuth token or Personal Access Token) and
        location ID and returns an authorization code that custom mobile apps can use to initialize Square mobile
        solutions like Reader SDK to accept payments using Square hardware.
      externalDocsList:
      - description: Mobile Authorization
        url: https://developer.squareup.com/docs/mobile-authz/what-it-does
    Terminal:
      name: Terminal
      summary: Requests a checkout from a paired Square Terminal
      description: |2-

        The Terminal API allows you to manage terminal checkout requests sent to a paired Square
        Terminal. You can create a request, check the request status, cancel the checkout,
        search for in-process checkout requests, and get the results of the checkout after
        it is completed by the Square Terminal.
      externalDocsList:
      - description: Terminal
        url: https://developer.squareup.com/docs/terminal-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Disputes:
      name: Disputes
      summary: Use the Disputes API to manage disputes (chargebacks).
      description: |2-

        A merchant has the following options to process a dispute:

        - **Accept the dispute** using the [AcceptDispute](/reference/square/disputes-api/accept-dispute) endpoint. Square returns the disputed amount from the account balance of the Square account.
        - **Challenge the dispute** using the [SubmitEvidence](/reference/square/disputes-api/submit-evidence) endpoint — If payment was valid you can contest the disputed payment.
        You submit supporting evidence you have about the transaction, such as, receipts, invoices, email correspondence, proof of delivery, or photos.
        You upload evidence using the [CreateDisputeEvidenceFile](/reference/square/disputes-api/create-dispute-evidence-file) endpoint.

        The Disputes API also supports other endpoints useful in dispute management.
      externalDocsList:
      - description: Disputes
        url: https://developer.squareup.com/docs/disputes-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Catalog:
      name: Catalog
      summary: Sync items to Square POS to itemize payments consistently across all
        channels
      description: |2-

        The Catalog API allows you to manage your item catalog in Point of Sale, including items, variations,
        categories, discounts, taxes, modifiers, and more.

        You can efficiently sync items between your systems and Square by using our batch APIs, which allow
        you update many catalog items at once.
      externalDocsList:
      - description: Catalog
        url: https://developer.squareup.com/docs/catalog-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    CustomerGroups:
      name: Customer Groups
      summary: Programmatically create and manage customer groups to streamline and
        automate workflows, and to enable more personalized customer interactions.
      description: "\nThe Customer Groups API lets you create and manage customer\
        \ groups to provide targeted promotions or take other customized actions based\
        \ on customers' group memberships. For example, you could create _Weekly_,\
        \ _Monthly_ and _Quarterly_ customer groups and add customers to them based\
        \ on their preferences to receive marketing promotions on a weekly, monthly\
        \ and quarterly basis, respectively. You could then send marketing emails\
        \ to customers in the _Weekly_ group every Wednesday, to those in the _Monthly_\
        \ group the first day of each month, and to those in the _Quarterly_ group\
        \ every three months. \n\nThe Customer Groups API enables you to retrieve\
        \ and manage customer groups, while you can add and remove customers from\
        \ groups and search for customers based on group membership using the Customers\
        \ API.\n\n"
      externalDocsList:
      - description: Customer Groups
        url: https://developer.squareup.com/docs/customer-groups-api/what-it-does
    Settlements:
      name: Settlements
      summary: Get a list of deposits / withdrawals from a merchant's bank accounts
      description: |2-

        The Settlements API allows you to see a complete list of settlements made to a merchant's bank account,
        with a list of settlement entries that describe the payments associated with each settlement. It can be paired with the
        Bank Accounts API to add detail about which bank account each settlement was made to.
    Orders:
      name: Orders
      summary: Get sales data for a Square merchant, itemize payments, push orders
        to POS, and more
      description: |2-

        The Orders API is your one-stop shop for adding rich functionality to payments. You can itemize
        payments using custom line items or catalog objects, send orders to physical Point of Sale devices
        to be fulfilled, attach a customer to a payment, and more.

        In addition, the Orders API lets you search through all of a merchant's past sales and returns itemization
        data, customer references, and other details from sales made via POS or online.
      externalDocsList:
      - description: Orders
        url: https://developer.squareup.com/docs/orders-api/what-it-does
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Team:
      name: Team
      summary: Pull employee data into accounting and payroll systems with the Team
        API
      description: |2-

        The Team API allows applications to retrieve a roster of team members registered in the Square Point
        of Sale system, which can be useful in payroll and account contexts.

        The Team API is best used in conjunction with the Labor API, where you provide team member IDs to
        manage shifts, breaks, and wages.
      externalDocsList:
      - description: Team
        url: https://developer.squareup.com/docs/team/overview
    Transactions:
      name: Transactions
      summary: Deprecated - Use the Orders & Payments APIs instead
      description: |2-

        Prior to 2019/08/15, Transactions API was the way to take online payments. Going forward, the Payments
        and Refunds API (together with the Orders API) replace the Transactions API.
    Refunds:
      name: Refunds
      summary: Manage and issue refunds for payments made to Square merchants
      description: |2

        The following apply for refunds:

        - You cannot refund more than what was originally collected.
        - The refund amount must be available in the account’s Square balance. If not, Square will attempt to take money out of
          their associated bank account. Refunds will be in a state of `PENDING` until the funds can be secured.
        - If funds can not be secured, the refund will not complete and the buyer will not receive a credit. The refund will have
          a status of `FAILED`. Future refunds to this payment will not be allowed and the buyer should be reimbursed by other means.
        - You can refund only payments with status `COMPLETED`. You cannot refund an `APPROVED` payment; however, you can cancel
          an approved payment.
      externalDocsList:
      - description: Refunds
        url: https://developer.squareup.com/docs/payments-api/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
    Subscriptions:
      name: Subscriptions
      summary: Create and manage subscriptions.
      description: "\nSubscriptions enable sellers to generate a reliable cash flow\
        \ and recurring revenue to grow their businesses. Square offers the Subscriptions\
        \ API for developers to embed subscription functionality in their applications.\
        \ You first create a subscription plan using the Catalog API and then use\
        \ the Subscriptions API to create and manage subscriptions. \n\n"
      externalDocsList:
      - description: Subscriptions
        url: https://developer.squareup.com/docs/subscriptions/overview
      - description: Webhooks
        url: https://developer.squareup.com/docs/webhooks-overview
  x-categories:
    Business:
      name: Business
      summary: Manage locations and merchant details
      description: |2-

        Use the Location and Merchant APIs to keep track of core business details, such
        as addresses and business hours. Use Devices and Cash Drawers to keep track of the
        point of sale devices and cash drawer shift activity in a business.
      apis:
      - '#/components/x-apis/Merchants'
      - '#/components/x-apis/Locations'
      - '#/components/x-apis/Devices'
      - '#/components/x-apis/Cash Drawers'
    Loyalty:
      name: Loyalty
      summary: 'Create loyalty accounts for buyers in a loyalty program, allow them
        to earn points, and to redeem rewards. '
      description: "\nCreate loyalty accounts for buyers in a loyalty program, add\
        \ points to their loyalty account, and redeem rewards.\n\n\n "
      apis:
      - '#/components/x-apis/Loyalty'
    Items:
      name: Items
      summary: APIs for enriching payments with items and inventory
      description: |2-

        Sync merchant catalogs and inventory to provide consistent itemization and
        reporting across all channels
      apis:
      - '#/components/x-apis/Catalog'
      - '#/components/x-apis/Inventory'
    Invoices:
      name: Invoices
      summary: Create and manage invoices.
      description: |2

        Square invoices enable you to request or automatically collect payments from  customer for orders created using the Orders API.

        The Invoices API makes it easy  for you to manage invoices. After you create and publish an invoice using the API, Square follows up with customers: sends invoices to the customer's email address or automatically charges the customer's card on file. Square makes it easy for your customers to pay by hosting each invoice on a web page where customers can pay for it.

        For more information, see [Manage Invoices Using the Invoices API](/docs/invoices-api/overview).
      apis:
      - '#/components/x-apis/Invoices'
    Customers:
      name: Customers
      summary: 'Create and manage customer profiles, save cards on file for customers,
        and sync custom CRM systems with Square. '
      description: "\nCreate and manage customer profiles, as well as search for customers\
        \ based on various criteria such as customer group membership and when the\
        \ customer was created. Save cards on file for the customers to facilitate\
        \ future transactions. Sync contacts between your CRM system and Square.\n\
        \n\n "
      apis:
      - '#/components/x-apis/Customers'
      - '#/components/x-apis/CustomerGroups'
      - '#/components/x-apis/CustomerSegments'
    Payments:
      name: Payments
      summary: Take payments and issue refunds
      description: |2-

        Square's Payment APIs make it easy for you to take payments, manage refunds,
        and help customers check out online.
      apis:
      - '#/components/x-apis/Payments'
      - '#/components/x-apis/Refunds'
      - '#/components/x-apis/Disputes'
      - '#/components/x-apis/Checkout'
      - '#/components/x-apis/ApplePay'
      - '#/components/x-apis/Reporting'
      - '#/components/x-apis/Terminal'
      - '#/components/x-apis/Transactions'
    Auth:
      name: Auth
      summary: Manage access to Square merchant accounts
      description: |2-

        Use OAuth to gain programmatic access to other Square merchants, and use the
        Mobile Authorization API to grant access to Reader SDK to take payments.
      apis:
      - '#/components/x-apis/OAuth'
      - '#/components/x-apis/MobileAuthorization'
    Orders:
      name: Orders
      summary: Itemize payments, issue refunds, and push orders into Square of Sale
      description: |2-

        Square's Payment APIs make it easy for you to take itemize payments, fulfill
        orders at physical locations, and report on a merchant's sales.
      apis:
      - '#/components/x-apis/Orders'
    Team:
      name: Team
      summary: Manage your team of employees
      description: |2-

        Use the Team and Labor APIs to keep track of who works at your business and
        when they clock in / out.
      apis:
      - '#/components/x-apis/Team'
      - '#/components/x-apis/Labor'
    Financials:
      name: Financials
      summary: Get details about your business' deposits and bank accounts
      description: ""
      apis:
      - '#/components/x-apis/BankAccounts'
      - '#/components/x-apis/Settlements'
    Subscriptions:
      name: Subscriptions
      summary: 'Create and manage subscriptions. '
      description: "\nSubscriptions enable sellers to generate a reliable cash flow\
        \ and recurring revenue to grow their businesses. Square offers the Subscriptions\
        \ API for developers to embed subscription functionality in their applications.\
        \ You first create a subscription plan using the Catalog API and then use\
        \ the Subscriptions API to create and manage subscriptions. \n\nFor more information,\
        \ see [Square Subscriptions](/docs/subscriptions/overview)."
      apis:
      - '#/components/x-apis/Subscriptions'
  x-categories-order:
  - Payments
  - Orders
  - Subscriptions
  - Invoices
  - Items
  - Customers
  - Loyalty
  - Business
  - Team
  - Financials
  - Auth
  x-v1-api-mappings:
    V1Employees:
      ListCashDrawerShifts: CashDrawers
      RetrieveCashDrawerShift: CashDrawers
      CreateEmployee: Employees
      CreateEmployeeRole: Employees
      ListEmployees: Employees
      ListEmployeeRoles: Employees
      RetrieveEmployee: Employees
      RetrieveEmployeeRole: Employees
      UpdateEmployee: Employees
      UpdateEmployeeRole: Employees
      CreateTimecard: Labor
      DeleteTimecard: Labor
      ListTimecards: Labor
      ListTimecardEvents: Labor
      RetrieveTimecard: Labor
      UpdateTimecard: Labor
    V1Items:
      ApplyFee: Catalog
      ApplyModifierList: Catalog
      CreateCategory: Catalog
      CreateDiscount: Catalog
      CreateFee: Catalog
      CreateItem: Catalog
      CreateModifierList: Catalog
      CreateModifierOption: Catalog
      CreatePage: Catalog
      CreateVariation: Catalog
      DeleteCategory: Catalog
      DeleteDiscount: Catalog
      DeleteFee: Catalog
      DeleteItem: Catalog
      DeleteModifierList: Catalog
      DeleteModifierOption: Catalog
      DeletePage: Catalog
      DeletePageCell: Catalog
      DeleteVariation: Catalog
      ListCategories: Catalog
      ListDiscounts: Catalog
      ListFees: Catalog
      ListItems: Catalog
      ListModifierLists: Catalog
      ListPages: Catalog
      RemoveFee: Catalog
      RemoveModifierList: Catalog
      RetrieveItem: Catalog
      RetrieveModifierList: Catalog
      UpdateCategory: Catalog
      UpdateDiscount: Catalog
      UpdateFee: Catalog
      UpdateItem: Catalog
      UpdateModifierList: Catalog
      UpdateModifierOption: Catalog
      UpdatePage: Catalog
      UpdatePageCell: Catalog
      UpdateVariation: Catalog
      UploadItemImage: Catalog
      AdjustInventory: Inventory
      ListInventory: Inventory
    V1Locations:
      ListLocations: Locations
      RetrieveBusiness: Merchants
    V1Transactions:
      ListBankAccounts: BankAccounts
      RetrieveBankAccount: BankAccounts
      ListPayments: Payments
      RetrievePayment: Payments
      CreateRefund: Refunds
      ListRefunds: Refunds
      ListSettlements: Settlements
      RetrieveSettlement: Settlements
    V1Webhooks:
      ListWebhooks: Webhooks
      UpdateWebhooks: Webhooks
