/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The response object returned by the [ListMerchant](api-endpoint:Merchants-ListMerchants) endpoint.
type ListMerchantsResponse struct {
	// Information on errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The requested `Merchant` entities.
	Merchant []Merchant `json:"merchant,omitempty"`
	// If the  response is truncated, the cursor to use in next  request to fetch next set of objects.
	Cursor int32 `json:"cursor,omitempty"`
}
