/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes a gift card activity of the ADJUST_DECREMENT type.
type GiftCardActivityAdjustDecrement struct {
	AmountMoney *Money                                 `json:"amount_money"`
	Reason      *GiftCardActivityAdjustDecrementReason `json:"reason"`
}
