/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1SettlementEntryType string

// List of V1SettlementEntryType
const (
	ADJUSTMENT_V1SettlementEntryType                      V1SettlementEntryType = "ADJUSTMENT"
	BALANCE_CHARGE_V1SettlementEntryType                  V1SettlementEntryType = "BALANCE_CHARGE"
	CHARGE_V1SettlementEntryType                          V1SettlementEntryType = "CHARGE"
	FREE_PROCESSING_V1SettlementEntryType                 V1SettlementEntryType = "FREE_PROCESSING"
	HOLD_ADJUSTMENT_V1SettlementEntryType                 V1SettlementEntryType = "HOLD_ADJUSTMENT"
	PAID_SERVICE_FEE_V1SettlementEntryType                V1SettlementEntryType = "PAID_SERVICE_FEE"
	PAID_SERVICE_FEE_REFUND_V1SettlementEntryType         V1SettlementEntryType = "PAID_SERVICE_FEE_REFUND"
	REDEMPTION_CODE_V1SettlementEntryType                 V1SettlementEntryType = "REDEMPTION_CODE"
	REFUND_V1SettlementEntryType                          V1SettlementEntryType = "REFUND"
	RETURNED_PAYOUT_V1SettlementEntryType                 V1SettlementEntryType = "RETURNED_PAYOUT"
	SQUARE_CAPITAL_ADVANCE_V1SettlementEntryType          V1SettlementEntryType = "SQUARE_CAPITAL_ADVANCE"
	SQUARE_CAPITAL_PAYMENT_V1SettlementEntryType          V1SettlementEntryType = "SQUARE_CAPITAL_PAYMENT"
	SQUARE_CAPITAL_REVERSED_PAYMENT_V1SettlementEntryType V1SettlementEntryType = "SQUARE_CAPITAL_REVERSED_PAYMENT"
	SUBSCRIPTION_FEE_V1SettlementEntryType                V1SettlementEntryType = "SUBSCRIPTION_FEE"
	SUBSCRIPTION_FEE_REFUND_V1SettlementEntryType         V1SettlementEntryType = "SUBSCRIPTION_FEE_REFUND"
	OTHER_V1SettlementEntryType                           V1SettlementEntryType = "OTHER"
	INCENTED_PAYMENT_V1SettlementEntryType                V1SettlementEntryType = "INCENTED_PAYMENT"
	RETURNED_ACH_ENTRY_V1SettlementEntryType              V1SettlementEntryType = "RETURNED_ACH_ENTRY"
	RETURNED_SQUARE_275_V1SettlementEntryType             V1SettlementEntryType = "RETURNED_SQUARE_275"
	SQUARE_275_V1SettlementEntryType                      V1SettlementEntryType = "SQUARE_275"
	SQUARE_CARD_V1SettlementEntryType                     V1SettlementEntryType = "SQUARE_CARD"
)
