/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ItemVisibility string

// List of V1ItemVisibility
const (
	PUBLIC_V1ItemVisibility  V1ItemVisibility = "PUBLIC"
	PRIVATE_V1ItemVisibility V1ItemVisibility = "PRIVATE"
)
