/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ItemColor string

// List of V1ItemColor
const (
	a9DA2A6__V1ItemColor V1ItemColor = "9da2a6"
	a4AB200__V1ItemColor V1ItemColor = "4ab200"
	a0B8000__V1ItemColor V1ItemColor = "0b8000"
	a2952CC__V1ItemColor V1ItemColor = "2952cc"
	aA82EE5_V1ItemColor  V1ItemColor = "a82ee5"
	aE5457A_V1ItemColor  V1ItemColor = "e5457a"
	aB21212_V1ItemColor  V1ItemColor = "b21212"
	a593C00__V1ItemColor V1ItemColor = "593c00"
	aE5_BF00_V1ItemColor V1ItemColor = "e5BF00"
)
