/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Additional details about a Buy Now Pay Later payment type.
type BuyNowPayLaterDetails struct {
	// The brand used for the Buy Now Pay Later payment. The brand can be `AFTERPAY` or `UNKNOWN`.
	Brand           string           `json:"brand,omitempty"`
	AfterpayDetails *AfterpayDetails `json:"afterpay_details,omitempty"`
}
