/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CatalogQuickAmountsSettingsOption : Determines a seller's option on Quick Amounts feature.
type CatalogQuickAmountsSettingsOption string

// List of CatalogQuickAmountsSettingsOption
const (
	DISABLED_CatalogQuickAmountsSettingsOption CatalogQuickAmountsSettingsOption = "DISABLED"
	MANUAL_CatalogQuickAmountsSettingsOption   CatalogQuickAmountsSettingsOption = "MANUAL"
	AUTO_CatalogQuickAmountsSettingsOption     CatalogQuickAmountsSettingsOption = "AUTO"
)
