/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to unlink a customer from a gift card.
type UnlinkCustomerFromGiftCardRequest struct {
	// The ID of the customer to unlink from the gift card.
	CustomerId string `json:"customer_id"`
}
