/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A response that contains one `GiftCard` that was unlinked. The response might contain a set of `Error` objects if the request resulted in errors.
type UnlinkCustomerFromGiftCardResponse struct {
	// Any errors that occurred during the request.
	Errors   []ModelError `json:"errors,omitempty"`
	GiftCard *GiftCard    `json:"gift_card,omitempty"`
}
