/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1PageCellObjectType string

// List of V1PageCellObjectType
const (
	ITEM_V1PageCellObjectType        V1PageCellObjectType = "ITEM"
	DISCOUNT_V1PageCellObjectType    V1PageCellObjectType = "DISCOUNT"
	CATEGORY_V1PageCellObjectType    V1PageCellObjectType = "CATEGORY"
	PLACEHOLDER_V1PageCellObjectType V1PageCellObjectType = "PLACEHOLDER"
)
