/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BatchUpsertCatalogObjectsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The created successfully created CatalogObjects.
	Objects []CatalogObject `json:"objects,omitempty"`
	// The database [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) of this update in RFC 3339 format, e.g., \"2016-09-04T23:59:33.123Z\".
	UpdatedAt string `json:"updated_at,omitempty"`
	// The mapping between client and server IDs for this upsert.
	IdMappings []CatalogIdMapping `json:"id_mappings,omitempty"`
}
