/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The response to a request for a set of `EmployeeWage` objects. Contains  a set of `EmployeeWage`.
type ListEmployeeWagesResponse struct {
	// A page of Employee Wage results.
	EmployeeWages []EmployeeWage `json:"employee_wages,omitempty"`
	// Value supplied in the subsequent request to fetch the next next page of Employee Wage results.
	Cursor string `json:"cursor,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
