/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a tax being returned that applies to one or more return line items in an order.  Fixed-amount, order-scoped taxes are distributed across all non-zero return line item totals. The amount distributed to each return line item is relative to that item’s contribution to the order subtotal.
type OrderReturnTax struct {
	// A unique ID that identifies the returned tax only within this order.
	Uid string `json:"uid,omitempty"`
	// The tax `uid` from the order that contains the original tax charge.
	SourceTaxUid string `json:"source_tax_uid,omitempty"`
	// The catalog object ID referencing [CatalogTax](entity:CatalogTax).
	CatalogObjectId string `json:"catalog_object_id,omitempty"`
	// The tax's name.
	Name  string                `json:"name,omitempty"`
	Type_ *OrderLineItemTaxType `json:"type,omitempty"`
	// The percentage of the tax, as a string representation of a decimal number. For example, a value of `\"7.25\"` corresponds to a percentage of 7.25%.
	Percentage   string                 `json:"percentage,omitempty"`
	AppliedMoney *Money                 `json:"applied_money,omitempty"`
	Scope        *OrderLineItemTaxScope `json:"scope,omitempty"`
}
