/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1CashDrawerEvent
type V1CashDrawerEvent struct {
	// The event's unique ID.
	Id string `json:"id,omitempty"`
	// The ID of the employee that created the event.
	EmployeeId string                      `json:"employee_id,omitempty"`
	EventType  *V1CashDrawerEventEventType `json:"event_type,omitempty"`
	EventMoney *V1Money                    `json:"event_money,omitempty"`
	// The time when the event occurred, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
	// An optional description of the event, entered by the employee that created it.
	Description string `json:"description,omitempty"`
}
