/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1UpdateModifierListRequest
type V1UpdateModifierListRequest struct {
	// The modifier list's name.
	Name          string                                    `json:"name,omitempty"`
	SelectionType *V1UpdateModifierListRequestSelectionType `json:"selection_type,omitempty"`
}
