/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1PaymentItemizationItemizationType string

// List of V1PaymentItemizationItemizationType
const (
	ITEM_V1PaymentItemizationItemizationType                 V1PaymentItemizationItemizationType = "ITEM"
	CUSTOM_AMOUNT_V1PaymentItemizationItemizationType        V1PaymentItemizationItemizationType = "CUSTOM_AMOUNT"
	GIFT_CARD_ACTIVATION_V1PaymentItemizationItemizationType V1PaymentItemizationItemizationType = "GIFT_CARD_ACTIVATION"
	GIFT_CARD_RELOAD_V1PaymentItemizationItemizationType     V1PaymentItemizationItemizationType = "GIFT_CARD_RELOAD"
	GIFT_CARD_UNKNOWN_V1PaymentItemizationItemizationType    V1PaymentItemizationItemizationType = "GIFT_CARD_UNKNOWN"
	OTHER_V1PaymentItemizationItemizationType                V1PaymentItemizationItemizationType = "OTHER"
)
