/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to retrieve gift cards by using nonces.
type RetrieveGiftCardFromNonceRequest struct {
	// The nonce of the gift card to retrieve.
	Nonce string `json:"nonce"`
}
