/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// VendorCreatedWebhookObjectOperation : The operation that can be performed against a vendor to cause the webhook event to be published.
type VendorCreatedWebhookObjectOperation string

// List of VendorCreatedWebhookObjectOperation
const (
	CREATED_VendorCreatedWebhookObjectOperation VendorCreatedWebhookObjectOperation = "CREATED"
)
