/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a reward tier in a loyalty program. A reward tier defines how buyers can redeem points for a reward, such as the number of points required and the value and scope of the discount. A loyalty program can offer multiple reward tiers.
type LoyaltyProgramRewardTier struct {
	// The Square-assigned ID of the reward tier.
	Id string `json:"id"`
	// The points exchanged for the reward tier.
	Points int32 `json:"points"`
	// The name of the reward tier.
	Name       string                          `json:"name"`
	Definition *LoyaltyProgramRewardDefinition `json:"definition"`
	// The timestamp when the reward tier was created, in RFC 3339 format.
	CreatedAt            string                  `json:"created_at"`
	PricingRuleReference *CatalogObjectReference `json:"pricing_rule_reference,omitempty"`
}
