/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Sets the sort order of search results.
type ShiftSort struct {
	Field *ShiftSortField `json:"field,omitempty"`
	Order *SortOrder      `json:"order,omitempty"`
}
