/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WebhookData struct {
	// Name of the affected object’s type.
	Type_ string `json:"type,omitempty"`
	// ID of the affected object.
	Id string `json:"id,omitempty"`
	// Is true if the affected object was deleted. Otherwise absent.
	Deleted bool `json:"deleted,omitempty"`
	// An object containing fields and values relevant to the event. Is absent if affected object was deleted.
	Object *interface{} `json:"object,omitempty"`
}
