/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the request parameters for the `ListDisputes` endpoint.
type ListDisputesRequest struct {
	// A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of results for the original query. For more information, see [Pagination](https://developer.squareup.com/docs/basics/api101/pagination).
	Cursor string `json:"cursor,omitempty"`
	// The dispute states used to filter the result. If not specified, the endpoint returns all disputes. See [DisputeState](#type-disputestate) for possible values
	States []DisputeState `json:"states,omitempty"`
	// The ID of the location for which to return a list of disputes. If not specified, the endpoint returns disputes associated with all locations.
	LocationId string `json:"location_id,omitempty"`
}
