/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an [AccumulateLoyaltyPoints](api-endpoint:Loyalty-AccumulateLoyaltyPoints) response.
type AccumulateLoyaltyPointsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError  `json:"errors,omitempty"`
	Event  *LoyaltyEvent `json:"event,omitempty"`
	// The resulting loyalty events. The `ACCUMULATE_POINTS` event is always included. When using the Orders API, the `ACCUMULATE_PROMOTION_POINTS` event is included if the purchase also qualifies for a loyalty promotion.
	Events []LoyaltyEvent `json:"events,omitempty"`
}
