/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the fields that are included in the response body of a request to the [CreateWebhookSubscription](api-endpoint:WebhookSubscriptions-CreateWebhookSubscription) endpoint.  Note: if there are errors processing the request, the [Subscription](entity:WebhookSubscription) will not be present.
type CreateWebhookSubscriptionResponse struct {
	// Information on errors encountered during the request.
	Errors       []ModelError         `json:"errors,omitempty"`
	Subscription *WebhookSubscription `json:"subscription,omitempty"`
}
