/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A response that contains one or more `GiftCard`. The response might contain a set of `Error` objects if the request resulted in errors.
type ListGiftCardsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// Gift cards retrieved.
	GiftCards []GiftCard `json:"gift_cards,omitempty"`
	// When a response is truncated, it includes a cursor that you can use in a subsequent request to fetch the next set of gift cards. If empty, this is the final response.
	Cursor string `json:"cursor,omitempty"`
}
