/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an action performed on a [gift card](entity:GiftCard) that affects its state or balance.  A gift card activity contains information about a specific activity type. For example, a `REDEEM` activity includes a `redeem_activity_details` field that contains information about the redemption.
type GiftCardActivity struct {
	// The Square-assigned ID of the gift card activity.
	Id    string                `json:"id,omitempty"`
	Type_ *GiftCardActivityType `json:"type"`
	// The ID of the [business location](entity:Location) where the activity occurred.
	LocationId string `json:"location_id"`
	// The timestamp when the gift card activity was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The gift card ID. When creating a gift card activity, `gift_card_id` is not required if  `gift_card_gan` is specified.
	GiftCardId string `json:"gift_card_id,omitempty"`
	// The gift card account number (GAN). When creating a gift card activity, `gift_card_gan`  is not required if `gift_card_id` is specified.
	GiftCardGan                           string                                  `json:"gift_card_gan,omitempty"`
	GiftCardBalanceMoney                  *Money                                  `json:"gift_card_balance_money,omitempty"`
	LoadActivityDetails                   *GiftCardActivityLoad                   `json:"load_activity_details,omitempty"`
	ActivateActivityDetails               *GiftCardActivityActivate               `json:"activate_activity_details,omitempty"`
	RedeemActivityDetails                 *GiftCardActivityRedeem                 `json:"redeem_activity_details,omitempty"`
	ClearBalanceActivityDetails           *GiftCardActivityClearBalance           `json:"clear_balance_activity_details,omitempty"`
	DeactivateActivityDetails             *GiftCardActivityDeactivate             `json:"deactivate_activity_details,omitempty"`
	AdjustIncrementActivityDetails        *GiftCardActivityAdjustIncrement        `json:"adjust_increment_activity_details,omitempty"`
	AdjustDecrementActivityDetails        *GiftCardActivityAdjustDecrement        `json:"adjust_decrement_activity_details,omitempty"`
	RefundActivityDetails                 *GiftCardActivityRefund                 `json:"refund_activity_details,omitempty"`
	UnlinkedActivityRefundActivityDetails *GiftCardActivityUnlinkedActivityRefund `json:"unlinked_activity_refund_activity_details,omitempty"`
	ImportActivityDetails                 *GiftCardActivityImport                 `json:"import_activity_details,omitempty"`
	BlockActivityDetails                  *GiftCardActivityBlock                  `json:"block_activity_details,omitempty"`
	UnblockActivityDetails                *GiftCardActivityUnblock                `json:"unblock_activity_details,omitempty"`
	ImportReversalActivityDetails         *GiftCardActivityImportReversal         `json:"import_reversal_activity_details,omitempty"`
}
