/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerminalCheckoutUpdatedWebhookData struct {
	// Name of the updated object’s type, `\"terminal.checkout\"`.
	Type_ string `json:"type,omitempty"`
	// ID of the updated terminal checkout.
	Id     string                                `json:"id,omitempty"`
	Object *TerminalCheckoutUpdatedWebhookObject `json:"object,omitempty"`
}
