/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines input parameters in a call to the  [SwapPlan](api-endpoint:Subscriptions-SwapPlan) endpoint.
type SwapPlanRequest struct {
	// The ID of the new subscription plan.
	NewPlanId string `json:"new_plan_id"`
}
