/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Updates a [Subscription](entity:WebhookSubscription) by replacing the existing signature key with a new one.
type UpdateWebhookSubscriptionSignatureKeyRequest struct {
	// A unique string that identifies the [UpdateWebhookSubscriptionSignatureKey](api-endpoint:WebhookSubscriptions-UpdateWebhookSubscriptionSignatureKey) request.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
}
