/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MeasurementUnitLength : The unit of length used to measure a quantity.
type MeasurementUnitLength string

// List of MeasurementUnitLength
const (
	INVALID_LENGTH_MeasurementUnitLength    MeasurementUnitLength = "INVALID_LENGTH"
	IMPERIAL_INCH_MeasurementUnitLength     MeasurementUnitLength = "IMPERIAL_INCH"
	IMPERIAL_FOOT_MeasurementUnitLength     MeasurementUnitLength = "IMPERIAL_FOOT"
	IMPERIAL_YARD_MeasurementUnitLength     MeasurementUnitLength = "IMPERIAL_YARD"
	IMPERIAL_MILE_MeasurementUnitLength     MeasurementUnitLength = "IMPERIAL_MILE"
	METRIC_MILLIMETER_MeasurementUnitLength MeasurementUnitLength = "METRIC_MILLIMETER"
	METRIC_CENTIMETER_MeasurementUnitLength MeasurementUnitLength = "METRIC_CENTIMETER"
	METRIC_METER_MeasurementUnitLength      MeasurementUnitLength = "METRIC_METER"
	METRIC_KILOMETER_MeasurementUnitLength  MeasurementUnitLength = "METRIC_KILOMETER"
)
