/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GiftCardType string

// List of GiftCardType
const (
	TYPE_DO_NOT_USE_GiftCardType GiftCardType = "TYPE_DO_NOT_USE"
	PHYSICAL_GiftCardType        GiftCardType = "PHYSICAL"
	DIGITAL_GiftCardType         GiftCardType = "DIGITAL"
)
