/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents one of a business's employees.
type V1Employee struct {
	// The employee's unique ID.
	Id string `json:"id,omitempty"`
	// The employee's first name.
	FirstName string `json:"first_name"`
	// The employee's last name.
	LastName string `json:"last_name"`
	// The ids of the employee's associated roles. Currently, you can specify only one or zero roles per employee.
	RoleIds []string `json:"role_ids,omitempty"`
	// The IDs of the locations the employee is allowed to clock in at.
	AuthorizedLocationIds []string `json:"authorized_location_ids,omitempty"`
	// The employee's email address.
	Email  string            `json:"email,omitempty"`
	Status *V1EmployeeStatus `json:"status,omitempty"`
	// An ID the merchant can set to associate the employee with an entity in another system.
	ExternalId string `json:"external_id,omitempty"`
	// The time when the employee entity was created, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The time when the employee entity was most recently updated, in ISO 8601 format.
	UpdatedAt string `json:"updated_at,omitempty"`
}
