/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CustomerCreationSource : Indicates the method used to create the customer profile.
type CustomerCreationSource string

// List of CustomerCreationSource
const (
	OTHER_CustomerCreationSource              CustomerCreationSource = "OTHER"
	APPOINTMENTS_CustomerCreationSource       CustomerCreationSource = "APPOINTMENTS"
	COUPON_CustomerCreationSource             CustomerCreationSource = "COUPON"
	DELETION_RECOVERY_CustomerCreationSource  CustomerCreationSource = "DELETION_RECOVERY"
	DIRECTORY_CustomerCreationSource          CustomerCreationSource = "DIRECTORY"
	EGIFTING_CustomerCreationSource           CustomerCreationSource = "EGIFTING"
	EMAIL_COLLECTION_CustomerCreationSource   CustomerCreationSource = "EMAIL_COLLECTION"
	FEEDBACK_CustomerCreationSource           CustomerCreationSource = "FEEDBACK"
	IMPORT__CustomerCreationSource            CustomerCreationSource = "IMPORT"
	INVOICES_CustomerCreationSource           CustomerCreationSource = "INVOICES"
	LOYALTY_CustomerCreationSource            CustomerCreationSource = "LOYALTY"
	MARKETING_CustomerCreationSource          CustomerCreationSource = "MARKETING"
	MERGE_CustomerCreationSource              CustomerCreationSource = "MERGE"
	ONLINE_STORE_CustomerCreationSource       CustomerCreationSource = "ONLINE_STORE"
	INSTANT_PROFILE_CustomerCreationSource    CustomerCreationSource = "INSTANT_PROFILE"
	TERMINAL_CustomerCreationSource           CustomerCreationSource = "TERMINAL"
	THIRD_PARTY_CustomerCreationSource        CustomerCreationSource = "THIRD_PARTY"
	THIRD_PARTY_IMPORT_CustomerCreationSource CustomerCreationSource = "THIRD_PARTY_IMPORT"
	UNMERGE_RECOVERY_CustomerCreationSource   CustomerCreationSource = "UNMERGE_RECOVERY"
)
