/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Published when a [Vendor](entity:Vendor) is updated.
type VendorUpdatedWebhook struct {
	// The ID of a seller associated with this webhook event.
	MerchantId string `json:"merchant_id,omitempty"`
	// The ID of a target platform account associated with this webhook event, if the event is associated with the platform account.
	AccountId string `json:"account_id,omitempty"`
	// The ID of a seller location associated with this webhook event, if the event is associated with the location.
	LocationId string `json:"location_id,omitempty"`
	// The type of this webhook event. The value is `\"vendor.updated\".`
	Type_ string `json:"type,omitempty"`
	// A unique ID for this webhoook event.
	EventId string `json:"event_id,omitempty"`
	// The RFC 3339-formatted time when the underlying webhook event data object is created.
	CreatedAt string                    `json:"created_at,omitempty"`
	Data      *VendorUpdatedWebhookData `json:"data,omitempty"`
}
