/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the parameters for a `CreateDisputeEvidenceFile` request.
type CreateDisputeEvidenceFileRequest struct {
	// The Unique ID. For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
	IdempotencyKey string               `json:"idempotency_key"`
	EvidenceType   *DisputeEvidenceType `json:"evidence_type,omitempty"`
	// The MIME type of the uploaded file. The type can be image/heic, image/heif, image/jpeg, application/pdf, image/png, or image/tiff.
	ContentType string `json:"content_type,omitempty"`
}
