/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// LocationCapability : The capabilities a location might have.
type LocationCapability string

// List of LocationCapability
const (
	CREDIT_CARD_PROCESSING_LocationCapability LocationCapability = "CREDIT_CARD_PROCESSING"
	AUTOMATIC_TRANSFERS_LocationCapability    LocationCapability = "AUTOMATIC_TRANSFERS"
)
