/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the fields that are included in the response body of a request to the [UpdateWebhookSubscriptionSignatureKey](api-endpoint:WebhookSubscriptions-UpdateWebhookSubscriptionSignatureKey) endpoint.  Note: If there are errors processing the request, the [Subscription](entity:WebhookSubscription) is not present.
type UpdateWebhookSubscriptionSignatureKeyResponse struct {
	// Information on errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The new Square-generated signature key used to validate the origin of the webhook event.
	SignatureKey string `json:"signature_key,omitempty"`
}
