/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1SubmitBatchResponse struct {
	// An array of `BatchResponse` objects corresponding to requests. The index of each response in the array matches the index of the corresponding request.
	Items []BatchResponse `json:"items,omitempty"`
}
