/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// GiftCardActivityAdjustDecrementReason : Indicates the reason for deducting money from a [gift card](entity:GiftCard).
type GiftCardActivityAdjustDecrementReason string

// List of GiftCardActivityAdjustDecrementReason
const (
	REASON_DO_NOT_USE_GiftCardActivityAdjustDecrementReason              GiftCardActivityAdjustDecrementReason = "REASON_DO_NOT_USE"
	SUSPICIOUS_ACTIVITY_GiftCardActivityAdjustDecrementReason            GiftCardActivityAdjustDecrementReason = "SUSPICIOUS_ACTIVITY"
	BALANCE_ACCIDENTALLY_INCREASED_GiftCardActivityAdjustDecrementReason GiftCardActivityAdjustDecrementReason = "BALANCE_ACCIDENTALLY_INCREASED"
	SUPPORT_ISSUE_GiftCardActivityAdjustDecrementReason                  GiftCardActivityAdjustDecrementReason = "SUPPORT_ISSUE"
	PURCHASE_WAS_REFUNDED_GiftCardActivityAdjustDecrementReason          GiftCardActivityAdjustDecrementReason = "PURCHASE_WAS_REFUNDED"
)
