/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// MeasurementUnitVolume : The unit of volume used to measure a quantity.
type MeasurementUnitVolume string

// List of MeasurementUnitVolume
const (
	INVALID_VOLUME_MeasurementUnitVolume      MeasurementUnitVolume = "INVALID_VOLUME"
	GENERIC_FLUID_OUNCE_MeasurementUnitVolume MeasurementUnitVolume = "GENERIC_FLUID_OUNCE"
	GENERIC_SHOT_MeasurementUnitVolume        MeasurementUnitVolume = "GENERIC_SHOT"
	GENERIC_CUP_MeasurementUnitVolume         MeasurementUnitVolume = "GENERIC_CUP"
	GENERIC_PINT_MeasurementUnitVolume        MeasurementUnitVolume = "GENERIC_PINT"
	GENERIC_QUART_MeasurementUnitVolume       MeasurementUnitVolume = "GENERIC_QUART"
	GENERIC_GALLON_MeasurementUnitVolume      MeasurementUnitVolume = "GENERIC_GALLON"
	IMPERIAL_CUBIC_INCH_MeasurementUnitVolume MeasurementUnitVolume = "IMPERIAL_CUBIC_INCH"
	IMPERIAL_CUBIC_FOOT_MeasurementUnitVolume MeasurementUnitVolume = "IMPERIAL_CUBIC_FOOT"
	IMPERIAL_CUBIC_YARD_MeasurementUnitVolume MeasurementUnitVolume = "IMPERIAL_CUBIC_YARD"
	METRIC_MILLILITER_MeasurementUnitVolume   MeasurementUnitVolume = "METRIC_MILLILITER"
	METRIC_LITER_MeasurementUnitVolume        MeasurementUnitVolume = "METRIC_LITER"
)
