/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents additional data for rules with the `SPEND` accrual type.
type LoyaltyProgramAccrualRuleSpendData struct {
	AmountMoney *Money `json:"amount_money"`
	// The IDs of any `CATEGORY` catalog objects that are excluded from points accrual.  You can use the [BatchRetrieveCatalogObjects](api-endpoint:Catalog-BatchRetrieveCatalogObjects) endpoint to retrieve information about the excluded categories.
	ExcludedCategoryIds []string `json:"excluded_category_ids,omitempty"`
	// The IDs of any `ITEM_VARIATION` catalog objects that are excluded from points accrual.  You can use the [BatchRetrieveCatalogObjects](api-endpoint:Catalog-BatchRetrieveCatalogObjects) endpoint to retrieve information about the excluded item variations.
	ExcludedItemVariationIds []string                          `json:"excluded_item_variation_ids,omitempty"`
	TaxMode                  *LoyaltyProgramAccrualRuleTaxMode `json:"tax_mode"`
}
