/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetrieveObsMigrationProfileResponse struct {
	// Indicates whether the seller has enabled the COVID banner (`true`) or not (`false`).
	BannerEnabled bool `json:"banner_enabled,omitempty"`
	// The text appearing on the COVID banner.
	BannerText string `json:"banner_text,omitempty"`
	// The text of the label of the CTA button beneath the banner.
	BannerCtaText string `json:"banner_cta_text,omitempty"`
	// The URL to link to when the CTA button is clicked.
	BannerCtaUrl string `json:"banner_cta_url,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
