/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// DayOfWeek : Indicates the specific day  of the week.
type DayOfWeek string

// List of DayOfWeek
const (
	SUN_DayOfWeek DayOfWeek = "SUN"
	MON_DayOfWeek DayOfWeek = "MON"
	TUE_DayOfWeek DayOfWeek = "TUE"
	WED_DayOfWeek DayOfWeek = "WED"
	THU_DayOfWeek DayOfWeek = "THU"
	FRI_DayOfWeek DayOfWeek = "FRI"
	SAT_DayOfWeek DayOfWeek = "SAT"
)
