/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// BusinessAppointmentSettingsBookingLocationType : Supported types of location where service is provided.
type BusinessAppointmentSettingsBookingLocationType string

// List of BusinessAppointmentSettingsBookingLocationType
const (
	BUSINESS_LOCATION_BusinessAppointmentSettingsBookingLocationType BusinessAppointmentSettingsBookingLocationType = "BUSINESS_LOCATION"
	CUSTOMER_LOCATION_BusinessAppointmentSettingsBookingLocationType BusinessAppointmentSettingsBookingLocationType = "CUSTOMER_LOCATION"
	PHONE_BusinessAppointmentSettingsBookingLocationType             BusinessAppointmentSettingsBookingLocationType = "PHONE"
)
