/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Returns a list of gift card activities. You can optionally specify a filter to retrieve a subset of activites.
type ListGiftCardActivitiesRequest struct {
	// If you provide a gift card ID, the endpoint returns activities that belong  to the specified gift card. Otherwise, the endpoint returns all gift card activities for  the seller.
	GiftCardId string `json:"gift_card_id,omitempty"`
	// If you provide a type, the endpoint returns gift card activities of this type.  Otherwise, the endpoint returns all types of gift card activities.
	Type_ string `json:"type,omitempty"`
	// If you provide a location ID, the endpoint returns gift card activities for that location.  Otherwise, the endpoint returns gift card activities for all locations.
	LocationId string `json:"location_id,omitempty"`
	// The timestamp for the beginning of the reporting period, in RFC 3339 format. Inclusive. Default: The current time minus one year.
	BeginTime string `json:"begin_time,omitempty"`
	// The timestamp for the end of the reporting period, in RFC 3339 format. Inclusive. Default: The current time.
	EndTime string `json:"end_time,omitempty"`
	// If you provide a limit value, the endpoint returns the specified number  of results (or less) per page. A maximum value is 100. The default value is 50.
	Limit int32 `json:"limit,omitempty"`
	// A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of results for the original query. If you do not provide the cursor, the call returns the first page of the results.
	Cursor string `json:"cursor,omitempty"`
	// The order in which the endpoint returns the activities, based on `created_at`. - `ASC` - Oldest to newest. - `DESC` - Newest to oldest (default).
	SortOrder string `json:"sort_order,omitempty"`
}
