/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This model gives the details of a cash drawer shift. The cash_payment_money, cash_refund_money, cash_paid_in_money, and cash_paid_out_money fields are all computed by summing their respective event types.
type CashDrawerShift struct {
	// The shift unique ID.
	Id    string                `json:"id,omitempty"`
	State *CashDrawerShiftState `json:"state,omitempty"`
	// The time when the shift began, in ISO 8601 format.
	OpenedAt string `json:"opened_at,omitempty"`
	// The time when the shift ended, in ISO 8601 format.
	EndedAt string `json:"ended_at,omitempty"`
	// The time when the shift was closed, in ISO 8601 format.
	ClosedAt string `json:"closed_at,omitempty"`
	// The IDs of all employees that were logged into Square Point of Sale at any point while the cash drawer shift was open.
	EmployeeIds []string `json:"employee_ids,omitempty"`
	// The ID of the employee that started the cash drawer shift.
	OpeningEmployeeId string `json:"opening_employee_id,omitempty"`
	// The ID of the employee that ended the cash drawer shift.
	EndingEmployeeId string `json:"ending_employee_id,omitempty"`
	// The ID of the employee that closed the cash drawer shift by auditing the cash drawer contents.
	ClosingEmployeeId string `json:"closing_employee_id,omitempty"`
	// The free-form text description of a cash drawer by an employee.
	Description       string            `json:"description,omitempty"`
	OpenedCashMoney   *Money            `json:"opened_cash_money,omitempty"`
	CashPaymentMoney  *Money            `json:"cash_payment_money,omitempty"`
	CashRefundsMoney  *Money            `json:"cash_refunds_money,omitempty"`
	CashPaidInMoney   *Money            `json:"cash_paid_in_money,omitempty"`
	CashPaidOutMoney  *Money            `json:"cash_paid_out_money,omitempty"`
	ExpectedCashMoney *Money            `json:"expected_cash_money,omitempty"`
	ClosedCashMoney   *Money            `json:"closed_cash_money,omitempty"`
	Device            *CashDrawerDevice `json:"device,omitempty"`
}
