/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Reflects the current status of a card payment. Contains only non-confidential information.
type CardPaymentDetails struct {
	// The card payment's current state. The state can be AUTHORIZED, CAPTURED, VOIDED, or FAILED.
	Status string `json:"status,omitempty"`
	Card   *Card  `json:"card,omitempty"`
	// The method used to enter the card's details for the payment. The method can be `KEYED`, `SWIPED`, `EMV`, `ON_FILE`, or `CONTACTLESS`.
	EntryMethod string `json:"entry_method,omitempty"`
	// The status code returned from the Card Verification Value (CVV) check. The code can be `CVV_ACCEPTED`, `CVV_REJECTED`, or `CVV_NOT_CHECKED`.
	CvvStatus string `json:"cvv_status,omitempty"`
	// The status code returned from the Address Verification System (AVS) check. The code can be `AVS_ACCEPTED`, `AVS_REJECTED`, or `AVS_NOT_CHECKED`.
	AvsStatus string `json:"avs_status,omitempty"`
	// The status code returned by the card issuer that describes the payment's authorization status.
	AuthResultCode string `json:"auth_result_code,omitempty"`
	// For EMV payments, the application ID identifies the EMV application used for the payment.
	ApplicationIdentifier string `json:"application_identifier,omitempty"`
	// For EMV payments, the human-readable name of the EMV application used for the payment.
	ApplicationName string `json:"application_name,omitempty"`
	// For EMV payments, the cryptogram generated for the payment.
	ApplicationCryptogram string `json:"application_cryptogram,omitempty"`
	// For EMV payments, the method used to verify the cardholder's identity. The method can be `PIN`, `SIGNATURE`, `PIN_AND_SIGNATURE`, `ON_DEVICE`, or `NONE`.
	VerificationMethod string `json:"verification_method,omitempty"`
	// For EMV payments, the results of the cardholder verification. The result can be `SUCCESS`, `FAILURE`, or `UNKNOWN`.
	VerificationResults string `json:"verification_results,omitempty"`
	// The statement description sent to the card networks.  Note: The actual statement description varies and is likely to be truncated and appended with additional information on a per issuer basis.
	StatementDescription string               `json:"statement_description,omitempty"`
	DeviceDetails        *DeviceDetails       `json:"device_details,omitempty"`
	CardPaymentTimeline  *CardPaymentTimeline `json:"card_payment_timeline,omitempty"`
	// Whether the card must be physically present for the payment to be refunded.  If set to `true`, the card must be present.
	RefundRequiresCardPresence bool `json:"refund_requires_card_presence,omitempty"`
	// Information about errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
