/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1ItemType string

// List of V1ItemType
const (
	NORMAL_V1ItemType    V1ItemType = "NORMAL"
	GIFT_CARD_V1ItemType V1ItemType = "GIFT_CARD"
	OTHER_V1ItemType     V1ItemType = "OTHER"
)
