/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// OauthAuthorizationRevokedWebhookRevokerType : Defines the possible types for the revoking client.
type OauthAuthorizationRevokedWebhookRevokerType string

// List of OauthAuthorizationRevokedWebhookRevokerType
const (
	APPLICATION_OauthAuthorizationRevokedWebhookRevokerType OauthAuthorizationRevokedWebhookRevokerType = "APPLICATION"
	MERCHANT_OauthAuthorizationRevokedWebhookRevokerType    OauthAuthorizationRevokedWebhookRevokerType = "MERCHANT"
	SQUARE_OauthAuthorizationRevokedWebhookRevokerType      OauthAuthorizationRevokedWebhookRevokerType = "SQUARE"
)
