/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A tax applicable to an item.
type CatalogTax struct {
	// The tax's name. This is a searchable attribute for use in applicable query filters, and its value length is of Unicode code points.
	Name             string               `json:"name,omitempty"`
	CalculationPhase *TaxCalculationPhase `json:"calculation_phase,omitempty"`
	InclusionType    *TaxInclusionType    `json:"inclusion_type,omitempty"`
	// The percentage of the tax in decimal form, using a `'.'` as the decimal separator and without a `'%'` sign. A value of `7.5` corresponds to 7.5%.
	Percentage string `json:"percentage,omitempty"`
	// If `true`, the fee applies to custom amounts entered into the Square Point of Sale app that are not associated with a particular `CatalogItem`.
	AppliesToCustomAmounts bool `json:"applies_to_custom_amounts,omitempty"`
	// If `true`, the tax will be shown as enabled in the Square Point of Sale app.
	Enabled bool `json:"enabled,omitempty"`
}
