/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// LoyaltyEventSource : Defines whether the event was generated by the Square Point of Sale.
type LoyaltyEventSource string

// List of LoyaltyEventSource
const (
	SQUARE_LoyaltyEventSource      LoyaltyEventSource = "SQUARE"
	LOYALTY_API_LoyaltyEventSource LoyaltyEventSource = "LOYALTY_API"
)
