/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a refund of a payment made using Square. Contains information on the original payment and the amount of money refunded.
type PaymentRefund struct {
	// Unique ID for this refund, generated by Square.
	Id string `json:"id"`
	// The refund's status: - `PENDING` - awaiting approval - `COMPLETED` - successfully completed - `REJECTED` - the refund was rejected - `FAILED` - an error occurred
	Status string `json:"status,omitempty"`
	// Location ID associated with the payment this refund is attached to.
	LocationId  string `json:"location_id,omitempty"`
	AmountMoney *Money `json:"amount_money"`
	AppFeeMoney *Money `json:"app_fee_money,omitempty"`
	// Processing fees and fee adjustments assessed by Square on this refund.
	ProcessingFee []ProcessingFee `json:"processing_fee,omitempty"`
	// The ID of the payment assocated with this refund.
	PaymentId string `json:"payment_id,omitempty"`
	// The ID of the order associated with the refund.
	OrderId string `json:"order_id,omitempty"`
	// The reason for the refund.
	Reason string `json:"reason,omitempty"`
	// Timestamp of when the refund was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// Timestamp of when the refund was last updated, in RFC 3339 format.
	UpdatedAt string `json:"updated_at,omitempty"`
}
