/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// InvoiceRequestType : Indicates the type of the payment request. For more information, see  [Payment requests](https://developer.squareup.com/docs/invoices-api/overview#payment-requests).
type InvoiceRequestType string

// List of InvoiceRequestType
const (
	INVOICE_REQUEST_TYPE_DO_NOT_USE_InvoiceRequestType InvoiceRequestType = "INVOICE_REQUEST_TYPE_DO_NOT_USE"
	BALANCE_InvoiceRequestType                         InvoiceRequestType = "BALANCE"
	DEPOSIT_InvoiceRequestType                         InvoiceRequestType = "DEPOSIT"
	INSTALLMENT_InvoiceRequestType                     InvoiceRequestType = "INSTALLMENT"
)
