/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SubscriptionActionType : Supported types of an action as a pending change to a subscription.
type SubscriptionActionType string

// List of SubscriptionActionType
const (
	DEFAULT_SUBSCRIPTION_ACTION_TYPE_DO_NOT_USE_SubscriptionActionType SubscriptionActionType = "DEFAULT_SUBSCRIPTION_ACTION_TYPE_DO_NOT_USE"
	CANCEL_SubscriptionActionType                                      SubscriptionActionType = "CANCEL"
	PAUSE_SubscriptionActionType                                       SubscriptionActionType = "PAUSE"
	RESUME_SubscriptionActionType                                      SubscriptionActionType = "RESUME"
	SWAP_PLAN_SubscriptionActionType                                   SubscriptionActionType = "SWAP_PLAN"
)
