/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to create a new `BreakType`
type CreateBreakTypeRequest struct {
	// Unique string value to insure idempotency of the operation
	IdempotencyKey string     `json:"idempotency_key,omitempty"`
	BreakType      *BreakType `json:"break_type"`
}
