/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a set of points for a loyalty account that are scheduled to expire on a specific date.
type LoyaltyAccountExpiringPointDeadline struct {
	// The number of points scheduled to expire at the `expires_at` timestamp.
	Points int32 `json:"points"`
	// The timestamp of when the points are scheduled to expire, in RFC 3339 format.
	ExpiresAt string `json:"expires_at"`
}
