/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Only one of `order_entries` or `orders` fields will be set, depending on whether `return_entries` was set on the [SearchOrdersRequest](#type-searchorderrequest).
type SearchOrdersResponse struct {
	// List of [OrderEntries](#type-orderentry) that fit the query conditions. Populated only if `return_entries` was set to `true` in the request.
	OrderEntries []OrderEntry `json:"order_entries,omitempty"`
	// List of [Order](#type-order) objects that match query conditions. Populated only if `return_entries` in the request is set to `false`.
	Orders []Order `json:"orders,omitempty"`
	// The pagination cursor to be used in a subsequent request. If unset, this is the final response. See [Pagination](https://developer.squareup.com/docs/basics/api101/pagination) for more information.
	Cursor string `json:"cursor,omitempty"`
	// [Errors](#type-error) encountered during the search.
	Errors []ModelError `json:"errors,omitempty"`
}
