/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// CatalogCustomAttributeDefinitionType : Defines the possible types for a custom attribute.
type CatalogCustomAttributeDefinitionType string

// List of CatalogCustomAttributeDefinitionType
const (
	ATTRIBUTE_TYPE_DO_NOT_USE_CatalogCustomAttributeDefinitionType CatalogCustomAttributeDefinitionType = "ATTRIBUTE_TYPE_DO_NOT_USE"
	STRING__CatalogCustomAttributeDefinitionType                   CatalogCustomAttributeDefinitionType = "STRING"
	INTEGER_CatalogCustomAttributeDefinitionType                   CatalogCustomAttributeDefinitionType = "INTEGER"
	BOOLEAN_CatalogCustomAttributeDefinitionType                   CatalogCustomAttributeDefinitionType = "BOOLEAN"
	NUMBER_CatalogCustomAttributeDefinitionType                    CatalogCustomAttributeDefinitionType = "NUMBER"
	SELECTION_CatalogCustomAttributeDefinitionType                 CatalogCustomAttributeDefinitionType = "SELECTION"
	STRING_INT_CatalogCustomAttributeDefinitionType                CatalogCustomAttributeDefinitionType = "STRING_INT"
	TOKEN_INT_CatalogCustomAttributeDefinitionType                 CatalogCustomAttributeDefinitionType = "TOKEN_INT"
)
