/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// LoyaltyProgramAccrualRuleType : The type of the accrual rule that defines how buyers can earn points.
type LoyaltyProgramAccrualRuleType string

// List of LoyaltyProgramAccrualRuleType
const (
	VISIT_LoyaltyProgramAccrualRuleType          LoyaltyProgramAccrualRuleType = "VISIT"
	SPEND_LoyaltyProgramAccrualRuleType          LoyaltyProgramAccrualRuleType = "SPEND"
	ITEM_VARIATION_LoyaltyProgramAccrualRuleType LoyaltyProgramAccrualRuleType = "ITEM_VARIATION"
	CATEGORY_LoyaltyProgramAccrualRuleType       LoyaltyProgramAccrualRuleType = "CATEGORY"
)
