/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1Page
type V1Page struct {
	// The page's unique identifier.
	Id string `json:"id,omitempty"`
	// The page's name, if any.
	Name string `json:"name,omitempty"`
	// The page's position in the merchant's list of pages. Always an integer between 0 and 6, inclusive.
	PageIndex int32 `json:"page_index,omitempty"`
	// The cells included on the page.
	Cells []V1PageCell `json:"cells,omitempty"`
}
