/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1Settlement
type V1Settlement struct {
	// The settlement's unique identifier.
	Id         string              `json:"id,omitempty"`
	Status     *V1SettlementStatus `json:"status,omitempty"`
	TotalMoney *V1Money            `json:"total_money,omitempty"`
	// The time when the settlement was submitted for deposit or withdrawal, in ISO 8601 format.
	InitiatedAt string `json:"initiated_at,omitempty"`
	// The Square-issued unique identifier for the bank account associated with the settlement.
	BankAccountId string `json:"bank_account_id,omitempty"`
	// The entries included in this settlement.
	Entries []V1SettlementEntry `json:"entries,omitempty"`
}
