/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1EmployeeRolePermissions string

// List of V1EmployeeRolePermissions
const (
	ACCESS_SALES_HISTORY_V1EmployeeRolePermissions          V1EmployeeRolePermissions = "REGISTER_ACCESS_SALES_HISTORY"
	APPLY_RESTRICTED_DISCOUNTS_V1EmployeeRolePermissions    V1EmployeeRolePermissions = "REGISTER_APPLY_RESTRICTED_DISCOUNTS"
	CHANGE_SETTINGS_V1EmployeeRolePermissions               V1EmployeeRolePermissions = "REGISTER_CHANGE_SETTINGS"
	EDIT_ITEM_V1EmployeeRolePermissions                     V1EmployeeRolePermissions = "REGISTER_EDIT_ITEM"
	ISSUE_REFUNDS_V1EmployeeRolePermissions                 V1EmployeeRolePermissions = "REGISTER_ISSUE_REFUNDS"
	OPEN_CASH_DRAWER_OUTSIDE_SALE_V1EmployeeRolePermissions V1EmployeeRolePermissions = "REGISTER_OPEN_CASH_DRAWER_OUTSIDE_SALE"
	VIEW_SUMMARY_REPORTS_V1EmployeeRolePermissions          V1EmployeeRolePermissions = "REGISTER_VIEW_SUMMARY_REPORTS"
)
