/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerminalActionQueryFilter struct {
	// `TerminalAction`s associated with a specific device. If no device is specified then all `TerminalAction`s for the merchant will be displayed.
	DeviceId  string     `json:"device_id,omitempty"`
	CreatedAt *TimeRange `json:"created_at,omitempty"`
	// Filter results with the desired status of the `TerminalAction` Options: `PENDING`, `IN_PROGRESS`, `CANCEL_REQUESTED`, `CANCELED`, `COMPLETED`
	Status string                    `json:"status,omitempty"`
	Type_  *TerminalActionActionType `json:"type,omitempty"`
}
