/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SearchCatalogItemsRequestStockLevel : Defines supported stock levels of the item inventory.
type SearchCatalogItemsRequestStockLevel string

// List of SearchCatalogItemsRequestStockLevel
const (
	STOCK_LEVEL_DO_NOT_USE_SearchCatalogItemsRequestStockLevel SearchCatalogItemsRequestStockLevel = "STOCK_LEVEL_DO_NOT_USE"
	OUT_SearchCatalogItemsRequestStockLevel                    SearchCatalogItemsRequestStockLevel = "OUT"
	LOW_SearchCatalogItemsRequestStockLevel                    SearchCatalogItemsRequestStockLevel = "LOW"
)
