/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1TimecardEvent
type V1TimecardEvent struct {
	// The event's unique ID.
	Id        string                    `json:"id,omitempty"`
	EventType *V1TimecardEventEventType `json:"event_type,omitempty"`
	// The time the employee clocked in, in ISO 8601 format.
	ClockinTime string `json:"clockin_time,omitempty"`
	// The time the employee clocked out, in ISO 8601 format.
	ClockoutTime string `json:"clockout_time,omitempty"`
	// The time when the event was created, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
}
