/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CardForgottenWebhookCard struct {
	// Unique ID for this card. Generated by Square.
	Id string `json:"id,omitempty"`
	// The ID of a customer created using the Customers API associated with the card.
	CustomerId string `json:"customer_id,omitempty"`
	// Indicates whether or not a card can be used for payments.
	Enabled bool `json:"enabled,omitempty"`
	// An optional user-defined reference ID that associates this card with another entity in an external system. For example, a customer ID from an external customer management system.
	ReferenceId string `json:"reference_id,omitempty"`
	// Current version number of the card. Increments with each card update. Requests to update an existing Card object will be rejected unless the version in the request matches the current version for the Card.
	Version int64 `json:"version,omitempty"`
	// The ID of the merchant associated with the card.
	MerchantId string `json:"merchant_id,omitempty"`
}
