/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the payment details of a card to be used for payments. These details are determined by the payment token generated by Web Payments SDK.
type Card struct {
	// Unique ID for this card. Generated by Square.
	Id        string     `json:"id,omitempty"`
	CardBrand *CardBrand `json:"card_brand,omitempty"`
	// The last 4 digits of the card number.
	Last4 string `json:"last_4,omitempty"`
	// The expiration month of the associated card as an integer between 1 and 12.
	ExpMonth int64 `json:"exp_month,omitempty"`
	// The four-digit year of the card's expiration date.
	ExpYear int64 `json:"exp_year,omitempty"`
	// The name of the cardholder.
	CardholderName string   `json:"cardholder_name,omitempty"`
	BillingAddress *Address `json:"billing_address,omitempty"`
	// Intended as a Square-assigned identifier, based on the card number, to identify the card across multiple locations within a single application.
	Fingerprint string `json:"fingerprint,omitempty"`
	// The ID of a customer created using the Customers API to be associated with the card.
	CustomerId string `json:"customer_id,omitempty"`
	// An optional user-defined reference ID that associates this card with another entity in an external system. For example, a customer ID from an external customer management system.
	ReferenceId string `json:"reference_id,omitempty"`
	// Indicates whether or not a card can be used for payments.
	Enabled     bool             `json:"enabled,omitempty"`
	CardType    *CardType        `json:"card_type,omitempty"`
	PrepaidType *CardPrepaidType `json:"prepaid_type,omitempty"`
	// The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API returns this field.
	Bin string `json:"bin,omitempty"`
	// Current version number of the card. Increments with each card update. Requests to update an existing Card object will be rejected unless the version in the request matches the current version for the Card.
	Version int64 `json:"version,omitempty"`
}
