/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a promotion for a [loyalty program](entity:LoyaltyProgram). Loyalty promotions enable buyers to earn extra points on top of those earned from the base program.  A loyalty program can have a maximum of 10 loyalty promotions with an `ACTIVE` or `SCHEDULED` status.
type LoyaltyPromotion struct {
	// The Square-assigned ID of the promotion.
	Id string `json:"id,omitempty"`
	// The name of the promotion.
	Name          string                             `json:"name"`
	Incentive     *LoyaltyPromotionIncentive         `json:"incentive"`
	AvailableTime *LoyaltyPromotionAvailableTimeData `json:"available_time"`
	TriggerLimit  *LoyaltyPromotionTriggerLimit      `json:"trigger_limit,omitempty"`
	Status        *LoyaltyPromotionStatus            `json:"status,omitempty"`
	// The timestamp of when the promotion was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The timestamp of when the promotion was canceled, in RFC 3339 format.
	CanceledAt string `json:"canceled_at,omitempty"`
	// The timestamp when the promotion was last updated, in RFC 3339 format.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The ID of the [loyalty program](entity:LoyaltyProgram) associated with the promotion.
	LoyaltyProgramId        string `json:"loyalty_program_id,omitempty"`
	MinimumSpendAmountMoney *Money `json:"minimum_spend_amount_money,omitempty"`
}
