/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Either the `order_entries` or `orders` field is set, depending on whether `return_entries` is set on the [SearchOrdersRequest](api-endpoint:Orders-SearchOrders).
type SearchOrdersResponse struct {
	// A list of [OrderEntries](entity:OrderEntry) that fit the query conditions. The list is populated only if `return_entries` is set to `true` in the request.
	OrderEntries []OrderEntry `json:"order_entries,omitempty"`
	// A list of [Order](entity:Order) objects that match the query conditions. The list is populated only if `return_entries` is set to `false` in the request.
	Orders []Order `json:"orders,omitempty"`
	// The pagination cursor to be used in a subsequent request. If unset, this is the final response. For more information, see [Pagination](https://developer.squareup.com/docs/basics/api101/pagination).
	Cursor string `json:"cursor,omitempty"`
	// [Errors](entity:Error) encountered during the search.
	Errors []ModelError `json:"errors,omitempty"`
}
